<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Route->Title = 'Promo Video Headers';
$Route->Info = 'Mainly designed for use as page intros as an artsy way to add motion to the background of an element.';

$Route->Pathbar->Items->Push(Atlantis\Struct\Item::New(
	Title: 'PromoVideo',
	URL: '/docs/ui/promo-video'
));

$Surface->Area('sensei/docs/__example-via-area', [
	'Areas' => [
		'With Static Text'
		=> 'sensei/docs/ui/promo-video/example-static',

		'With Typeified Text'
		=> 'sensei/docs/ui/promo-video/example-typeify'
	]
]);
