<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Surface->Area('sensei/docs/__header', [
	'Title' => 'Promo Video',
	'Trail' => [ Atlantis\Struct\Item::New(Title: 'UI', URL: '/docs/ui') ]
]);
$Surface->Area('sensei/docs/__example-via-area', [
	'Areas' => [
		'With Static Text'
		=> 'sensei/docs/ui/promo-video/example-static',

		'With Typeified Text'
		=> 'sensei/docs/ui/promo-video/example-typeify'
	]
]);
