<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Surface->Set([
	'Page.Section.Title' => 'UI Elements',
	'Page.Title'         => 'PromoVideo',
	'Page.Info'          => NULL
]);

$Surface->Area('sensei/docs/__example-via-area', [
	'Areas' => [
		'With Static Text'
		=> 'sensei/docs/ui/promo-video/example-static',

		'With Typeified Text'
		=> 'sensei/docs/ui/promo-video/example-typeify'
	]
]);
