<?php

use Nether\Atlantis\UI\Dropdown;

/**
 * @var Nether\Atlantis\Routes\Profile\ProfileWeb $Route
 * @var Nether\Atlantis\Profile\Entity $Profile
 * @var Nether\Common\Datastore $ExtraData
 */

//$AdminMenu = $Route::ProfileViewAdminMenu($App, $Profile, $ExtraData);
$Address = $Profile->GetAddresssLines();
$MapURL = $Profile->GetMapURL();

?>

<div class="row">

	<?php if(isset($Profile->CoverImage)): ?>
	<div class="col-12 col-md-3 mb-4 mb-md-0">
		<div class="ratiobox widescreen rounded">
			<div class="position-absolutely wallpapered covered rounded" style="transform:scale(1.1);filter:blur(26px);background-image:url(<?php $Util->Print($Profile->GetCoverImageURL()) ?>);"></div>
			<div class="position-absolutely wallpapered rounded contained bg-transparent" style="background-image:url(<?php $Util->Print($Profile->GetCoverImageURL()) ?>);">
				<a class="position-absolutely" href="<?php $Util->Print($Profile->Alias) ?>"></a>
			</div>
		</div>
	</div>
	<?php endif; ?>

	<div class="col">
		<div class="row">
			<div class="col">
				<h2 class="mb-0"><a href=""><?php $Util->Print($Profile->Title) ?></a></h2>
			</div>

			<?php if($Route->IsUserAdmin()): ?>
			<div class="col-auto">
				<?php echo Dropdown::FromSurfaceWith($Surface, [ 'Menu' => $AdminMenu, 'MenuBtnStyleClass'=> 'btn-outline-light', 'ItemBtnStyleClass'=> 'btn-light' ]) ?>
			</div>
			<?php endif; ?>

		</div>
		<hr class="mt-1 mb-3" />
		<div class="mb-0">
			<?php $Surface->Area('widgets/tag-buttons', [ 'Tags'=> $Tags ]) ?>
		</div>

		<?php if($Address->Count()): ?>
		<div class="font-size-large">
			<span class="tt-upper fw-bold">Address:</span>
			<a class="td-underline" href="<?php $Util->Print($Profile->GetMapURL()) ?>"><?php $Util->Print($Address->Join(' ')) ?></a>
		</div>
		<?php elseif($Profile->AddressState): ?>
		<div class="font-size-large">
			<span class="tt-upper fw-bold">State:</span>
			<?php $Util->Print($Profile->AddressState) ?>
		</div>
		<?php endif; ?>

		<?php if($Profile->SocialData->HasAnyItems()): ?>
		<div class="row font-size-large tight align-items-center">
			<div class="col-auto">
				<span class="fw-bold text-uppercase">Links:</span>
			</div>
			<?php foreach($Profile->SocialData->GetIterator() as $Key => $Val): ?>
			<div class="col-auto">
				<a href="<?php $Util->Print($Val) ?>" class="ml-2" target="_blank">
					<i class="<?php $Util->Print($Profile->SocialData->GetIconStyleClass($Key)) ?>"></i>
				</a>
			</div>
			<?php endforeach; unset($Key, $Val); ?>
		</div>
		<?php endif; ?>

	</div>
</div>
