<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Common\Datastore $SectionsBefore
 * @var Common\Datastore $SectionsAfter
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\Profile\Entity $Profile
 * @var Database\ResultSet $Tags
 * @var Database\ResultSet $Photos
 * @var Database\ResultSet $Videos
 * @var Database\ResultSet $Related
 */

$AdminMenu ??= NULL;
$Embed ??= FALSE;

$Scopeify = (
	fn($Item): array
	=> array_merge(
		$__SCOPE,
		[ 'Element'=> $Item, 'Parent'=> $Profile ],
		$Item->GetExtraData()->GetData()
	)
);

$PhotoItemClasses = 'col-12 col-md-3 mb-4';

if(isset($Photos) && $Photos->Count() >= 6) {
	$PhotoItemClasses = 'col-6 col-md-3 mb-4';
}

?>

<?php $Surface->Area('profile/view-before', $__SCOPE) ?>

<div class="<?php $Util->Print($Embed ? 'atl-profile-view' : 'container atl-profile-view') ?>">

	<?php if(!$Embed): ?>

	<?php if(!$Profile->Enabled): ?>
	<div class="alert alert-primary text-align-center mb-4">This profile is currently disabled.</div>
	<?php endif; ?>

	<!-- HEADER -->
	<div class="mb-6">
		<?php

		$Surface->Area('profile/header', [
			'Profile'   => $Profile,
			'AdminMenu' => $AdminMenu,
			'ExtraData' => $ExtraData,
			'Tags'      => $Tags
		])

		?>
	</div>
	<?php else: ?>
	<div class="mb-4">
	<?php $Surface->Area('widgets/tag-buttons', [ 'Tags'=> $Tags ]) ?>
	</div>
	<?php endif; ?>

	<?php if($Profile->HasDetails()): ?>
	<!-- DETAILS -->
	<div class="mb-8">
		<h2 class="text-uppercase mb-0">Description</h2>
		<hr class="mt-1 mb-3" />

		<?php $Surface->Area('profile/view-desc-before', $__SCOPE) ?>

		<?php if($Profile->Details): ?>
		<div id="EditorContent" class="EditorContent"><?php echo $Profile->Details ?></div>
		<?php else: ?>
		<div class="fst-italic">No additional information has been added.</div>
		<?php endif; ?>

		<?php $Surface->Area('profile/view-desc-after', $__SCOPE) ?>
	</div>
	<?php endif; ?>

	<?php if($Route->IsUserAdmin() && $Profile->HasAdminNotes()): ?>
	<div class="jumbotron rounded p-2 mb-4">
		<div class="fw-bold">Admin Notes</div>
		<div id="EntityAdminNotes">
			<?php echo $Profile->ExtraData['AdminNotes'] ?>
		</div>
	</div>
	<?php endif; ?>

	<!-- SECTIONS: BEFORE -->
	<?php if($SectionsBefore): foreach($SectionsBefore as $Item): /** @var Atlantis\Struct\Item $Item */ ?>
	<div class="atl-profile-section atl-profile-section-before">
		<?php
		if(is_callable($Item)) $Item($__SCOPE);
		else echo $Item;
		?>
	</div>
	<?php endforeach; endif; unset($Item); ?>

	<?php $Surface->Area('profile/view-extend-before', $__SCOPE) ?>

	<?php if($News && $News->Count()): ?>
	<!-- NEWS -->
	<div class="mb-8">
		<h2 class="text-uppercase mb-0">News</h2>
		<hr class="mt-1 mb-3" />

		<div class="hr-hide-last">
			<?php $Surface->Area('blog/widgets/post-list-lite', [ 'Posts'=> $News ]) ?>
		</div>
	</div>
	<?php endif; ?>

	<?php

	if(isset($Photos) && $Photos->Total)
	$Surface->Area('profile/section/photos', [ 'Profile'=> $Profile, 'Photos'=> $Photos ]);

	if(isset($Videos) && $Videos->Total)
	$Surface->Area('profile/section/videos', [ 'Profile'=> $Profile, 'Videos'=> $Videos ]);

	if(isset($Links) && $Links->Total)
	$Surface->Area('profile/section/related-links', [ 'Profile'=> $Profile, 'Links'=> $Links ]);

	if(isset($Related) && $Related->Count()) {
		echo '<h2 class="text-uppercase mb-0">Related Profiles</h2>';
		echo '<hr class="mt-1 mb-3" />';
		$Surface->Area('widgets/profile-list-lite', [ 'Profiles'=> $Related ]);
	}

	?>

	<!-- SECTIONS: AFTER -->
	<?php if($SectionsAfter): foreach($SectionsAfter as $Item): /** @var Atlantis\Struct\Item $Item */ ?>
	<div class="atl-profile-section atl-profile-section-after">
		<?php
		if(is_callable($Item)) $Item($__SCOPE);
		else echo $Item;
		?>
	</div>
	<?php endforeach; endif; unset($Item); ?>

	<?php $Surface->Area('profile/view-extend-after', $__SCOPE) ?>

	<!-- FOOTER -->
	<div class="mb-6">
		<?php

		$Surface->Area('profile/footer', [
			'Profile'   => $Profile,
			'AdminMenu' => $AdminMenu,
			'ExtraData' => $ExtraData,
			'Tags'      => $Tags
		])

		?>
	</div>

</div>

<script type="module">
import SimpleLightbox from '/themes/default/lib/js/simplelightbox.js';
import API            from '/share/nui/api/json.js';
import DialogUtil     from '/share/nui/util/dialog.js';

jQuery(function() {



	////////

	jQuery('[data-profile-cmd="z-related-link"]')
	.on('click', function() {

		let that = jQuery(this);
		let id = that.attr('data-id');
		let uuid = that.attr('data-uuid');
		let endpoint = '/api/media/link';

		let parentType = 'Profile.Entity';
		let parentUUID = <?php echo json_encode($Profile->UUID) ?>;

		let diag = new DialogUtil.Window({
			title: 'New Related Link',
			labelAccept: 'Save',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, id),
				new DialogUtil.Field('text', 'Title', 'Title'),
				new DialogUtil.Field('text', 'URL', 'URL'),
				new DialogUtil.Field('date', 'DateCreated', 'Date'),
				new DialogUtil.Field('hidden', 'ParentType', null, parentType),
				new DialogUtil.Field('hidden', 'ParentUUID', null, parentUUID)
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('POST', endpoint, data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.show();

		return false;
	});

	jQuery('[data-link-cmd="edit"]')
	.on('click', function(){

		let that = jQuery(this);
		let id = that.attr('data-id');
		let uuid = that.attr('data-uuid');
		let endpoint = '/api/media/link';

		let diag = new DialogUtil.Window({
			title: 'Edit Related Link',
			labelAccept: 'Save',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, id),
				new DialogUtil.Field('text', 'Title', 'Title'),
				new DialogUtil.Field('text', 'URL', 'URL'),
				new DialogUtil.Field('date', 'DateCreated', 'Date')
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('PATCH', endpoint, data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.fillByRequest(
			'GET', endpoint,
			{ ID: id },
			true
		);

		return false;
	});

	jQuery('[data-link-cmd="delete"]')
	.on('click', function(){

		let that = jQuery(this);
		let id = that.attr('data-id');
		let uuid = that.attr('data-uuid');
		let endpoint = '/api/media/link';

		let diag = new DialogUtil.Window({
			title: 'Delete Releated Link',
			body: 'Really delete this link?',
			labelAccept: 'Yes',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, id)
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('DELETE', endpoint, data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.fillByRequest(
			'GET', endpoint,
			{ ID: id },
			true
		);

		return false;
	});

	return;
});
</script>
