<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\Profile\Entity $Profile
 * @var Database\ResultSet $Tags
 * @var Database\ResultSet $Photos
 * @var Database\ResultSet $Videos
 */

$Address = $Profile->GetAddresssLines();
$MapURL = $Profile->GetMapURL();

$AdminMenu = NULL;

if($Route->IsUserAdmin()) {
	$AdminMenu = Atlantis\Struct\DropdownMenu::New();

	$Plugins = (
		($App->Plugins)
		->Get(Atlantis\Plugins\PrototypeAdminMenuInterface::class)
		->Remap(fn(string $C)=> new $C($App))
		->Accumulate(new Common\Datastore, (
			fn(Common\Datastore $C, Atlantis\Plugins\PrototypeAdminMenuInterface $P)
			=> $C->MergeRight($P->GetItems( $Profile ))
		))
		->Sort()
	);

	($AdminMenu)
	->ItemNew('Manage Tags', 'mdi-tag-multiple', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'tags' ], TRUE))
	->ItemNew('Edit Title & Alias', 'mdi-pencil', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'title' ], TRUE))
	->ItemNew('Edit Description', 'mdi-pencil', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'details' ], TRUE))
	->ItemNew('Edit Street Address', 'mdi-pencil', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'address' ], TRUE))
	->ItemNew('Edit Web Links', 'mdi-pencil', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'links' ], TRUE))
	->ItemNew('Enable Profile', 'mdi-eye', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'enable' ], TRUE), If: !$Profile->Enabled)
	->ItemNew('Disable Profile', 'mdi-eye-off', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'disable' ], TRUE), If: $Profile->Enabled)
	->ItemNew('-');

	if($Plugins && $Plugins->Count()) {
		$AdminMenu->ItemPush($Plugins);
		$AdminMenu->ItemNew('-');
	}

	($AdminMenu)
	->ItemNew('Upload Photos', 'mdi-upload', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'photo' ], TRUE))
	->ItemNew('Add Related Link', 'mdi-web', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'related-link' ], TRUE))
	->ItemNew('Add Video URL', 'mdi-video', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'videotp' ], TRUE))
	->ItemNew('-');

	($AdminMenu)
	->ItemNew('Delete', 'mdi-delete', Attr: $Profile->GetDataAttr([ 'profile-cmd' => 'delete' ], TRUE));
}

$FilterTags = fn(Atlantis\Tag\Entity $T)=> $T->Type !== 'site';

$GetMenuForRelatedLink = function(Atlantis\Media\RelatedLink $Rel) use($Route) {

	$Menu = Atlantis\Struct\DropdownMenu::New();
	$Menu->ItemNew('Edit Link', 'mdi-pencil', Attr: $Rel->GetDataAttr([ 'link-cmd' => 'edit' ], TRUE));
	$Menu->ItemNew('Delete', 'mdi-close', Attr: $Rel->GetDataAttr([ 'link-cmd' => 'delete' ], TRUE));

	return $Menu;
};

?>

<?php $Surface->Area('design/subheader'); ?>

<?php $Surface->Area('profile/view-before-pre', $__SCOPE) ?>

<div class="container pt-6 pb-6">

	<?php if(!$Profile->Enabled): ?>
	<div class="alert alert-primary text-align-center">This profile is currently disabled.</div>
	<?php endif; ?>

	<!-- HEADER -->
	<div class="mb-6">
		<div class="row">
			<?php if(isset($Profile->CoverImage)): ?>
			<div class="col-12 col-md-3 mb-4 mb-md-0">
				<div class="ratiobox widescreen rounded">
					<div class="position-absolutely wallpapered covered rounded" style="transform:scale(1.1);filter:blur(26px);background-image:url(<?php $Util->Print($Profile->GetCoverImageURL()) ?>);"></div>
					<div class="position-absolutely wallpapered rounded contained bg-transparent" style="background-image:url(<?php $Util->Print($Profile->GetCoverImageURL()) ?>);">
						<a class="position-absolutely" href="<?php $Util->Print($Profile->Alias) ?>"></a>
					</div>
				</div>
			</div>
			<?php endif; ?>
			<div class="col">
				<div class="row">
					<div class="col">
						<h2 class="mb-0"><?php $Util->Print($Profile->Title) ?></h2>
					</div>

					<?php if($Route->IsUserAdmin()): ?>
					<div class="col-auto">
						<?php $Surface->Area('widgets/dropdown', [ 'Dropdown'=> $AdminMenu ]) ?>
					</div>
					<?php endif; ?>

				</div>
				<hr class="mt-1 mb-3" />
				<div class="mb-0">
					<?php $Surface->Area('widgets/tag-buttons', [ 'Tags'=> $Tags, 'URL'=> $Route->GetTagURL() ]) ?>
				</div>

				<?php if($Address->Count()): ?>
				<div class="font-size-large">
					<span class="tt-upper fw-bold">Address:</span>
					<a class="td-underline" href="<?php $Util->Print($Profile->GetMapURL()) ?>"><?php $Util->Print($Address->Join(' ')) ?></a>
				</div>
				<?php elseif($Profile->AddressState): ?>
				<div class="font-size-large">
					<span class="tt-upper fw-bold">State:</span>
					<?php $Util->Print($Profile->AddressState) ?>
				</div>
				<?php endif; ?>

				<?php if($Profile->SocialData->HasAnyItems()): ?>
				<div class="row font-size-large tight align-items-center">
					<div class="col-auto">
						<span class="fw-bold text-uppercase">Links:</span>
					</div>
					<?php foreach($Profile->SocialData->GetIterator() as $Key => $Val): ?>
					<div class="col-auto">
						<a href="<?php $Util->Print($Val) ?>" class="ml-2" target="_blank">
							<i class="<?php $Util->Print($Profile->SocialData->GetIconStyleClass($Key)) ?>"></i>
						</a>
					</div>
					<?php endforeach; unset($Key, $Val); ?>
				</div>
				<?php endif; ?>

			</div>
		</div>
	</div>

	<!-- DETAILS -->
	<div class="mb-8">
		<h2 class="text-uppercase mb-0">Description</h2>
		<hr class="mt-1 mb-3" />

		<?php $Surface->Area('profile/view-desc-pre', $__SCOPE) ?>

		<?php if($Profile->Details): ?>
		<div id="EditorContent" class="EditorContent"><?php echo $Profile->Details ?></div>
		<?php else: ?>
		<div class="fst-italic">No additional information has been added.</div>
		<?php endif; ?>
	</div>

	<?php if($News && $News->Count()): ?>
	<!-- NEWS -->
	<div class="mb-8">
		<h2 class="text-uppercase mb-0">News</h2>
		<hr class="mt-1 mb-3" />

		<div class="hr-hide-last">
			<?php $Surface->Area('blog/widgets/post-list-lite', [ 'Posts'=> $News ]) ?>
		</div>
	</div>
	<?php endif; ?>

	<?php $Surface->Area('profile/view-extend-pre', $__SCOPE) ?>

	<?php if(isset($Photos) && $Photos->Total): ?>
	<!-- PHOTOS -->
	<div class="mb-8">
		<h2 class="text-uppercase mb-0">Photos (<?php $Util->Print($Photos->Total) ?>)</h2>
		<hr class="mt-1 mb-3" />

		<div class="row">
			<?php foreach($Photos as $Photo): /** @var Atlantis\Media\File $Photo */ ?>
			<div class="col-6 col-md-3 mb-4">
				<div class="cursor-pointer ratiobox widescreen wallpapered contained rounded bg-dark PhotoGalleryItem" style="background-image:url(<?php $Util->Print($Photo->GetPublicURL()) ?>);" data-url-lg="<?php $Util->Print($Photo->GetPublicURL()) ?>">
					<div class="position-absolute position-bottom position-right p-1">
						<?php if($Route->IsUserAdmin()): ?>
						<button class="btn <?php $Util->Print($Profile->CoverImageID === $Photo->ID ? 'btn-success' : 'btn-dark') ?>" <?php echo $Profile->GetDataAttrForHTML(['profile-cmd'=> 'photoset', 'photo-id'=> $Photo->ID]) ?>><i class="mdi mdi-account-star mr-0"></i></button>
						<button class="btn btn-danger" <?php echo $Photo->GetDataAttrForHTML(['photolib-cmd'=> 'delete']) ?>><i class="mdi mdi-trash-can mr-0"></i></button>
						<?php endif; ?>
					</div>
				</div>
			</div>
			<?php endforeach; unset($Photo); ?>
		</div>
	</div>
	<?php endif; ?>

	<?php if(isset($Videos) && $Videos->Total): ?>
	<!-- VIDEOS -->
	<div class="mb-8">
		<h2 class="text-uppercase mb-0">Videos (<?php $Util->Print($Videos->Total) ?>)</h2>
		<hr class="mt-1 mb-3" />

		<?php $Surface->Area('widgets/media/video-tp-list', [ 'Videos'=> $Videos ]) ?>
	</div>
	<?php endif; ?>

	<?php if(isset($Links) && $Links->Total): ?>
	<!-- RELATED LINKS -->
	<div class="mb-8">
		<h2 class="text-uppercase mb-0">Related Links (<?php $Util->Print($Links->Total) ?>)</h2>
		<hr class="mt-1 mb-3" />

		<?php foreach($Links as $Rel): ?>
		<div class="row align-items-center">
			<div class="col">
				<div class="fst-italic">
					<?php $Util->Print(Atlantis\Util::DomainFromURL($Rel->URL)) ?>
				</div>
				<div>
					<a href="<?php $Util->Print($Rel->URL) ?>" target="_blank" class="fw-bold"><?php $Util->Print($Rel->Title) ?></a>
				</div>
			</div>
			<?php if($Route->IsUserAdmin()): ?>
			<div class="col-auto">
				<?php $Surface->Area('widgets/dropdown', [ 'Menu'=> $GetMenuForRelatedLink($Rel) ]) ?>
			</div>
			<?php endif; ?>
		</div>
		<hr />
		<?php endforeach; unset($Rel); ?>
	</div>
	<?php endif; ?>

	<?php $Surface->Area('profile/view-extend', $__SCOPE) ?>

</div>

<script type="module">
import SimpleLightbox from '/themes/default/lib/js/simplelightbox.js';
import API            from '/share/nui/api/json.js';
import DialogUtil     from '/share/nui/util/dialog.js';

jQuery(function() {

	let gallery = new SimpleLightbox('.PhotoGalleryItem', {
		captions: true,
		captionSelector: 'self',
		scrollZoom: false,
		fileExt: false,
		sourceAttr: 'data-url-lg'
	});

	////////

	jQuery('[data-profile-cmd="related-link"]')
	.on('click', function() {

		let that = jQuery(this);
		let id = that.attr('data-id');
		let uuid = that.attr('data-uuid');
		let endpoint = '/api/media/link';

		let parentType = 'Profile.Entity';
		let parentUUID = <?php echo json_encode($Profile->UUID) ?>;

		let diag = new DialogUtil.Window({
			title: 'New Related Link',
			labelAccept: 'Save',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, id),
				new DialogUtil.Field('text', 'Title', 'Title'),
				new DialogUtil.Field('text', 'URL', 'URL'),
				new DialogUtil.Field('date', 'DateCreated', 'Date'),
				new DialogUtil.Field('hidden', 'ParentType', null, parentType),
				new DialogUtil.Field('hidden', 'ParentUUID', null, parentUUID)
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('POST', endpoint, data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.show();

		return false;
	});

	jQuery('[data-link-cmd="edit"]')
	.on('click', function(){

		let that = jQuery(this);
		let id = that.attr('data-id');
		let uuid = that.attr('data-uuid');
		let endpoint = '/api/media/link';

		let diag = new DialogUtil.Window({
			title: 'Edit Related Link',
			labelAccept: 'Save',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, id),
				new DialogUtil.Field('text', 'Title', 'Title'),
				new DialogUtil.Field('text', 'URL', 'URL'),
				new DialogUtil.Field('date', 'DateCreated', 'Date')
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('PATCH', endpoint, data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.fillByRequest(
			'GET', endpoint,
			{ ID: id },
			true
		);

		return false;
	});

	jQuery('[data-link-cmd="delete"]')
	.on('click', function(){

		let that = jQuery(this);
		let id = that.attr('data-id');
		let uuid = that.attr('data-uuid');
		let endpoint = '/api/media/link';

		let diag = new DialogUtil.Window({
			title: 'Delete Releated Link',
			body: 'Really delete this link?',
			labelAccept: 'Yes',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, id)
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('DELETE', endpoint, data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.fillByRequest(
			'GET', endpoint,
			{ ID: id },
			true
		);

		return false;
	});

	return;
});
</script>
