<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * ...
 */

################################################################################
################################################################################

$ItemTemplate =<<< EOL
		<item>
			<title>{%Title%}</title>
			<pubDate>{%Date%}</pubDate>
			<link>{%URL%}</link>
			<guid isPermaLink="false">{%UUID%}</guid>
			<description>{%Excerpt%}</description>
		</item>
EOL;

################################################################################
################################################################################

foreach($Posts as $Post) {
	/** @var Blog\Post $Post */

	echo Common\Text::TemplateReplaceTokens($ItemTemplate, [
		'Title'   => htmlspecialchars($Post->Title),
		'Date'    => $Post->DateCreated->Get(DateTime::RFC2822),
		'UUID'    => $Post->UUID,
		'URL'     => $Post->GetPageURL(),
		'Excerpt' => htmlspecialchars($Post->GetExcerpt())
	]);

	continue;
}
