<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\UI\Alphabar $Element
 */

$Field ??= $Element->Field;
$BaseURL ??= $Element->BaseURL;
$Items ??= $Element->Items;

$ClassItemNormal ??= 'btn-outline-light';
$ClassItemSelect ??= 'btn-light';

$GetLetterURL = (fn(string $Val)=> sprintf(
	'%s%s',
	$BaseURL,
	$Route->QueryCooker(array_merge(
		$Element->GetQueryBroth($Val),
		[ 'page'=> NULL ]
	))
));

?>

<style type="text/css">
	.atl-ui-alphabar { --bs-gutter-x: 0.0rem; justify-content: center; }
	.atl-ui-alphabar-item { width: 3.846% !important; }

	.atl-ui-alphabar-item .btn {
		background-color: var(--theme-light-fg);
		border: 0px;
		border-left: 1px solid var(--theme-grey-lt);
		border-radius: 0px;
		color: var(--theme-light);
		margin: 0.25rem 0px;
		padding: 0px 0px;
		text-align: center;
	}

	.atl-ui-alphabar-item:first-of-type .btn {
		border-left: 0px;
	}

	.atl-ui-alphabar-item.selected {
		color: var(--theme-light);
	}

	.atl-ui-alphabar-item.selected .btn {
		border: 0px solid var(--theme-light);
		background-color: var(--theme-light);
		color: var(--theme-light-fg);
	}

	.atl-ui-alphabar-filters {
		margin-bottom: 1rem;
	}

	.atl-ui-alphabar-filter-item.selected {
		font-weight: bold;
		border-bottom: 3px solid var(--theme-primary) !important;
	}

	@media(max-width: 1199.99px) {
		.atl-ui-alphabar-item { width: 7.692% !important; }
	}

	@media(max-width: 767.99px) {
		.atl-ui-alphabar-item { width: 7.692% !important; }
	}
</style>

<div id="<?php $Util->Print($Element->GetID()) ?>" class="row gx-1 gy-2 atl-ui-alphabar" data-field="<?php $Util->Print($Element->Field) ?>">
	<?php foreach($Items as $L): ?>
	<div class="atl-ui-alphabar-item <?php $Util->Print($Element->IsSelected($L) ? 'selected' : '') ?>">
		<a class="btn btn-block" href="<?php $Util->Print($GetLetterURL($L)) ?>">
			<?php $Util->Print($L) ?>
		</a>
	</div>
	<?php endforeach; unset($L); ?>
</div>
