<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Surface->Set([
	'Page.Section.Title' => 'UI Elements',
	'Page.Title'         => 'Pillbox',
	'Page.Info'          => NULL
]);

$Surface->Area('sensei/docs/__example-via-area', [
	'Areas' => [
		'Basic'               => 'sensei/docs/ui/pillbox/example-basic',
		'Dropdown'            => 'sensei/docs/ui/pillbox/example-dropdown',
		'Moredown Auto Fit'   => 'sensei/docs/ui/pillbox/example-moredown-auto',
		'Moredown Set Number' => 'sensei/docs/ui/pillbox/example-moredown-set'
	]
]);
