<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Atlantis\Media\File $Item
 * @var Nether\Database\Struct\PrototypeFindResult $Tags
 */



$Surface
->Set('Page.Title', 'View Media - Dashboard')
->Area('media/dashboard/scripts', $__SCOPE)
->Area('dashboard/nav', [ 'Trail' => [
	'Media'  => NULL,
	'View'   => NULL
]]);

?>

<div class="row justify-content-center">
	<div class="col-12 col-lg-8 mb-4 mb-4 mb-md-0">
		<?php if($Item->Type === 'img'): ?>
		<img src="<?php $Printer($Item->GetPublicURL()) ?>" />
		<?php else: ?>
		[some unviewed media type: <?php $Printer($Item->Type) ?>]
		<?php endif; ?>
	</div>
	<div class="col-12 col-lg-4">
		<div class="jumbotron quotron rounded mb-4">
			<div class="row tight font-size-smaller">

				<div class="col">
					<i class="mdi mdi-fw mdi-pound"></i>
					<strong>ID:</strong>
				</div>
				<div class="col-auto"><?php $Printer($Item->ID) ?></div>
				<div class="col-auto">
					<a href="#" data-nui-copy-value="<?php $Printer($Item->ID) ?>"><i class="mdi mdi-fw mdi-content-copy"></i></a>
				</div>
				<div class="col-12"><hr /></div>

				<div class="col">
					<i class="mdi mdi-fw mdi-liquid-spot"></i>
					<strong>UUID:</strong>
				</div>
				<div class="col-6">
					<div class="text-align-right text-ellipsis"><?php $Printer($Item->UUID) ?></div>
				</div>
				<div class="col-auto">
					<a href="#" data-nui-copy-value="<?php $Printer($Item->UUID) ?>"><i class="mdi mdi-fw mdi-content-copy"></i></a>
				</div>
				<div class="col-12"><hr /></div>

				<div class="col">
					<i class="mdi mdi-fw mdi-file"></i>
					<strong>Type:</strong>
				</div>
				<div class="col-auto"><?php $Printer($Item->Type) ?></div>
				<div class="col-12"><hr /></div>

				<div class="col">
					<i class="mdi mdi-fw mdi-weight"></i>
					<strong>Size:</strong>
				</div>
				<div class="col-auto"><?php $Printer($Item->GetSizeReadable()) ?></div>
				<div class="col-12"><hr /></div>

				<div class="col">
					<i class="mdi mdi-fw mdi-link"></i>
					<strong>URL:</strong>
				</div>
				<div class="col-auto">
					<a href="<?php $Printer($Item->GetPublicURL()) ?>" target="_blank">Link to File</a>
				</div>
				<div class="col-auto">
					<a href="#" data-nui-copy-value="<?php $Printer($Item->GetPublicURL()) ?>"><i class="mdi mdi-fw mdi-content-copy"></i></a>
				</div>
				<div class="col-12"><hr /></div>

				<div class="col">
					<i class="mdi mdi-fw mdi-tag"></i>
					<strong>Tags:</strong>
				</div>
				<div class="col-12 mb-2"></div>
				<div class="col-12">
					<button href="#" class="btn btn-sm pt-1 pb-1 btn-light" data-media-tag-add="<?php $Printer($Item->UUID) ?>" data-media-link-type="<?php $Printer(Nether\Atlantis\Media\FileTagLink::LinkType) ?>">
						<i class="mdi mdi-fw mdi-plus"></i> Add
					</button>

					<?php foreach($Tags as $Link): /** @var Nether\Atlantis\Media\FileTagLink $Link */ ?>
					<a href="#" class="btn btn-sm pt-1 pb-1 btn-outline-light"><?php $Printer($Link->Tag->Name) ?></a>
					<?php endforeach; unset($Tag); ?>
				</div>

			</div>
		</div>

		<div class="jumbotron quotron rounded">
			<button class="btn btn-danger btn-block text-align-left" data-media-delete="<?php $Printer($Item->ID) ?>" data-goto="/dashboard/media/browse">
				<i class="mdi mdi-fw mdi-trash-can"></i>
				Delete
			</button>
		</div>
	</div>
</div>

