<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\Media\VideoThirdParty $Video
 */

?>

<iframe
	class="w-100 h-100 border-0"
	src="https://player.vimeo.com/video/<?php $Util->Print($Video->GetVimeoID()) ?>"
	title="<?php $Util->Print($Video->Title) ?>"

	allow="encrypted-media; picture-in-picture; web-share; fullscreen;"
	allowfullscreen
	seamless
></iframe>
