<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\Profile\Entity $Profile
 * @var Common\Datastore $Videos
 */

################################################################################
############################################################################# ?>

<div class="mb-8">
	<h2 class="text-uppercase mb-0">Videos (<?php $Util->Print($Videos->Count()) ?>)</h2>
	<hr class="mt-1 mb-3" />

	<?php $Surface->Area('widgets/media/video-tp-list', [ 'Videos'=> $Videos, 'ParentUUID'=> $Profile->UUID, 'ShowTags'=> FALSE ]) ?>
</div>
