<?php

$Title ??= NULL;
$Section ??= NULL;
$Content ??= NULL;
$Nav ??= NULL;

$Items = Nether\Common\Datastore::FromArray([
	Nether\Atlantis\Struct\Item::New(Title: 'Docs', URL: '/docs', Classes: [ 'tag' ]),
	Nether\Atlantis\Struct\Item::New(Title: 'UI Elements', URL: '/docs/ui')
]);

if(is_iterable($Nav))
$Items->MergeRight($Nav);

?>

<div class="container pt-6 pb-0">

	<div class="mb-2">
		<?php echo Nether\Atlantis\UI\Pathbar::FromSurfaceWith($Surface, [
			'Classes' => [ 'fs-smaller' ],
			'Items' => $Items
		]); ?>
	</div>

	<div class="jumbotron rounded mb-0">
		<div class="mb-0">
			<?php echo Nether\Atlantis\UI\Article::FromSurfaceWith($Surface, [
				'Title'   => $Title,
				'Section' => $Section,
				'Content' => $Content
			]); ?>
		</div>
	</div>
</div>
