<?php

$Surface->Area('sensei/pages/ui/__intro', [
	'Title'   => 'Ace Code Editor and Viewer',
	'Section' => 'Atlantis\\UI\\AceEditor',
	'Content' => 'Provides for wrapping content into an editable source code editor, provided by Ace not the hardware place.'
]);

$Surface->Area('sensei/pages/ui/__demo-via-area', [
	'Areas' => [
		'Read-Only Code Viewer' => 'sensei/pages/ui/ace-editor/basic'
	]
]);
