<?php

$Surface->Area('sensei/pages/ui/__intro', [
	'Title'   => 'Article Widget',
	'Section' => 'Atlantis\\UI\\Article',
	'Content' => <<< LOL
		Display an article with its misc information typically associated with one.
		This here is actually one being used as like an introductory widget placed within a jumbotron for effect.
	LOL
]);

$Surface->Area('sensei/pages/ui/__demo-via-area', [
	'Areas' => [
		'Basic Article View' => 'sensei/pages/ui/article/basic'
	]
]);
