<?php

use Nether\Atlantis\UI;
use Nether\Common;

$Surface->Area('sensei/pages/ui/__intro', [
	'Title'   => 'Pagination Widget',
	'Section' => 'Atlantis\\UI\\Pager',
	'Content' => <<< LOL
		Provides a Next/Prev page element.
	LOL
]);

$Surface->Area('sensei/pages/ui/__demo-via-area', [
	'Areas' => [
		'Manual Setup'
		=> 'sensei/pages/ui/pager/basic',

		'Setup via Data Collection'
		=> 'sensei/pages/ui/pager/from-resultset1'
	]
]);
