<?php

use Nether\Atlantis;

$Intro = (fn()=> Atlantis\UI\Article::FromSurfaceWith($Surface, [
	'Title'   => 'Promo Video',
	'Section' => 'Atlantis\\UI\\PromoVideo',
	'Content' => 'Mainly designed for use as page headers as an artsy way to add motion to the background of an element.'
]));

$Sections = [
	(fn()=> Atlantis\UI\PromoVideo::FromSurfaceWith($Surface, [
		'VideoURL' => '/themes/default/gfx/splishsplash.mp4',
		'Overlay'  => 'grad-focus-dark',
		'Title'   => 'Video BG',
		'Subline' => 'With Static Text'
	])),
	(fn()=> Atlantis\UI\PromoVideo::FromSurfaceWith($Surface, [
		'VideoURL' => '/themes/default/gfx/splishsplash.mp4',
		'Overlay'  => 'grad-focus-dark',
		'Title'   => 'Video BG',
		'Subline' => 'With Typed Text',
		'Typeify' => TRUE
	]))
];

?>

<div class="container pt-6 pb-6">

	<div class="mb-6">
		<?php echo $Intro() ?>
	</div>

	<div class="row">
		<?php foreach($Sections as $Section): ?>
		<div class="col-12 mb-4">
			<div class="jumbotron rounded"><?php echo $Section() ?></div>
		</div>
		<?php endforeach; ?>
	</div>
</div>
