<?php

use Nether\Atlantis\UI;
use Nether\Common;

$Surface->Area('sensei/pages/ui/__intro', [
	'Title'   => 'Promo Video Heading',
	'Section' => 'Atlantis\\UI\\PromoVideo',
	'Content' => <<< LOL
		Mainly designed for use as page intros as an artsy way to add motion to the background of an element.
	LOL
]);

$Surface->Area('sensei/pages/ui/__demo-via-area', [
	'Areas' => [
		'With Static Text'
		=> 'sensei/pages/ui/promo-video/static',

		'With Typeified Text'
		=> 'sensei/pages/ui/promo-video/typeify'
	]
]);
