<?php

$Menu = Nether\Atlantis\UI\SiteMenu::FromSurfaceWith($Surface, [
	'DataKey' => 'examplemenu',
	'UUID'    => 'ExampleMenu1',
	'Title'   => 'Example Menu',
	'Pages'   => [
		Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
			'UUID'    => 'ExamplePage1',
			'Title'   => 'Example Page 1',
			'Content' => <<< EOL
				<button class="btn btn-primary" data-examplemenu="ExamplePage1/ExamplePage2">
					Open ExampleMenu2
				</button>
			EOL
		]),
		Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
			'UUID'    => 'ExamplePage2',
			'Title'   => 'Example Page 2',
			'Content' => <<< EOL
				<button class="btn btn-primary" data-examplemenu="ExamplePage1/ExamplePage2/ExamplePage3">
					Open ExampleMenu3
				</button>
			EOL
		]),
		Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
			'UUID'    => 'ExamplePage3',
			'Title'   => 'Example Page 3',
			'Content' => <<< EOL
				<button class="btn btn-primary" data-examplemenu="ExamplePage1/ExamplePage2/ExamplePage3/ExamplePage4">
					Open ExampleMenu4
				</button>
			EOL
		]),
		Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
			'UUID'    => 'ExamplePage4',
			'Title'   => 'Example Page 4',
			'Content' => <<< EOL
				Example Page 4
			EOL
		])
	]
]);

?>

<div class="container pt-6 pb-6">

	<div class="mb-6">
		Offcanvas Site Menu
	</div>

	<div class="row">
		<div class="col">
			<button class="btn btn-primary" data-examplemenu="ExamplePage1">
				Open ExampleMenu1
			</button>
		</div>
	</div>

<?php echo $Menu ?>

</div>