<?php

$Intro = (fn()=> Nether\Atlantis\UI\Article::FromSurfaceWith($Surface, [
	'Title'   => 'Site Menu',
	'Section' => 'Atlantis\\UI\\SiteMenu',
	'Content' => 'Provides a stack of off-screen sidebars in the style of mobile app menus using the offcanvas element in Bootstrap.'
]));

$Menu = Nether\Atlantis\UI\SiteMenu::FromSurfaceWith($Surface, [
	'DataKey' => 'examplemenu',
	'UUID'    => 'ExampleMenu1',
	'Title'   => 'Example Menu',
	'Pages'   => [
		Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
			'UUID'    => 'ExamplePage1',
			'Title'   => 'Example Page 1',
			'Content' => <<< EOL
				<button class="btn btn-primary" data-examplemenu="ExamplePage1/ExamplePage2">
					Go Deeper <i class="mdi mdi-chevron-right"></i>
				</button>
			EOL
		]),
		Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
			'UUID'    => 'ExamplePage2',
			'Title'   => 'Example Page 2',
			'Content' => <<< EOL
				<button class="btn btn-primary" data-examplemenu="ExamplePage1/ExamplePage2/ExamplePage3">
					Go Deeper <i class="mdi mdi-chevron-right"></i>
				</button>
			EOL
		]),
		Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
			'UUID'    => 'ExamplePage3',
			'Title'   => 'Example Page 3',
			'Content' => <<< EOL
				<button class="btn btn-primary" data-examplemenu="ExamplePage1/ExamplePage2/ExamplePage3/ExamplePage4">
					Go Deeper <i class="mdi mdi-chevron-right"></i>
				</button>
			EOL
		]),
		Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
			'UUID'    => 'ExamplePage4',
			'Title'   => 'Example Page 4',
			'Content' => <<< EOL
				So Deep.
			EOL
		])
	]
]);

?>

<div class="container pt-6 pb-6">

	<div class="mb-6">
		<?php echo $Intro() ?>
	</div>

	<div class="row">
		<div class="col-12 mb-2">
			<button class="btn btn-primary" data-examplemenu="ExamplePage1">
				Open ExampleMenu1
			</button>
		</div>
		<div class="col-12 mb-2">
			<button class="btn btn-primary" data-examplemenu="ExamplePage1/ExamplePage2/ExamplePage3/ExamplePage4">
				Open ExampleMenu1 to Level 4
			</button>
		</div>
		<div class="col-12 mb-2">
			<button class="btn btn-primary" data-examplemenu="ExamplePage4">
				Open only Level 4 from ExampleMenu1
			</button>
		</div>
	</div>

<?php echo $Menu ?>

</div>