<?php

use Nether\Atlantis\UI;
use Nether\Common;

$Surface->Area('sensei/pages/ui/__intro', [
	'Title'   => 'Item Slider Widget',
	'Section' => 'Atlantis\\UI\\Slider',
	'Content' => <<< LOL
		Does the sideways media browser style finger flicking slider things.
	LOL
]);

$Surface->Area('sensei/pages/ui/__demo-via-area', [
	'Areas' => [
		'Manual Setup'
		=> 'sensei/pages/ui/slider/basic',

		'With Typeified Text'
		=> 'sensei/pages/ui/slider/from-resultset1'
	]
]);
