<?php

/**
 * @var Nether\Atlantis\Struct\LoginReset $Reset
 */

?>

<div style="margin-bottom:32px;">
	There has been a request to reset the login info for an account with this email address.
	Click this link or copy the URL into your browser to finish resetting your login.
	If you did not request this reset then you may ignore this email.
</div>

<div style="margin-bottom:32px">
	<a href="<?php echo htmlentities($Reset->GetURL()) ?>"><?php echo htmlentities($Reset->GetURL()) ?></a>
</div>

