<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * ...
 */

($Router->Response)
->SetContentType('text/xml');

$FeedURL = $Router->Request->GetURL();

$HomeTitle = $Surface->Get('Page.Title');
$HomeURL = $Surface->Get('Page.HomeURL');
$HomeDesc = $App->Config->Get(Atlantis\Key::ConfProjectDescShort);

?>
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
	<channel>
		<atom:link href="<?php $Util->Print($FeedURL) ?>" rel="self" type="application/rss+xml" />
		<title><?php $Util->Print($HomeTitle) ?></title>
		<link><?php $Util->Print($HomeURL) ?></link>
		<description><?php $Util->Print($HomeDesc) ?></description>

<?php echo $Output ?>

	</channel>
</rss>
