<?php

/**
 * @var Nether\Atlantis\Struct\TemplateHelper $Util
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Atlantis\UI\Gallery $Element
 * @var Nether\Atlantis\UI\GalleryItem $Item
 */

$Admin = $Route->IsUserAdmin();
$ImageURL = $Item->Item->GetPublicURL();
$ThumbnailURL = $Item->Item->GetPublicURL();

$Classes = 'ratiobox widescreen wallpapered contained rounded bg-dark cursor-pointer GalleryItem';

?>

<div class="col-6 col-md-3 mb-4">
	<div class="<?php $Util->Print($Classes) ?>" style="background-image:url(<?php $Util->Print($ThumbnailURL) ?>);" data-url-lg="<?php $Util->Print($ImageURL) ?>">
		<div class="position-absolute position-bottom position-right p-1">

			<?php if($Admin): ?>
			<button class="btn btn-danger font-size-large p-0 pl-1 pr-1" <?php echo $Item->Item->GetDataAttrForHTML([ 'photolib-cmd'=> 'delete' ]) ?>>
				<i class="mdi mdi-trash-can mr-0"></i>
			</button>
			<?php endif; ?>
		</div>
	</div>
</div>
