<?php

/**
 * @var Nether\Atlantis\Struct\TemplateHelper $Util
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Atlantis\UI\Gallery $Element
 *
 * @var bool $Brick
 */

$Brick ??= TRUE;

if($Brick) {
	$Surface
	->AddScriptURL('/themes/default/lib/js/masonry.pkgd.min.js')
	->AddScriptURL('/themes/default/lib/js/imagesloaded.min.js')
	->AddScriptReadyFrag('elements/gallery/frags/galleryify.js')
	->AddScriptReadyFrag('elements/gallery/frags/brickify.js');
}

?>

<div id="<?php $Util->Print($Element->GetID()) ?>" class="atl-ui-gallery">
	<div class="row">
		<?php $Element->PrintItems() ?>
	</div>
</div>
