<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Common\Datastore $Verbs
 * @var Nether\Common\Datastore $Endpoints
 */

$Trail = [ 'API Tool' => '/ops/api' ];

$Breadcrumbs = (fn()
	=> $Surface->GetArea('admin/breadcrumbs', [ 'Trail' => $Trail ])
);

$CurrentVerb ??= 'GET';
$CurrentEndpoint ??= '/api/user/entity';

//Nether\Common\Dump::Var($Endpoints, TRUE);

?>

<div class="container">

	<?php echo $Breadcrumbs(); ?>

	<form id="ToolSend">
	<div class="glassbox rounded p-3" style="position: sticky; top: 0.5rem;">
		<div class="row align-items-center g-2">

			<!-- VERB -->
			<div class="col-12" data-tool-hidable>
				<div class="form-floating">
					<select name="Verb" class="form-control form-select ff-mono">
						<?php foreach($Verbs as $Verb): ?>
						<option value="<?php $Printer(strtoupper($Verb)) ?>" <?php $Printer($Selected($CurrentVerb === $Verb)) ?>><?php $Printer($Verb) ?></option>
						<?php endforeach; unset($Verb); ?>
					</select>
					<label>Verb</label>
				</div>
			</div>

			<!-- ENDPOINT -->
			<div class="col-12 pos-relative" data-tool-hidable>
				<div class="input-group">
					<div class="form-floating">
						<input type="text" name="Endpoint" class="form-control ff-mono bc-grey-dk" list="EndpointList" placeholder="..." value="<?php $Util->Print($CurrentEndpoint) ?>" />
						<label>Endpoint</label>
						<datalist id="EndpointList">
							<?php foreach($Endpoints as $Endpoint): ?>
							<option value="<?php $Printer($Endpoint) ?>"><?php $Printer($Endpoint) ?></option>
							<?php endforeach; unset($Endpoint); ?>
						</datalist>
					</div>
				</div>
			</div>

			<div class="col-12" data-tool-hidable><hr class="border-0 my-2" /></div>

			<!-- DATASET -->
			<div class="col-12" data-tool-hidable>

				<div class="row align-items-center g-4 mb-2">
					<div class="col-auto">
						<span class="fs-large fw-bold tt-upper ff-mono o-50">Dataset</span>
					</div>
					<div class="col">
						<hr />
					</div>
					<div class="col-auto">
						<button type="button" class="btn btn-sm btn-outline-light fs-large py-1 rounded-less BtnDataAppend">
							<i class="mdi mdi-plus-circle"></i>
							Key/Pair
						</button>
					</div>
				</div>

				<div id="DatasetList">
					<div class="jumbotron rounded p-2 text-center ff-mono o-50">
						No Data Items
					</div>
				</div>
			</div>

			<div class="col-12" data-tool-hidable><hr class="bc-grey-dk my-2" /></div>

			<div class="col">
				<button type="button" class="btn btn-outline-light btn-lg fs-large d-none" data-tool-expand>
					<i class="mdi mdi-ghost mr-0"></i>
					Show
				</button>
				<button type="button" class="btn btn-outline-light btn-lg fs-large" data-tool-collapse>
					<i class="mdi mdi-ghost-outline"></i>
					Hide
				</button>
			</div>

			<div class="col-auto">
				<button type="submit" class="btn btn-light btn-lg fs-large">
					Send
				</button>
			</div>

		</div>
	</div>

	<div class="row">
		<div class="col-12 py-4">
			<pre id="ToolSendOutput" class="jumbotron rounded p-2"></pre>
		</div>
	</div>
	</form>

</div>

<script type="module">
import Tool from '/share/atlantis/admin/apitool.js?v=<?php $Printer($CacheBuster) ?>';

jQuery(function() {
	new Tool;
	return;
});
</script>
