<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * ...
 */

$ShowTags ??= TRUE;

//$TagFilter = fn(Atlantis\Tag\Entity $T)=> $T->ID !== $TagPrimary->ID;

?>

<?php foreach($Profiles as $PK=> $Profile): ?>
<div class="row align-items-center">
	<div class="col">
		<div class="fw-bold fs-large"><a href="<?php $Util->Print($App->RewriteURL($Profile->GetPageURL($App))) ?>"><?php $Util->Print($Profile->Title) ?></a></div>
	</div>
	<div class="col-auto">
		<a class="btn btn-primary fs-larger" href="<?php $Util->Print($App->RewriteURL($Profile->GetPageURL($App))) ?>">View Document</a>
	</div>
</div>
<?php if(!$Profiles->IsLastKey($PK)): ?>
<hr class="mt-4 mb-5" />
<?php endif; ?>
<?php endforeach; ?>
