<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * ...
 */

?>

<?php foreach($Profiles as $Profile): ?>
<div class="row tight align-items-center">
	<div class="col">
		<a href="<?php $Util->Print($Profile->GetPageURL()) ?>"><?php $Util->Print($Profile->Title) ?></a>
	</div>
	<div class="col-auto">
		<a class="btn btn-block btn-dark" href="<?php $Util->Print($Profile->GetPageURL()) ?>">Visit</a>
	</div>
	<div class="col-auto">
		<button class="btn btn-block btn-danger" <?php echo $Profile->GetDataAttrForHTML([ 'profile-cmd'=> 'delete' ]) ?> href="#"><i class="mdi mdi-delete mr-0"></i></btn>
	</div>
</div>
<hr />
<?php endforeach; ?>
