<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore $Tags
 * @var Common\Datastore $Pre
 * @var ?string $URL
 */

$Pre ??= NULL;
$URL ??= '/tag/:Alias:';

$RewriteURL = function(Atlantis\Tag\Entity $T, string $Template): string {

	if($T->Type === 'tag')
	return str_replace(':Alias:', $T->Alias, $Template);

	return $T->GetPageURL();
};

$TagClasses = function(Atlantis\Tag\Entity $T): string {

	if($T->Type === 'site')
	return 'btn-dark opacity-10';

	return 'btn-outline-dark';
};

?>

<div class="opacity-100">

	<?php if($Pre) foreach($Pre as $Tag): /** @var Atlantis\Tag\Entity $Tag */ ?>
	<a href="<?php $Util->Print($Tag->Alias) ?>" class="btn <?php $Util->Print($Tag->Type) ?> <?php $Util->Print($TagClasses($Tag)) ?> p-1 pl-2 pr-2 mb-2"><?php $Util->Print($Tag->Name) ?></a>
	<?php endforeach; ?>

	<?php if($Tags) foreach($Tags as $Tag): /** @var Atlantis\Tag\Entity $Tag */ ?>
	<a href="<?php $Util->Print($RewriteURL($Tag, $URL)) ?>" class="btn <?php $Util->Print($TagClasses($Tag)) ?> p-1 pl-2 pr-2 mb-2"><?php $Util->Print($Tag->Name) ?></a>
	<?php endforeach; ?>

</div>
