<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Atlantis\Struct\TemplateHelper $Util
 */

$Theme = match(TRUE) {
	isset($_COOKIE['theme']) => $_COOKIE['theme'],
	default => 'dark'
};

?>

<div class="form-check form-switch">
	<label class="form-check-label text-muted text-uppercase font-size-small cursor-pointer">
		<input type="checkbox" role="switch" class="form-check-input nui-theme-switch" data-nui-theme-switch="dark/light" <?php echo $Util->GetCheckedHTML($Theme === 'light') ?> />
		Dark / Light
	</label>
</div>
