<?php

use Nether\Common;

?>

<!-- VIDEOS -->
<div class="mb-8">
	<h2 class="text-uppercase">Videos (<?php $Util->Print($Videos->Count()) ?>)</h2>
	<hr class="mt-2 mb-4" />

	<div class="row">
		<?php foreach($Videos as $Video): /** @var Atlantis\Media\VideoThirdParty $Video */ ?>
		<div class="col-12 col-md-3">
			<div class="ratiobox widescreen wallpapered contained rounded bg-dark" style="background-image:url(<?php $Util->Print($Video->GetCoverImageURL()) ?>);">
				<a class="position-absolutely" href="<?php $Util->Print($Video->URL) ?>" target="_blank"></a>
				<div class="position-absolute position-bottom position-right p-1">
					<?php if($Route->IsUserAdmin()): ?>
					<button class="btn btn-light CmdVideoEdit" data-video-id="<?php $Util->Print($Video->ID) ?>"><i class="mdi mdi-pencil mr-0"></i></button>
					<button class="btn btn-danger CmdVideoDelete" data-video-id="<?php $Util->Print($Video->ID) ?>"><i class="mdi mdi-trash-can mr-0"></i></button>
					<?php endif; ?>
				</div>
			</div>
		</div>
		<div class="col-12 col-md mb-4">
			<h3><a href="<?php $Util->Print($Video->URL) ?>" target="_blank"><?php $Util->Print($Video->Title) ?></a></h3>
			<div>
				<b>Date Posted:</b>
				<?php $Util->Print($Video->DatePosted->Get(Common\Values::DateFormatFancyDate)) ?>
			</div>
		</div>
		<div class="col-12">
			<hr />
		</div>
		<?php endforeach; unset($Video); ?>

		<?php if(!$Videos->Count()): ?>
		<div class="fst-italic">
			No videos have been added yet.
		</div>
		<?php endif; ?>
	</div>
</div>

<script type="module">
import API from '/share/nui/api/json.js';
import DialogUtil from '/share/nui/util/dialog.js';

jQuery(function() {

	jQuery('.CmdVideoAdd')
	.on('click', function(){

		let parent = this.dataset.parentUuid;

		let diag = new DialogUtil.Window({
			show: true,
			title: 'Add Video By URL',
			labelAccept: 'Add',
			fields: [
				new DialogUtil.Field('hidden', 'ParentUUID', null, parent),
				new DialogUtil.Field('text', 'URL'),
				new DialogUtil.Field('text', 'Title'),
				new DialogUtil.Field('date', 'DatePosted', 'Date')
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('POST', '/api/media/video-tp', data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		return false;
	});

	jQuery('.CmdVideoDelete')
	.on('click', function(){

		let vid = this.dataset.videoId;

		let diag = new DialogUtil.Window({
			title: 'Delete Video',
			labelAccept: 'Yes',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, vid)
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('DELETE', '/api/media/video-tp', data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.fillByRequest(
			'GET', '/api/media/video-tp',
			{ ID: vid },
			true,
			function(d, result) {
				d.body.prepend(`Delete <em>${result.payload.Title}</em>?`);
				return;
			}
		);

		return false;
	});

	jQuery('.CmdVideoEdit')
	.on('click', function(){

		let vid = this.dataset.videoId;

		let diag = new DialogUtil.Window({
			title: 'Edit Video',
			labelAccept: 'Save',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, vid),
				new DialogUtil.Field('text', 'URL', null),
				new DialogUtil.Field('text', 'Title', null),
				new DialogUtil.Field('date', 'DatePosted', 'Date')
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('PATCH', '/api/media/video-tp', data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.fillByRequest(
			'GET', '/api/media/video-tp',
			{ ID: vid },
			true,
			function(d, result) {

				return;
			}
		);

		return false;
	});

	return;
});
</script>
