<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Blog\Blog $Blog
 */

$CacheBust ??= FALSE;
$HeaderImageURL = $Blog->GetHeaderURL();
$IconImageURL = $Blog->GetIconURL();
$BlogURL = $Blog->GetURL();
$Title = $Blog->Title;
$Tagline = $Blog->Tagline;

$ViewMode = 3;

if($CacheBust) {
	$HeaderImageURL .= sprintf('?v=%s', Nether\Common\UUID::V4());
	$IconImageURL .= sprintf('?v=%s', Nether\Common\UUID::V4());
}

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

if($ViewMode === 0)
return;

?>

<header class="atl-blog-header">

	<!-- HEADER BACKGROUND WASHOUT -->
	<div class="atl-blog-header-wash" style="--image: url(<?php $Printer($HeaderImageURL) ?>);">
	</div>

	<!-- HEADER TITLE BAR -->
	<div class="atl-blog-header-titlebar">
		<div class="container fs-smaller">
			<div class="row align-items-center gx-2 gy-0 py-1">
				<div class="col-12 col-md-auto">
					<a class="atl-blog-header-titlebar-title" href="<?php $Util->Print($BlogURL) ?>">
						<?php $Util->Print($Title) ?>
					</a>
				</div>
				<?php if($Tagline): ?>
				<div class="col-12 col-md-auto">
					<a class="atl-blog-header-titlebar-tagline" href="<?php $Util->Print($BlogURL) ?>">
						<span class="d-none d-md-inline">// </span>
						<?php $Util->Print($Tagline) ?>
					</a>
				</div>
				<?php endif; ?>
			</div>
		</div>
	</div>

	<!-- HEADER WALLPAPER -->
	<?php if($ViewMode === 1): ?>
	<section class="atl-blog-header-artwork">
		<div class="container gx-0 gx-sm-4">
			<div class="wallpapered p-4 atl-blog-header-artwork-graphic" style="background-image:url(<?php $Printer($HeaderImageURL) ?>);">
			</div>
		</div>
	</section>
	<?php endif; ?>

	<?php if($ViewMode === 2 || $ViewMode === 3): ?>
	<section class="atl-blog-header-artsplit">
		<div class="container gx-0 gx-sm-4 py-0 py-sm-4">
			<div class="row">
				<div class="col-auto d-none d-sm-block <?php $Util->Print($ViewMode === 3 ? 'order-2' : '') ?>">
					<div class="ratiobox wallpapered square rounded atl-blog-header-artsplit-icon" style="background-image:url(<?php $Util->Print($IconImageURL) ?>);"></div>
				</div>
				<div class="col <?php $Util->Print($ViewMode === 3 ? 'order-1' : '') ?>">
					<div class="wallpapered rounded atl-blog-header-artsplit-graphic" style="background-image:url(<?php $Util->Print($HeaderImageURL) ?>);"></div>
				</div>
			</div>
		</div>
	</section>
	<?php endif; ?>

	<div class="atl-blog-header-breakbar"></div>

</header>
