<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Blog\Blog $Blog
 */

$CacheBust ??= FALSE;
$HeaderImageURL = $Blog->GetHeaderURL();
$IconImageURL = $Blog->GetIconURL();
$Title = $Blog->Title;
$Tagline = $Blog->Tagline;

if($CacheBust) {
	$HeaderImageURL .= sprintf('?v=%s', Nether\Common\UUID::V4());
	$IconImageURL .= sprintf('?v=%s', Nether\Common\UUID::V4());
}

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

// these should be set in then pulled from the blog settings.

$CSSVars = new Common\Datastore([
	'--atl-blog-bg1' => 'var(--theme-orange)',
	'--atl-blog-fg1' => 'var(--theme-black)'
]);

$CSSVars->RemapKeyValue(fn(string $K, string $V)=> "{$K}: {$V};")

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

?>

<div class="BlogHeader" style="<?php $Util->Print($CSSVars->Join(' ')) ?>">
	<aside style="background-image:url(<?php $Printer($HeaderImageURL) ?>);">
	</aside>

	<!-- HEADER TITLE BAR -->
	<header>
		<div class="container fs-smaller">
			<div class="row align-items-center gx-2 gy-1 py-1">
				<div class="col-12 col-md-auto">
					<span class="fw-bold">
						<?php $Util->Print($Title) ?>
					</span>
				</div>
				<?php if($Tagline): ?>
				<div class="col-12 col-md-auto">
					<span class="o-50">
						<span class="d-none d-md-inline">// </span>
						<?php $Util->Print($Tagline) ?>
					</span>
				</div>
				<?php endif; ?>
			</div>
		</div>
	</header>

	<!-- HEADER WALLPAPER -->
	<section class="container gx-0 gx-sm-4">
		<div class="wallpapered bg-black p-4" style="background-image:url(<?php $Printer($HeaderImageURL) ?>);">
		</div>
	</section>
</div>
