<?php

use Nether\Blog;

/**
  * @var Blog\Blog $Blog
  * @var ?bool $CacheBust
  */

$CacheBust ??= FALSE;
$HeaderImageURL = $Blog->GetHeaderURL();
$IconImageURL = $Blog->GetIconURL();

if($CacheBust) {
	$HeaderImageURL .= sprintf('?v=%s', Nether\Common\UUID::V4());
	$IconImageURL .= sprintf('?v=%s', Nether\Common\UUID::V4());
}

?>

<div class="BlogHeader">
	<div class="BlogHeaderWash" style="background-image:url(<?php $Printer($HeaderImageURL) ?>);"></div> 
	<div class="BlogHeaderTitleBar" style="box-shadow: 0px 0px 10px #000;">
		<div class="container fs-smaller">
			<div class="row align-items-center gx-2 gy-1 py-1">
				<div class="col-12 col-md-auto">
					<span class="tc-black fw-bold">
						<?php $Util->Print($Blog->Title) ?>
					</span>
				</div>
				<?php if($Blog->Tagline): ?>
				<div class="col-12 col-md-auto">
					<span class="tc-black o-50">
						<span class="d-none d-md-inline">// </span>
						<?php $Util->Print($Blog->Tagline) ?>
					</span>
				</div>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<div class="BlogHeaderContainer container">
		<div class="BlogHeaderGraphic wallpapered bg-black p-4" style="background-image:url(<?php $Printer($HeaderImageURL) ?>);">
			<div class="d-none row align-items-center">
				<div class="col-4 col-sm-3 col-md-2">
					<div class="ratiobox square rounded wallpapered bg-body-secondary" style="background-image:url(<?php $Printer($IconImageURL) ?>);">
						<a href="<?php $Printer($Blog->GetURL()) ?>" class="position-absolutely text-decoration-none"></a>
					</div>
				</div>
				<div class="col">
					<h1 class="text-shadow-wofty"><a href="<?php $Printer($Blog->GetURL()) ?>"><?php $Printer($Blog->Title) ?></a></h1>
					<?php if($Blog->Tagline): ?>
					<div class="fw-bold text-shadow-wofty"><?php $Printer($Blog->Tagline) ?></div>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
</div>
