<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore $Posts
 */

$GetPreTags = function(Blog\Post $Post): Common\Datastore {

	$Output = new Common\Datastore;

	if(!$Post->Enabled)
	$Output->Push(Atlantis\Tag\Entity::New(
		Name: 'DRAFT',
		Type: 'btn-primary'
	));

	return $Output;
};

?>

<?php foreach($Posts as $Post): /** @var Blog\Post $Post */ ?>
<div>
	<div class="row align-items-start <?php $Util->Print($Post->Enabled ? '' : 'opacity-60') ?>">
		<div class="col-12 col-md-2 mb-4 mb-md-0">
			<div class="ratiobox widescreen rounded wallpapered" style="background-image:url(<?php $Util->Print($Post->GetCoverImageURL()) ?>);">
				<a class="position-absolutely" href="<?php $Printer($Post->GetURL()) ?>"></a>
			</div>
		</div>
		<div class="col-12 col-md mb-0 mb-md-0">
			<div class="fw-bold text-uppercase font-size-small">
				<?php $Printer($Post->DateCreated->Get(Common\Values::DateFormatFancyDate)) ?>
			</div>
			<div class="fw-bold font-size-large mb-1">
				<a href="<?php $Printer($Post->GetURL()) ?>" class="border-0"><?php $Printer($Post->Title) ?></a>
			</div>

			<div class="mb-2"><?php $Surface->Area('tag/buttons', [ 'Pre'=> $GetPreTags($Post), 'Tags'=> $Post->GetTags() ]) ?></div>

			<div class="EditorContent mb-2">
				<?php echo $Post->GetExcerpt() ?>
			</div>

			<div>
				<a href="<?php $Util->Print($Post->GetURL()) ?>" class="btn btn-primary">Read More...</a>
			</div>
		</div>
	</div>
</div>
<hr class="mt-5 mb-5" />
<?php endforeach; ?>
