<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore $Posts
 */

$GetPreTags = function(Blog\Post $Post): Common\Datastore {

	$Output = new Common\Datastore;

	if(!$Post->Enabled)
	$Output->Push(Atlantis\Tag\Entity::New(
		Name: 'DRAFT',
		Type: 'btn-primary'
	));

	return $Output;
};

?>

<?php foreach($Posts as $PK=> $Post): /** @var Blog\Post $Post */ ?>
<div>
	<div class="row align-items-start <?php $Util->Print($Post->Enabled ? '' : 'opacity-60') ?>">
		<div class="col-12 col-md-2 mb-4 mb-md-0">
			<div class="ratiobox widescreen rounded wallpapered" style="background-image:url(<?php $Util->Print($Post->GetCoverImageURL()) ?>);">
				<a class="position-absolutely" href="<?php $Util->Print($App->RewriteURL($Post->GetURL(), $Post->GetTags())) ?>"></a>
			</div>
		</div>
		<div class="col-12 col-md mb-0 mb-md-0">
			<div class="mb-2">
				<?php match($Post->Editor) {
					'link'
					=> $Surface->Area('blog/views/link', [ 'Post'=> $Post, 'Full'=> FALSE, 'Excerpt'=> FALSE ]),

					default
					=> $Surface->Area('blog/views/html', [ 'Post'=> $Post, 'Full'=> FALSE, 'Excerpt'=> FALSE ])
				}; ?>
			</div>

			<div>
				<a href="<?php $Util->Print($App->RewriteURL($Post->GetURL(), $Post->GetTags())) ?>" class="btn btn-primary">Read More...</a>
			</div>
		</div>
	</div>
</div>
<hr class="mt-5 mb-5" />
<?php endforeach; ?>
