<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore $Posts
 */

$BlogUser ??= NULL;

$GetPreTags = function(Blog\Post $Post): Common\Datastore {

	$Output = new Common\Datastore;

	if(!$Post->Enabled)
	$Output->Push(Atlantis\Tag\Entity::New(
		Name: 'DRAFT',
		Type: 'btn-primary'
	));

	return $Output;
};

$ShowBlogIcon ??= $Surface->Get('Blog.PostList.ShowBlogIcon') ?? FALSE;
$ShowDefaultImage ??= $Surface->Get('Blog.PostList.ShowDefaultImage') ?? TRUE;


?>

<?php foreach($Posts as $Post): /** @var Blog\Post $Post */ ?>
<div class="atl-blog-post-row">
	<div class="row <?php $Util->Print($Post->Enabled ? '' : 'opacity-60') ?>">
		<?php if($Post->HasCoverImage() || $ShowDefaultImage): ?>
		<div class="col-12 col-md-4 col-lg-3 mb-4">
			<div class="ratiobox widescreen rounded wallpapered bg-dark" style="background-image:url(<?php $Util->Print($Post->GetCoverImageURL()) ?>);">

				<?php if(!$Post->HasCoverImage()): ?>
				<div class="pos-absolutely grad-focus-normal"></div>
				<?php endif; ?>

				<?php if($ShowBlogIcon): ?>
				<div class="pos-absolute pos-top pos-left" style="width:25%;padding:0.25em;">
					<div class="ratiobox square rounded wallpapered bg-dark" style="<?php $Util->Print($Post->Blog->GetIconStyleBG()) ?>">
						<div class="pos-absolutely grad-focus-normal"></div>
					</div>
				</div>
				<?php endif; ?>

				<a class="pos-absolutely" href="<?php $Printer($Post->GetURL()) ?>"></a>

			</div>
		</div>
		<?php endif; ?>

		<div class="col-12 col-md mb-4">

			<?php match($Post->Editor) {
				'link'
				=> $Surface->Area('blog/views/link', [ 'BlogUser'=> $BlogUser, 'Post'=> $Post, 'Full'=> FALSE ]),

				default
				=> $Surface->Area('blog/views/html', [ 'BlogUser'=> $BlogUser, 'Post'=> $Post, 'Full'=> FALSE ])
			}; ?>

			<div class="pt-4">
				<a href="<?php $Util->Print($Post->GetURL()) ?>" class="btn btn-primary">Read More...</a>
			</div>
		</div>
	</div>
</div>
<hr class="mt-4 mb-6" />
<?php endforeach; ?>