<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore $Posts
 */

$GetPreTags = function(Blog\Post $Post): Common\Datastore {

	$Output = new Common\Datastore;

	if(!$Post->Enabled)
	$Output->Push(Atlantis\Tag\Entity::New(
		Name: 'DRAFT',
		Type: 'btn-primary'
	));

	return $Output;
};

?>

<?php foreach($Posts as $Post): /** @var Blog\Post $Post */ ?>
<div>
	<div class="row <?php $Util->Print($Post->Enabled ? '' : 'opacity-60') ?>">
		<div class="col-12 mb-4">
			<div class="ratiobox widescreen rounded wallpapered" style="background-image:url(<?php $Util->Print($Post->GetCoverImageURL()) ?>);">
				<a class="position-absolutely" href="<?php $Printer($Post->GetURL()) ?>"></a>
			</div>
		</div>
		<div class="col-12 mb-4">

			<?php match($Post->Editor) {
				'link'
				=> $Surface->Area('blog/views/link', [ 'Post'=> $Post, 'Full'=> FALSE ]),

				default
				=> $Surface->Area('blog/views/html', [ 'Post'=> $Post, 'Full'=> FALSE ])
			}; ?>

			<div class="pt-4">
				<a href="<?php $Util->Print($Post->GetURL()) ?>" class="btn btn-primary">Read More...</a>
			</div>
		</div>
	</div>
</div>
<hr class="mt-6 mb-6" />
<?php endforeach; ?>