<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> project.atl <command> <args>

<span style="font-weight: bold; color: #9eb2d7;">•</span> <span style="font-weight: bold; color: #9eb2d7;">help <command>:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9eb2d7;">•</span> <span style="font-weight: bold; color: #9eb2d7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7b9bd5;">init</span>
<span style="color: #676767;">Begin setting up the project from scratch.</span>

<span style="font-weight: bold; color: #7b9bd5;">setup</span> --fix
<span style="color: #676767;">Reconfigure anything that can be reconfigured easily.</span>

<span style="font-weight: bold; color: #7b9bd5;">db</span> --info=… --json=… --set=… --del=… --host=… --db=… --user=… --pass=…
<span style="color: #676767;">Manage the project database connection info.</span>

<span style="font-weight: bold; color: #7b9bd5;">dirs</span> --add --del --path=…
<span style="color: #676767;">Lists and Edit the directories managed by the Project JSON.</span>

<span style="font-weight: bold; color: #7b9bd5;">symlinks</span> --add --del --path=… --source=…
<span style="color: #676767;">Lists and Edit the Symlinks managed by the Project JSON.</span>

