<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> project.atl symlinks <command> <args>

<span style="font-weight: bold; color: #7b9bd5;">symlinks</span> --add --del --path=… --source=…
<span style="color: #676767;">Lists and Edit the Symlinks managed by the Project JSON.</span>

	--add
	<span style="color: #676767;">Add the specified --path.</span>

	--del
	<span style="color: #676767;">Delete the specified --path.</span>

	--path=…
	<span style="color: #676767;">The path to manage.</span>

	--source=…
	<span style="color: #676767;">The source to point at.</span>

