<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> project.atl dirs <command> <args>

<span style="font-weight: bold; color: #7b9bd5;">dirs</span> --add --del --path=…
<span style="color: #676767;">Lists and Edit the directories managed by the Project JSON.</span>

	--add
	<span style="color: #676767;">Add the specified --path.</span>

	--del
	<span style="color: #676767;">Delete the specified --path.</span>

	--path=…
	<span style="color: #676767;">The path to manage.</span>

