<?php

/**
 * @var Nether\Atlantis\UI\Slider $Element
 * @var Nether\Atlantis\UI\SliderItem $Item
 * @var Nether\Atlantis\Tag\Entity $Tag
 */

$Title ??= $Item->GetItemTitle();
$URL ??= $Item->GetItemURL();
$ImageURL ??= $Item->GetItemImageURL();

?>

<div class="swiper-slide">
	<div class="ratiobox widescreen wallpapered rounded" style="background-image:url(<?php $Util->Print($ImageURL) ?>);">
		<div class="position-absolutely grad-bottom-normal"></div>
		<div class="position-absolute position-bottom w-100 text-align-center">
			<span class="fw-bold"><?php $Util->Print($Title) ?></span>
		</div>
		<a href="<?php $Util->Print($URL) ?>" class="position-absolutely"></a>
	</div>
</div>
