<?php

/**
 * @var Nether\Atlantis\UI\Slider $Element
 * @var Nether\Atlantis\UI\SliderItem $Item
 * @var Nether\Atlantis\Profile\Entity $Profile
 */

$Profile = $Item->GetItem();

?>

<div class="swiper-slide">
	<div class="ratiobox widescreen wallpapered rounded" style="background-image:url(<?php $Util->Print($Profile->GetCoverImageURL()) ?>);">
		<div class="position-absolutely grad-bottom-normal"></div>
		<div class="position-absolute position-bottom w-100 text-align-center">
			<span class="fw-bold text-uppercase"><?php $Util->Print($Profile->Title) ?></span>
		</div>
		<a href="<?php $Util->Print($Profile->GetPageURL()) ?>" class="position-absolutely"></a>
	</div>
</div>
