<?php

/**
 * @var Nether\Atlantis\Struct\TemplateHelper $Util
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Atlantis\UI\Slider $Element
 */

// @todo 2023-09-12 if using realboot css class then do not include the init
// code afterwards as that will be handled by the mass booter.

$CacheBust = $Util->GetCacheBuster();
$ElementID = $Element->GetID();
$ScriptURL = "/share/nui/modules/itemslider/itemslider.js?v={$CacheBust}";
$ScriptSelector = $Element->GetSelectorID();

$Surface->AddScriptReadyFrag('elements/slider/ready');

?>

<div class="<?php $Util->Print($Element->GetClassesForHTML('atl-ui-slider o-0')) ?>" data-slide-count="4">
	<div class="swiper-supercontainer">
		<div id="<?php $Util->Print($ElementID) ?>" class="swiper swiper-coldboot">
			<div class="swiper-wrapper">
				<?php $Element->PrintItems() ?>
			</div>
		</div>
	</div>
</div>

<script type="module">
import ItemSlide from "<?php echo $ScriptURL ?>";

jQuery(document)
.ready(function(){


	return;
});
</script>
