<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Surface->Area('sensei/docs/__header', [
	'Title' => 'Pathbar',
	'Trail' => [ Atlantis\Struct\Item::New(Title: 'UI', URL: '/docs/ui') ]
]);

$Surface->Area('sensei/docs/__example-via-area', [
	'Areas' => [
		'Basic'
		=> 'sensei/docs/ui/pathbar/example-basic',

		'More Fancy'
		=> 'sensei/docs/ui/pathbar/example-more',

		'Less Fancy'
		=> 'sensei/docs/ui/pathbar/example-less'
	]
]);
