<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Surface->Set([
	'Page.Section.Title' => 'UI Elements',
	'Page.Title'         => 'Pathbar',
	'Page.Info'          => NULL
]);

$Surface->Area('sensei/docs/__example-via-area', [
	'Areas' => [
		'Basic'
		=> 'sensei/docs/ui/pathbar/example-basic',

		'More Fancy'
		=> 'sensei/docs/ui/pathbar/example-more',

		'Less Fancy'
		=> 'sensei/docs/ui/pathbar/example-less'
	]
]);
