<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Atlantis\Struct\TemplateHelper $Util
 * @var Nether\Atlantis\UI\Example $Element
 */

?>

<div class="jumbotron rounded">
	<h1>Element</h1>
	<div class="mb-4">
		This is an example widget. They are defined by a class that extends
		the base Element and a Surface theme file.
	</div>
	<ul class="mb-0">
		<li class="mb-2"><code>class Atlantis\UI\Example extends Surface\Element</code>.</li>
		<li class="mb-2">Override <code>$Area</code> property to set the theme area.</li>
		<li class="mb-0">Print/Echo the object to render it.</li>
	</ul>
</div>
