<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Common;
use Nether\Surface;

/**
 * @var Atlantis\Engine $App
 * @var Routes\Docs $Route
 * @var Surface\Engine $Surface
 */

$Title ??= NULL;
$Section ??= NULL;
$Info ??= NULL;
$Classes ??= NULL;
$Container ??= TRUE;
$Boxify ??= TRUE;
$Trail ??= NULL;

if(!is_array($Trail))
$Trail = [];

################################################################################
################################################################################

$Pathbar = Atlantis\UI\Pathbar::FromSurfaceWith($Surface, [
	'Items' => Common\Datastore::FromStackMerged(
		[ Atlantis\Struct\Item::New(Title: 'Docs', URL: '/docs/', Classes: [ 'tag' ]) ],
		$Trail
	)
]);

$Intro = Atlantis\UI\Article::FromSurfaceWith($Surface, [
	'Title'   => $Title,
	'Section' => $Pathbar,
	'Content' => $Info,
	'Classes' => $Classes ?? []
]);

if($Title)
$Surface->Set('Page.Title', $Title);

?>

<?php if($Container): ?><div class="container pt-6 pb-6">
<?php endif; ?>

	<?php if($Boxify): ?><div class="jumbotron rounded">
	<?php endif; ?>
		<?php echo $Intro ?>
	<?php if($Boxify): ?></div>
	<?php endif; ?>

<?php if($Container): ?></div>
<?php endif; ?>
