<?php

use Nether\Atlantis;
use Nether\Surface;

/**
 * @var Atlantis\Engine $App
 * @var Routes\Docs $Route
 * @var Surface\Engine $Surface
 */

$Title ??= NULL;
$Section ??= NULL;
$Info ??= NULL;
$Classes ??= NULL;
$Container ??= TRUE;
$Boxify ??= TRUE;

$Intro = Atlantis\UI\Article::FromSurfaceWith($Surface, [
	'Title'   => $Title,
	'Section' => $Section,
	'Content' => $Info,
	'Classes' => $Classes ?? []
]);

?>

<?php if($Container): ?><div class="container pt-6 pb-6">
<?php endif; ?>

	<?php if($Boxify): ?><div class="jumbotron rounded">
	<?php endif; ?>
		<?php echo $Intro ?>
	<?php if($Boxify): ?></div>
	<?php endif; ?>

<?php if($Container): ?></div>
<?php endif; ?>
