<?php

use Nether\Atlantis;
use Nether\Common;

/**
 * @var Routes\Docs $Route
 * @var Common\Datastore $Pages
 */

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

$Route->Title = 'Atlantis From Scratch';

($Route->Pathbar->Items)
->Push(Atlantis\Struct\Item::New(
	Title: 'Install & Setup',
	URL: '/docs/cli'
));

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

$Surface->Area('sensei/docs/__header', [
	'Title'   => $Route->Title,
	'Section' => $Route->Pathbar
]);

?>


<div class="atl-cargobay">
	<section>
		<div class="container">

			<dl>
				<dt>Prepare Project Directory</dt>
				<dd><code>$ git clone git@github.com:netherphp/project app</code></dd>
				<dd><code>$ cd app</code></dd>
				<dd><code>$ rm -rf .git</code></dd>
			</dl>

			<dl>
				<dt>Install Framework</dt>
				<dd><code>$ composer require netherphp/atlantis dev-master</code></dd>
			</dl>

		</div>
	</section>
</div>

