<?php

use Nether\Atlantis;
use Nether\Surface;

/**
 * @var Atlantis\Engine $App
 * @var Routes\Docs $Route
 * @var Surface\Engine $Surface
 */

$Surface->Area('sensei/docs/__header', [
	'Title' => 'Framework Overview',
	'Trail' => [ ]
]);

?>

<div class="cargobay">
	<section class="pt-0">
		<div class="container">

			<h3>Install &amp; Setup</h3>
			<hr class="mt-1 mb-3" />

			<ul class="mb-0">
				<li><a href="/docs/afs">Atlantis From Scratch</a></li>
				<li><a href="/docs/surface-theme-extend">Extending Surface Theme</a></li>
			</ul>

		</div>
	</section>
	<section>
		<div class="container">

			<h3>References</h3>
			<hr class="mt-1 mb-3" />

			<ul class="mb-0">
				<li class="mb-4">
					<a href="/docs/cli">CLI Reference</a>
				</li>
				<li class="mb-4">
					<a href="/docs/css">CSS Reference</a>
					<ul class="pt-2">
						<li><a href="/docs/css">Basic Page</a></li>
						<li><a href="/docs/css/dyes">Dyes &amp; Colours</a></li>
						<li><a href="/docs/css/cargobay">Cargobay Containers</a></li>
					</ul>
				</li>
				<li class="mb-4">
					<a href="/docs/ui">Element Reference</a>
				</li>
				<li class="mb-0">
					<a href="/docs/systems">Subsystem Reference</a>
				</li>

			</ul>

		</div>
	</section>
</div>


