<?php

use Nether\Atlantis;
use Nether\Surface;

/**
 * @var Atlantis\Engine $App
 * @var Routes\Docs $Route
 * @var Surface\Engine $Surface
 */

$Surface->Area('sensei/docs/__header', [
	'Title'   => $Route->Title,
	'Section' => $Route->Pathbar
]);

?>

<div class="container pb-6">

	<div class="row">
		<div class="col-6">
			<div class="jumbotron rounded">
				<ul class="mb-0">
					<li><a href="/docs/afs">Install &amp; Setup</a></li>
				</ul>
			</div>
		</div>
		<div class="col-6">
			<div class="jumbotron rounded">
				<div class="fw-bold tt-upper">References</div>
				<ul class="mb-0">
					<li><a href="/docs/cli">Command Line Utilities</a></li>
					<li><a href="/docs/css">CSS (Default Theme)</a></li>
					<li><a href="/docs/ui">Surface UI Elements</a></li>
				</ul>
			</div>
		</div>
	</div>

</div>
