<?php

use Nether\Atlantis;
use Nether\Common;

/**
 * @var Routes\Docs $Route
 * @var Common\Datastore $Pages
 */

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

$Route->Title = 'Surface UI Elements';

($Route->Pathbar->Items)
->Push(Atlantis\Struct\Item::New(
	Title: 'Element UI',
	URL: '/docs/ui'
));

$Pages = Common\Datastore::FromArray([
	'AceEditor'   => '/docs/ui/ace-editor',
	'Article'     => '/docs/ui/article',
	'Pager'       => '/docs/ui/pager',
	'Pathbar'     => '/docs/ui/pathbar',
	'Pillbox'     => '/docs/ui/pillbox',
	'Promo Video' => '/docs/ui/promo-video',
	'Site Menu'   => '/docs/ui/sitemenu',
	'Slider'      => '/docs/ui/slider'
]);

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

$Surface->Area('sensei/docs/__header', [
	'Title'   => $Route->Title,
	'Section' => $Route->Pathbar
]);

?>

<div class="container pb-6">

	<div class="jumbotron rounded hr-hide-last">
		<?php foreach($Pages as $Title => $URL): ?>
		<div class="row align-items-center">
			<div class="col">
				<a href="<?php $Util->Print($URL) ?>"><?php $Util->Print($Title) ?></a>
			</div>
			<div class="col-auto">
				<a class="btn btn-primary" href="<?php $Util->Print($URL) ?>">
					View Docs
					<i class="mdi mdi-chevron-right mr-0"></i>
				</a>
			</div>
		</div>
		<hr class="opacity-20" />
		<?php endforeach; unset($Title, $URL); ?>
	</div>

</div>
