<?php

use Nether\Atlantis;
use Nether\Common;

/**
 * @var Routes\Docs $Route
 * @var Common\Datastore $Pages
 */

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

$Route->Title = 'Surface Element UI';

($Route->Pathbar->Items)
->Push(Atlantis\Struct\Item::New(
	Title: 'Element UI',
	URL: '/docs/ui'
));

$Sections = Common\Datastore::FromArray([
	'Navigation' => Common\Datastore::FromArray([
		'Pathbar' => '/docs/ui/pathbar',
		'Pillbox' => '/docs/ui/pillbox',
		'Site Menu' => '/docs/ui/sitemenu'
	]),

	'Collections' => Common\Datastore::FromArray([
		'Pager' => '/docs/ui/pager',
		'Slider' => '/docs/ui/slider'
	]),

	'Input' => Common\Datastore::FromArray([
		'AceEditor' => '/docs/ui/ace-editor'
	]),

	'Other' => Common\Datastore::FromArray([
		'Article' => '/docs/ui/article',
		'Promo Video' => '/docs/ui/promo-video'
	])
]);

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

$Surface->Area('sensei/docs/__header', [
	'Title'   => $Route->Title,
	'Section' => $Route->Pathbar
]);

?>

<div class="container pb-6">

	<?php foreach($Sections as $Section => $Pages): ?>
	<h2><?php $Util->Print($Section) ?></h2>
	<div class="jumbotron rounded hr-hide-last mb-6">
		<?php foreach($Pages as $Title => $URL): ?>
		<div class="row align-items-center">
			<div class="col">
				<a href="<?php $Util->Print($URL) ?>"><?php $Util->Print($Title) ?></a>
			</div>
			<div class="col-auto">
				<a class="btn btn-primary" href="<?php $Util->Print($URL) ?>">
					View Docs
					<i class="mdi mdi-chevron-right mr-0"></i>
				</a>
			</div>
		</div>
		<hr class="opacity-20" />
		<?php endforeach; unset($Title, $URL); ?>
	</div>
	<?php endforeach; ?>

</div>
