<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> gfx.atl <command> <args>

<span style="font-weight: bold; color: #9eb2d7;">•</span> <span style="font-weight: bold; color: #9eb2d7;">help <command>:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9eb2d7;">•</span> <span style="font-weight: bold; color: #9eb2d7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7b9bd5;">genshare</span> <path/to/image.png> --force --width=… --height=… --scale=… --bg=… --ext=… --suffix=…
<span style="color: #676767;">Generate the social share sized versions of a graphic. Mostly used for site logos.</span>

<span style="font-weight: bold; color: #7b9bd5;">qr</span> <data> --size=… --fresh=…
<span style="color: #676767;">No info provided.</span>

