<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> gfx.atl genshare <command> <args>

<span style="font-weight: bold; color: #7b9bd5;">genshare</span> <path/to/image.png> --force --width=… --height=… --scale=… --bg=… --ext=… --suffix=…
<span style="color: #676767;">Generate the social share sized versions of a graphic. Mostly used for site logos.</span>

	--force
	<span style="color: #676767;">Allows overwriting existing output file.</span>

	--width=…
	<span style="color: #676767;">Width of output. Default: 1920</span>

	--height=…
	<span style="color: #676767;">Height of output. Default: 1080</span>

	--scale=…
	<span style="color: #676767;">Percentage input fills the output. Default: 64 (%)</span>

	--bg=…
	<span style="color: #676767;">Background colour of the output. Should accept any CSS colour name or hex code.</span>

	--ext=…
	<span style="color: #676767;">Output file extension/format. Recommend sticking with "jpg" or "png". Default: jpg</span>

	--suffix=…
	<span style="color: #676767;">Suffix that gets added to the filename. Default: ogimage</span>

