<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> gfx.atl qr <command> <args>

<span style="font-weight: bold; color: #7b9bd5;">qr</span> <data> --size=… --fresh=…
<span style="color: #676767;">No info provided.</span>

	--size=…
	<span style="color: #676767;">Size of the QR in pixels. (Default: 1200)</span>

	--fresh=…
	<span style="color: #676767;">Overwrite with fresh copy if already exists.</span>

