<?php

use Nether\Blog;

/**
  * @var Blog\Blog $Blog
  */

?>

<div class="bg-alt1">
	<div class="container">
		<div class="bg-alt2 p-4">
			<div class="row align-items-center">
				<div class="col-2">
					<div class="ratiobox square bg-alt0">
						<a href="<?php $Printer($Blog->GetURL()) ?>" class="position-absolutely"></a>
					</div>
				</div>
				<div class="col">
					<h1><a href="<?php $Printer($Blog->GetURL()) ?>"><?php $Printer($Blog->Title) ?></a></h1>
					<?php if($Blog->Tagline): ?>
					<div><?php $Printer($Blog->Tagline) ?></div>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
</div>
