<?php

use Nether\Blog;

/**
  * @var Blog\Blog $Blog
  */

?>

<div class="BlogHeader">
	<div class="BlogHeaderWash position-absolutely wallpapered" style="background-image:url(<?php $Printer($Blog->GetHeaderURL()) ?>);"></div>
	<div class="BlogHeaderContainer container position-relative">
		<div class="wallpapered bg-black box-shadow-wofty p-4" style="background-image:url(<?php $Printer($Blog->GetHeaderURL()) ?>);">
			<div class="row align-items-center">
				<div class="col-4 col-sm-3 col-md-2">
					<div class="ratiobox square rounded wallpapered bg-body-secondary box-shadow-wofty" style="background-image:url(<?php $Printer($Blog->GetIconURL()) ?>);">
						<a href="<?php $Printer($Blog->GetURL()) ?>" class="position-absolutely text-decoration-none"></a>
					</div>
				</div>
				<div class="col">
					<h1 class="text-shadow-wofty"><a href="<?php $Printer($Blog->GetURL()) ?>"><?php $Printer($Blog->Title) ?></a></h1>
					<?php if($Blog->Tagline): ?>
					<div class="fw-bold text-shadow-wofty"><?php $Printer($Blog->Tagline) ?></div>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
	<div class="position-absolutely box-shadow-inset clickthrough"></div>
</div>
