<?php

// phpcs:disable

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Blog\BlogUser $BlogUser
 * @var Blog\Blog $Blog
 * @var Blog\Post $Post
 */

?>

<hr id="PostInfo" class="d-none"
data-blog-id="<?php $Util->Print($Post->Blog->ID) ?>"
data-blog-uuid="<?php $Util->Print($Post->Blog->UUID) ?>"
data-post-id="<?php $Util->Print($Post->ID) ?>"
data-post-uuid="<?php $Util->Print($Post->UUID) ?>"
/>

<?php $Surface->Area('blog/widgets/blog-header', $__SCOPE) ?>

<div class="container pt-4 ">
	<div class="row align-items-center">

		<!-- POST TITLE -->
		<div class="col">
			<h2 class="text-uppercase">
				<a href="<?php $Util->Print($Blog->GetURL()) ?>"><?php $Util->Print($Blog->Title) ?></a>
			</h2>
		</div>

		<?php if($Route->IsUserAdmin()): ?>
		<div class="col-auto">
			<?php echo Atlantis\UI\Dropdown::FromSurfaceWith($Surface, [
				'Menu'              => $AdminMenu,
				'MenuBtnStyleClass' => 'btn-outline-dark',
				'ItemBtnStyleClass' => 'btn-outline-dark'
			]) ?>
		</div>
		<?php endif; ?>

	</div>
	<hr class="mt-1" />
</div>

<div class="pt-0 pb-4">
	<div class="container">

		<?php if(!$Post->Enabled): ?>
		<div class="alert alert-primary text-center p-2 mb-4">
			This post is in DRAFT mode.
		</div>
		<?php endif; ?>

		<?php
		match($Post->Editor) {
			'link'
			=> $Surface->Area('blog/views/link', $__SCOPE),

			default
			=> $Surface->Area('blog/views/html', $__SCOPE)
		};
		?>

		<?php if(isset($Photos) && $Photos->Total): ?>
		<!-- PHOTOS -->
		<div class="mb-8">
			<h4 class="text-uppercase mb-0">Photos (<?php $Util->Print($Photos->Total) ?>)</h4>
			<hr class="mt-1 mb-3" />

			<?php echo Atlantis\UI\Gallery::FromDataset($Surface, $Photos) ?>
		</div>
		<?php endif; ?>

		<?php if(isset($Videos) && $Videos->Total): ?>
		<!-- VIDEOS -->
		<div class="mb-8">
			<h4 class="text-uppercase mb-0">Videos (<?php $Util->Print($Videos->Total) ?>)</h4>
			<hr class="mt-1 mb-3" />

			<?php echo Atlantis\UI\VideoList::FromDataset($Surface, $Videos, ParentUUID: $Post->UUID) ?>
		</div>
		<?php endif; ?>

	</div>
</div>

<?php if($BlogUser && $BlogUser->CanEdit()): ?>
<script type="module">
import Blog from '/share/atlantis/blog.js';

jQuery(function(){
	let post = Blog.Post.FromElement({ bindify: true });
	return;
});

</script>
<?php endif; ?>
