<?php

// phpcs:disable

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine                $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router                  $Router
 * @var Surface\Engine                 $Surface
 * @var User\EntitySession             $User
 *
 * @var Blog\Routes\BlogHandler        $Route
 * @var Blog\Blog                      $Blog
 * @var Blog\BlogUser                  $BUsr
 * @var Blog\Post                      $Post
 *
 * @deprecated 2024-06-23
 * @var Blog\BlogUser                  $BlogUser (use $BUsr)
 * @var Database\ResultSet             $Profiles (use $Related)
 */

$PostTags = $Post->GetTags();
$PostURL = $App->RewriteURL($Post->GetURL(), $PostTags);
$PostDateFancy = Common\Date::FromDateString($Post->DateCreated)->Get(Common\Values::DateFormatFancyDate);

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

// these should be set in then pulled from the blog settings.

$CSSVars = new Common\Datastore([
	'--atl-blog-bg0'   => 'var(--theme-grey-lt)',    // graphic wash tone
	'--atl-blog-bg1'   => 'var(--theme-orange)',     // titlebar bg colour
	'--atl-blog-bg2'   => 'var(--theme-grey-lt)',    // titlebar bg colour2
	'--atl-blog-fg1'   => 'var(--theme-black)',      // titlebar text colour
	'--atl-blog-fg2'   => 'var(--theme-orange-alt)', // accent text colours
	'--atl-blog-fgh4'  => 'var(--theme-orange-alt)'  // h4 text colour
]);

$CSSVars->RemapKeyValue(fn(string $K, string $V)=> "{$K}: {$V};");

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

?>

<hr id="PostInfo" class="d-none"
	data-blog-id="<?php $Util->Print($Post->Blog->ID) ?>"
	data-blog-uuid="<?php $Util->Print($Post->Blog->UUID) ?>"
	data-post-id="<?php $Util->Print($Post->ID) ?>"
	data-post-uuid="<?php $Util->Print($Post->UUID) ?>"
/>

<div class="atl-page-blog-post" style="<?php $Util->Print($CSSVars->Join(' ')) ?>">

	<!-- BLOG HEADER -->
	<div class="mb-4">
		<?php $Surface->Area('blog/widgets/blog-header', $__SCOPE) ?>
	</div>

	<!-- POST HEADING -->
	<div class="container atl-blog-post-header mb-4">
		<div class="row">

			<!-- POST TITLE -->
			<div class="col">
				<div class="atl-blog-post-dateline">
					<?php $Util->Print($PostDateFancy) ?>
				</div>
				<div class="atl-blog-post-title">
					<h3><a href="<?php $Util->Print($PostURL) ?>" class="border-0"><?php $Util->Print($Post->Title) ?></a></h3>
				</div>
				<?php if($PostTags->Count()): ?>
				<div class="atl-blog-post-tags">
					<?php $Surface->Area('widgets/tag-buttons', [ 'Tags'=> $PostTags ]) ?>
				</div>
				<?php endif; ?>
			</div>

			<?php if($Route->IsUserAdmin()): ?>
			<div class="col-auto">
				<?php echo Atlantis\UI\Dropdown::FromSurfaceWith($Surface, [ 'Menu'=> $AdminMenu ]) ?>
			</div>
			<?php endif; ?>

		</div>
	</div>

	<!-- POST BODY -->
	<div class="container atl-blog-post-container">

		<?php if(!$Post->Enabled): ?>
		<div class="alert alert-info text-center p-2 mb-4">
			This post is in DRAFT mode.
		</div>
		<?php endif; ?>

		<?php if($Post->HasPostImage()): ?>
		<div class="row justify-content-center mb-4">
			<div class="col-12">
				<img class="rounded" src="<?php $Util->Print($Post->GetPostImageURL('lg')) ?>" alt="<?php $Util->Print($Post->Title) ?>" style="width:100%;" />
			</div>
		</div>
		<?php endif; ?>

		<?php
		match($Post->Editor) {
			'editorjs'
			=> $Surface->Area('blog/views/editorjs', $__SCOPE),

			'link'
			=> $Surface->Area('blog/views/link', $__SCOPE),

			default
			=> $Surface->Area('blog/views/html', $__SCOPE)
		};
		?>

		<?php if(isset($Photos) && $Photos->Total): ?>
		<!-- PHOTOS -->
		<div class="mb-8">
			<h4 class="text-uppercase mb-0">Photos (<?php $Util->Print($Photos->Total) ?>)</h4>
			<hr class="mt-1 mb-3" />

			<?php echo Atlantis\UI\Gallery::FromDataset($Surface, $Photos) ?>
		</div>
		<?php endif; ?>

		<?php if(isset($Videos) && $Videos->Total): ?>
		<!-- VIDEOS -->
		<div class="mb-8">
			<h4 class="text-uppercase mb-0">Videos (<?php $Util->Print($Videos->Total) ?>)</h4>
			<hr class="mt-1 mb-3" />

			<?php echo Atlantis\UI\VideoList::FromDataset($Surface, $Videos, ParentUUID: $Post->UUID) ?>
		</div>
		<?php endif; ?>

	</div>

</div>

<?php if($BlogUser && $BlogUser->CanEdit()): ?>
<script type="module">
import Blog from '/share/atlantis/blog.js';

jQuery(function(){
	let post = Blog.Post.FromElement({ bindify: true });
	return;
});

</script>
<?php endif; ?>
