<?php

// phpcs:disable

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Blog\BlogUser $BlogUser
 * @var Blog\Blog $Blog
 * @var Blog\Post $Post
 */

?>

<hr id="PostInfo" class="d-none"
data-blog-id="<?php $Util->Print($Post->Blog->ID) ?>"
data-blog-uuid="<?php $Util->Print($Post->Blog->UUID) ?>"
data-post-id="<?php $Util->Print($Post->ID) ?>"
data-post-uuid="<?php $Util->Print($Post->UUID) ?>"
/>

<?php $Surface->Area('blog/widgets/blog-header', $__SCOPE) ?>

<div class="container pt-4 ">
	<div class="row align-items-center">
		<div class="col">
			<h2 class="text-uppercase"><a href="<?php $Util->Print($Blog->GetURL()) ?>"><?php $Util->Print($Blog->Title) ?></a></h2>
		</div>
		<div class="col-auto">
			<?php if($BlogUser && $BlogUser->CanWrite()): ?>
			<div class="dropdown">
				<button class="btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown">
					<i class="mdi mdi-fw mdi-cog m-0 p-0"></i>
				</button>
				<div class="dropdown-menu dropdown-menu-end">
					<?php if($BlogUser->CanWrite()): ?>
					<div class="dropdown-div">
						<a class="btn btn-outline-dark" data-post-cmd="edit" href="<?php $Printer($Post->GetEditURL()) ?>">
							<i class="mdi mdi-fw mdi-pencil"></i>
							Edit Post
						</a>
					</div>
					<div class="dropdown-div">
						<a class="btn btn-outline-dark" data-post-cmd="tags" href="#">
							<i class="mdi mdi-fw mdi-tag"></i>
							Edit Tags
						</a>
					</div>

					<?php $Surface->Area('blog/widgets/view-sidebar-manage', [ 'BlogUser'=> $BlogUser, 'Post'=> $Post ]) ?>

					<hr class="mb-2 mb-3" />

					<?php if(!$Post->Enabled): ?>
					<div class="dropdown-div">
						<a class="btn btn-outline-dark" data-post-cmd="publish" href="#">
							<i class="mdi mdi-fw mdi-eye"></i>
							Publish Post
						</a>
					</div>
					<?php else: ?>
					<div class="dropdown-div">
						<a class="btn btn-outline-dark" data-post-cmd="draft" href="#">
							<i class="mdi mdi-fw mdi-eye-off"></i>
							Set To Draft Mode
						</a>
					</div>
					<?php endif; ?>

					<hr class="mb-2 mb-3" />

					<div class="dropdown-div">
						<a class="btn btn-outline-dark" data-post-cmd="delete" href="#">
							<i class="mdi mdi-fw mdi-trash-can"></i>
							Delete Post
						</a>
					</div>
					<?php endif; ?>
				</div>
			</div>
			<?php endif; ?>
		</div>
	</div>
	<hr class="mt-1" />
</div>

<div class="pt-0 pb-4">
	<div class="container">

		<?php if(!$Post->Enabled): ?>
		<div class="alert alert-primary text-center p-2 mb-4">
			This post is in DRAFT mode.
		</div>
		<?php endif; ?>

		<?php
		match($Post->Editor) {
			'link'
			=> $Surface->Area('blog/views/link', $__SCOPE),

			default
			=> $Surface->Area('blog/views/html', $__SCOPE)
		};
		?>

	</div>
</div>

<?php if($BlogUser && $BlogUser->CanEdit()): ?>
<script type="module">
import Blog from '/share/atlantis/blog.js';

jQuery(function(){
	let post = Blog.Post.FromElement({ bindify: true });
	return;
});

</script>
<?php endif; ?>
