<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Surface\Engine $Surface
 * @var Nether\User\EntitySession $User
 * @var bool $ConfirmReq - if email confirmation is required.
 * @var bool $Updated - if the email address was updated.
 * @var bool $Sent - if an email confirmation was sent.
 */

use Nether\Common;
use Nether\Atlantis\Routes\User\AuthApple;
use Nether\Atlantis\Routes\User\AuthDiscord;
use Nether\Atlantis\Routes\User\AuthGitHub;
use Nether\Atlantis\Routes\User\AuthGoogle;

$Surface
->Set('Page.Title', 'Manage Authentication Connections')
->Area('dashboard/nav', [ 'Trail' => [ $Surface->Get('Page.Title') => NULL ]]);

////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////

$GetConnectButton = function(string $Type) use($App) {

	$Output = sprintf(
		'<a href="/auth/%s?goto=%s" class="btn btn-primary" data-auth-action="post" data-auth-type="%s">Connect</a>',
		$Type,
		Common\Datafilters::Base64Encode($App->Router->Request->GetURL()),
		$Type
	);

	return $Output;
};

$GetRemoveButton = function(string $Type) {

	$Output = sprintf(
		'<button class="btn btn-danger CmdAuthToggle" data-auth-action="delete" data-auth-type="%s">Disconnect</button>',
		$Type
	);

	return $Output;
};

?>

<div class="row">
	<div class="col-12 mb-4 hr-hide-last">
		<?php if(Nether\User\Library::IsAppleEnabled()): ?>
		<div class="row align-items-center">
			<div class="col-auto">
				<i class="font-size-larger si si-apple"></i>
			</div>
			<div class="col">
				Apple
			</div>
			<div class="col-auto">
				<?php
				echo $User->AuthAppleID
				? $GetRemoveButton(AuthApple::GetAuthKey())
				: $GetConnectButton(AuthApple::GetAuthKey());
				?>
			</div>
		</div>
		<hr />
		<?php endif; ?>

		<?php if(Nether\User\Library::IsDiscordEnabled()): ?>
		<div class="row align-items-center">
			<div class="col-auto">
				<i class="font-size-larger si si-discord"></i>
			</div>
			<div class="col">
				Discord
			</div>
			<div class="col-auto">
				<?php
				echo $User->AuthDiscordID
				? $GetRemoveButton(AuthDiscord::GetAuthKey())
				: $GetConnectButton(AuthDiscord::GetAuthKey());
				?>
			</div>
		</div>
		<hr />
		<?php endif; ?>

		<?php if(Nether\User\Library::IsGitHubEnabled()): ?>
		<div class="row align-items-center">
			<div class="col-auto">
				<i class="font-size-larger si si-github"></i>
			</div>
			<div class="col">
				GitHub
			</div>
			<div class="col-auto">
				<?php
				echo $User->AuthGitHubID
				? $GetRemoveButton(AuthGithub::GetAuthKey())
				: $GetConnectButton(AuthGithub::GetAuthKey());
				?>
			</div>
		</div>
		<hr />
		<?php endif; ?>

		<?php if(Nether\User\Library::IsGoogleEnabled()): ?>
		<div class="row align-items-center">
			<div class="col-auto">
				<i class="font-size-larger si si-google"></i>
			</div>
			<div class="col">
				Google
			</div>
			<div class="col-auto">
				<?php
				echo $User->AuthGoogleID
				? $GetRemoveButton(AuthGoogle::GetAuthKey())
				: $GetConnectButton(AuthGoogle::GetAuthKey());
				?>
			</div>
		</div>
		<hr />
		<?php endif; ?>

	</div>

</div>

<script type="module">
import NUI from '/share/nui/nui.js?v=<?php $Printer($CacheBuster) ?>';

jQuery(function(){

	jQuery('.CmdAuthToggle')
	.on('click', function(){

		let req = new NUI.Request(
			jQuery(this).attr('data-auth-action').toUpperCase(),
			'/api/dashboard/auth'
		);

		let data = NUI.Form.ObjectArrayToDataString([
			{ name: 'AuthType', value: jQuery(this).attr('data-auth-type') }
		]);

		(req.send(data))
		.then(req.goto)
		.catch(req.catch);

		return false;
	});

	return;
});
</script>

