<?php

use Nether\Atlantis\Dashboard\SidebarGroup;
use Nether\Atlantis\Dashboard\SidebarGroupItem;

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Common\Datastore $SidebarItems
 */

$Surface->Area('dashboard/nav');

?>

<div class="row">
	<?php foreach($SidebarItems as $Group): /** @var SidebarGroup $Group */ ?>
		<div class="col-12 mb-6">
			<div class="text-uppercase"><?php $Printer($Group->Title) ?></div>
			<hr class="mt-0 mb-2" />

			<div class="row tight">
				<?php foreach($Group->Items as $Key => $Item): /** @var SidebarGroupItem $Item */ ?>
				<div class="col-6 col-md-4 mb-2">
						<a href="<?php $Printer($Item->URL) ?>" class="btn btn-dark btn-left text-ellipsis">
							<div class="text-align-center font-size-mostest-large"><i class="mdi mdi-fw <?php $Printer($Item->Icon ?? 'mdi-blank') ?>"></i></div>
							<div class="text-align-center"><?php $Printer($Item->Title) ?></div>
						</a>
				</div>
				<?php endforeach; ?>
			</div>

		</div>
	<?php endforeach; unset($Key, $Item, $Group); ?>
</div>

<div class="row d-none">
	<div class="col-12 col-md-4">

		<?php foreach($SidebarItems as $Group): /** @var SidebarGroup $Group */ ?>
		<dl class="mb-6">
			<dt>
				<span class="text-uppercase"><?php $Printer($Group->Title) ?></span>
				<hr class="mt-0 mb-2" />
			</dt>
			<?php foreach($Group->Items as $Key => $Item): /** @var SidebarGroupItem $Item */ ?>
			<dd class="<?php $Printer($Group->Items->IsLastKey($Key) ? 'mb-0' : 'mb-2') ?>">
				<a href="<?php $Printer($Item->URL) ?>" class="btn btn-dark btn-left text-ellipsis">
					<i class="mdi mdi-fw <?php $Printer($Item->Icon ?? 'mdi-blank') ?>"></i>
					<?php $Printer($Item->Title) ?>
				</a>
			</dd>
			<?php endforeach; ?>
		</dl>
		<?php endforeach; unset($Key, $Item, $Group); ?>

	</div>
	<div class="col">



	</div>
</div>
