<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

use Nether\Atlantis\Plugin\Interfaces\Dashboard\InfoWidgetInterface;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\Routes\User\UserSessionWeb $Route
 * @var Common\Datastore $InfoWidgets
 */

################################################################################
################################################################################

$Surface->Area('dashboard/__header');

($Surface->Get('Page.Body.Classes'))
->Push('atl-page-dashboard');

?>

<?php if($InfoWidgets->Count()): ?>
<div class="container mb-6">
	<div class="row">
		<?php
		$InfoWidgets->Each(
			fn(InfoWidgetInterface $P)
			=> printf(
				'<div class="%s mb-4">%s</div>',
				$P->GetColumnSizes(),
				$P->Render()
			)
		)
		?>
	</div>
</div>
<?php endif; ?>
