<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Surface;
use Nether\User;

use Nether\Atlantis\Dashboard\SidebarGroup;
use Nether\Atlantis\Dashboard\SidebarGroupItem;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\Routes\User\UserSessionWeb $Route
 * @var Nether\Common\Datastore $SidebarItems
 * @var Nether\Common\Datastore $MainItems
 */


$Surface->Area('dashboard/nav');

?>

<div class="row mb-8">
	<?php foreach($MainItems as $Element): /** @var Atlantis\Dashboard\Element $Element */ ?>
	<div class="<?php $Util->Print($Element->GetBootstrapColumnClasses()) ?> mb-4">
		<?php $Surface->Area($Element->Area, array_merge($__SCOPE, [ 'Element'=> $Element ])) ?>
	</div>
	<?php endforeach; ?>
</div>
