<?php

/**
 * @var array $Left
 * @var array $Right
 */


?>

<div class="jumbotron rounded p-2 mb-4">
	<div class="row tight justify-content-between align-items-center">
		<div class="col-auto"></div>
		<div class="col-auto">
			<div class="row tight">
			<?php foreach($Right as $Item): ?>
				<div class="col-auto">
					<?php $Item->Print() ?>
				</div>
			<?php endforeach; ?>
			</div>
		</div>
	</div>
</div>