<?php

use Nether\Atlantis;
use Nether\Surface;

/**
 * @var Surface\Engine $Surface
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Atlantis\UI\Article $Element
 */

$Section ??= $Element->Section ?: NULL;
$SectionClass ??= $Element->SectionClass ?: NULL;
$SectionURL ??= $Element->SectionURL ?: NULL;

$Title ??= $Element->Title ?: NULL;
$TitleClass ??= $Element->TitleClass ?: NULL;
$TitleURL ??= $Element->TitleURL ?: NULL;

$Authour ??= $Element->Authour ?: NULL;
$AuthourClass ??= $Element->AuthourClass ?: NULL;
$AuthourURL ??= $Element->AuthourURL ?: NULL;

$Date ??= $Element->Date ?: NULL;
$DateClass ??= $Element->DateClass ?: NULL;

$Content ??= $Element->Content ?: NULL;
$ContentClass ??= $Element->ContentClass ?: NULL;

?>

<article class="<?php $Util->Print($Element->GetClassesForHTML('atl-ui-article')) ?>">

	<?php if($Section instanceof Surface\Element): ?>
	<div class="atl-ui-article-pathbar <?php $Util->Print($SectionClass) ?>">
		<?php echo $Section ?>
	</div>

	<?php elseif($Section): ?>
	<div class="atl-ui-article-section <?php $Util->Print($SectionClass) ?>">
		<?php if($SectionURL): ?><a href="<?php $Util->Print($SectionURL) ?>"><?php endif; ?>
		<?php $Util->Print($Section) ?>
		<?php if($SectionURL): ?></a><?php endif; ?>
	</div>
	<?php endif; ?>

	<?php if($Title): ?>
	<h1 class="atl-ui-article-title <?php $Util->Print($TitleClass) ?>">
		<?php if($TitleURL): ?><a href="<?php $Util->Print($TitleURL) ?>"><?php endif; ?>
		<?php $Util->Print($Title) ?>
		<?php if($TitleURL): ?></a><?php endif; ?>
	</h1>
	<?php endif; ?>

	<?php if($Date || $Authour): ?>
	<div class="atl-ui-article-subline">
		<?php if($Date): ?>
		<div class="atl-ui-article-date <?php $Util->Print($DateClass) ?>">
			<i class="mdi mdi-square-medium"></i>
			<?php $Util->Print($Date) ?>
		</div>
		<?php endif; ?>
		<?php if($Authour): ?>
		<div class="atl-ui-article-by <?php $Util->Print($AuthourClass) ?>">
			<i class="mdi mdi-square-medium"></i>
			By
			<?php if($AuthourURL): ?><a href="<?php $Util->Print($AuthourURL) ?>"><?php endif; ?>
			<?php $Util->Print($Authour) ?>
			<?php if($AuthourURL): ?></a><?php endif; ?>
		</div>
		<?php endif; ?>
	</div>
	<?php endif; ?>

	<?php if($Content): ?>
	<div class="atl-ui-article-content <?php $Util->Print($ContentClass) ?>">
		<?php echo $Content ?>
	</div>
	<?php endif; ?>

</article>
