<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore $Trail
 * @var Database\ResultSet $Tags
 */

$Surface
->Area('media/dashboard/scripts', $__SCOPE)
->Area('dashboard/nav', [ 'Trail'=> $Trail ]);

$View = 'list';

?>

<div class="jumbotron rounded mb-4">
	<form id="SearchFilters" method="post">
		<div class="row mb-2">
			<div class="col">
				<input name="q" type="text" class="form-control" placeholder="Search..." value="<?php $Util->Print($Route->Data->Q) ?>" />
			</div>
			<div class="col-auto">
				<select name="type" class="form-select">
					<optgroup label="Content Management">
						<option value="tag" <?php $Util->Print($Util->GetSelectedHTML($Filters['Type'] === 'tag')) ?>>Tags</option>
					</optgroup>

					<optgroup label="System">
						<option value="topic" <?php $Util->Print($Util->GetSelectedHTML($Filters['Type'] === 'topic')) ?>>Topics</option>
						<option value="site" <?php $Util->Print($Util->GetSelectedHTML($Filters['Type'] === 'site')) ?>>Sites</option>
					</optgroup>
				</select>
			</div>
		</div>
		<div class="row align-items-center">
			<div class="col-auto">
				<button type="submit" class="btn btn-dark">
					<i class="mdi mdi-magnify"></i>
					Search
				</button>
			</div>

			<?php if($Searched): ?>
			<div class="col-auto">(<a href="?">Reset</a>)</div>
			<?php endif; ?>
		</div>
	</form>
	<script type="module">
	import FormUtil from '/share/nui/util/form.js';

	jQuery(function(){

		jQuery('#SearchFilters')
		.on('submit', function() {

			location.href = (
				(new FormUtil(this))
				.read()
				.trim(['type', 'q'])
				.updateCurrentUrl([
					{ name: 'type', default: 'tag' },
					{ name: 'q',    default: '' }
				])
			);

			return false;
		});

		return;
	});
	</script>
</div>

<div class="row align-items-center">
	<div class="col">
		<span class="fw-bold text-uppercase">
			<?php $Util->Print($Tags->Total) ?> Tags Found
		</span>
	</div>
	<div class="col-auto">
		<div class="btn btn-outline-dark CmdTagNew">
			<i class="mdi mdi-plus"></i>
			New Tag
		</div>
	</div>
</div>
<hr />



<?php if($View === 'list'): foreach($Tags as $Tag): /** @var Atlantis\Tag\Entity $Tag */ ?>
<div class="row align-items-center">
	<div class="col-auto">
		<div class="ratiobox square wallpapered rounded" style="width:48px; background-image:url(<?php $Util->Print($Tag->GetCoverImageURL()) ?>);">
			<?php if(!$Tag->HasCoverImage()): ?>
			<div class="position-absolute position-v-center position-h-center font-size-large">
				<i class="mdi mdi-tag"></i>
			</div>
			<?php endif; ?>
		</div>
	</div>
	<div class="col">
		<a href="<?php $Util->Print($Tag->GetPageURL()) ?>"><?php $Util->Print($Tag->Name) ?></a>
	</div>
	<div class="col-auto font-size-largerer">
		<?php if($Tag->ExtraData->HasKey('URL')): ?>
		<a href="<?php $Util->Print($Util->RewriteURL($Tag->ExtraData->Get('URL'))) ?>" target="_blank">
			<i class="mdi mdi-link-box-variant mr-0 opacity-50"></i>
		</a>
		<?php endif; ?>
	</div>
	<div class="col-auto">
		<div class="btn btn-dark CmdTagEdit" data-tag-id="<?php $Util->Print($Tag->ID) ?>">
			<i class="mdi mdi-pencil"></i>
			Edit
		</div>
	</div>
	<div class="col-auto">
		<button class="btn btn-danger CmdTagDelete" data-tag-id="<?php $Util->Print($Tag->ID) ?>">
			<i class="mdi mdi-close mr-0"></i>
		</button>
	</div>
</div>
<hr />
<?php endforeach; endif; ?>

<div>
	<?php $Surface->Area('widgets/pager', [ 'Results'=> $Tags ]) ?>
</div>

<script type="module">
import API from '/share/nui/api/json.js';
import DialogUtil from '/share/nui/util/dialog.js';

jQuery(function() {

	jQuery('.CmdTagNew')
	.on('click', function(){

		let diag = new DialogUtil.Window({
			title: 'New Tag',
			labelAccept: 'Add',
			fields: [
				new DialogUtil.Field('text', 'Name', null)
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('POST', '/api/tag/entity', data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.show();

		return false;
	});

	jQuery('.CmdTagEdit')
	.on('click', function(){

		let tag = { id: parseInt(this.dataset.tagId) };

		let diag = new DialogUtil.Window({
			title: 'Edit Tag',
			labelAccept: 'Save',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, tag.id),
				new DialogUtil.Field('text', 'Name', null),
				new DialogUtil.Field('text', 'Alias', null),
				new DialogUtil.Field('text', 'ExtraData[URL]')
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('PATCH', '/api/tag/entity', data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.fillByRequest(
			'GET', '/api/tag/entity',
			{ ID: tag.id },
			true,
			function(d, result) {
				d.body.find('[name="ExtraData[URL]"]').val(result.payload.ExtraData.URL);
				return;
			}
		);

		return false;
	});

	jQuery('.CmdTagDelete')
	.on('click', function() {

		let tag = { id: parseInt(this.dataset.tagId) };

		let diag = new DialogUtil.Window({
			title: 'Confirm Tag Delete',
			body: '<blockquote class="quotron">Loading...</blockquote>',
			labelAccept: 'Yes',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, tag.id)
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('DELETE', '/api/tag/entity', data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.fillByRequest(
			'GET', '/api/tag/entity',
			{ ID: tag.id },
			true,
			function(d, result) {

				diag.body.find('blockquote')
				.html(`Delete ${result.payload.Name}? This cannot be undone.`);

				return;
			}
		);

		return;
	});

	return;
});
</script>

