<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Route->Title = 'Article & Content Element';
$Route->Info = 'Present some basic data in the style of an article or news post.';

$Route->Pathbar->Items->Push(Atlantis\Struct\Item::New(
	Title: 'Article',
	URL: '/docs/ui/article'
));

$Surface->Area('sensei/docs/__example-via-area', [
	'Areas' => [
		'Basic Article View'
		=> 'sensei/docs/ui/article/example-basic'
	]
]);
