<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Surface->Area('sensei/docs/__header', [
	'Title' => 'Slider',
	'Trail' => [ Atlantis\Struct\Item::New(Title: 'UI', URL: '/docs/ui') ]
]);

$Surface->Area('sensei/docs/__example-via-area', [
	'Areas' => [
		'Manual Setup'
		=> 'sensei/docs/ui/slider/example-basic',

		'From ResultSet'
		=> 'sensei/docs/ui/slider/example-resultset'
	]
]);
