<?php

use Nether\Atlantis;
use Nether\User;

/**
 * @var Atlantis\Engine                $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var User\EntitySession             $User
 * @var Atlantis\UI\SiteMenuPage       $Element
 */

$Element->Title = 'Documentation';
$ItemArea = $Surface->Get('Theme.SiteMenu.ItemArea');

$Menu = (
	Atlantis\Struct\DropdownMenu::New()
	->ItemNew('Overview', 'mdi-file-document', '/docs')
	->ItemNew('Install & Setup', '', '/docs/afs')
	->ItemNew('CSS Reference', '', '/docs/css')
	->ItemNew('UI Element Reference', '', '/docs/ui')
);

$Menu->Items->Each(
	fn(Atlantis\Struct\DropdownItem $Item)
	=> $Surface->Area($ItemArea, [
		'Element' => $Element,
		'Menu'    => $Menu,
		'Item'    => $Item
	])
);
