<?php

use Nether\Atlantis;
use Nether\User;

/**
 * @var Atlantis\Engine                $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var User\EntitySession             $User
 * @var Atlantis\UI\SiteMenuPage       $Element
 */

$Element->Title = 'Documentation';
$ItemArea = $Surface->Get('Theme.SiteMenu.ItemArea');

$Menu = (
	Atlantis\Struct\DropdownMenu::New()
	->ItemNew('Overview', 'mdi-file-document', '/docs')
	->ItemNew('Install & Setup', 'mdi-cog-play', '/docs/afs')
	->ItemNew('CLI Reference', 'mdi-console-line', '/docs/cli')
	->ItemNew('CSS Reference', 'mdi-palette-swatch-outline', '/docs/css')
	->ItemNew('Element Reference', 'mdi-widgets', '/docs/ui')
	->ItemNew('Subsystem Reference', 'mdi-application-braces-outline', '/docs/systems')
);

$Menu->Items->Each(
	fn(Atlantis\Struct\DropdownItem $Item)
	=> $Surface->Area($ItemArea, [
		'Element' => $Element,
		'Menu'    => $Menu,
		'Item'    => $Item
	])
);
