
<hr class="mt-0 mb-0" />

<a href="/" class="row border-0 pt-3 pb-3">
	<span class="col">Home</span>
</a>
<hr class="mt-0 mb-0" />

<a href="/" data-sitemenu="SiteMenuMain/SiteMenuDocs" class="row border-0 pt-3 pb-3">
	<span class="col">Docs</span>
	<span class="col-auto">
		<i class="mdi mdi-chevron-right"></i>
	</span>
</a>
<hr class="mt-0 mb-0" />

<div class="pt-3 pb-3"><?php $Surface->Area('widgets/theme-switcher') ?></div>
