<?php

use Nether\Atlantis;

/**
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Atlantis\Struct\DropdownMenu   $Menu
 * @var Atlantis\Struct\DropdownItem   $Item
 */

$UseIcons = $Surface->Get('Theme.SiteMenu.Icons');
$NoIconIcon = $Surface->Get('Theme.SiteMenu.Icons.NoIcon');
$NextIcon = $Surface->Get('Theme.SiteMenu.Icons.Next');

?>

<?php if($Item->Title === '==='): ?>
<div class="row justify-content-center border-0 pt-3 pb-3" <?php echo $Item->GetAttrForHTML() ?>>
	<div class="col-4">
		<hr class="o-10 my-2 m-0" />
	</div>
</div>
<hr class="mt-0 mb-0" />
<?php else: ?>
<a href="<?php $Util->Print($Item->URL) ?>" class="row border-0 pt-3 pb-3" <?php echo $Item->GetAttrForHTML() ?>>
	<div class="col">
		<div>
			<?php if($UseIcons && $Item->Icon): ?>
			<i class="<?php $Util->Print($Item->GetIcon() ?: $NoIconIcon) ?> mr-1"></i>
			<?php endif; ?>

			<span class="fw-bold"><?php $Util->Print($Item->Title); ?></span>
		</div>

		<?php if($Item->Subtitle): ?>
		<div>
			<?php if($UseIcons && $Item->Icon): ?>
			<i class="mdi mdi-blank mr-1"></i>
			<?php endif; ?>

			<span class="fs-smaller o-50">
				<?php $Util->Print($Item->Subtitle); ?>
			</span>
		</div>
		<?php endif; ?>
	</div>
	<?php if($Item->Attr->HasKey('data-sitemenu')): ?>
	<span class="col-auto"><i class="<?php echo $NextIcon ?>"></i></span>
	<?php endif; ?>
</a>
<hr class="mt-0 mb-0" />
<?php endif ?>
