<?php

use Nether\Atlantis;
use Nether\User;

/**
 * @var Atlantis\Engine                $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var User\EntitySession             $User
 * @var Atlantis\UI\SiteMenuPage       $Element
 */

$Element->Title = 'Main Menu';

$AllowLogin = $App->Config[Atlantis\Key::ConfUserAllowLogin];
$AllowSignup = $App->Config[Atlantis\Key::ConfUserAllowSignup];
$ItemArea = $Surface->Get('Theme.SiteMenu.ItemArea');

$Menu = (
	Atlantis\Struct\DropdownMenu::New()
	->ItemNew('Home', 'mdi-home', '/')
	->ItemNew('Docs', 'mdi-file-document', '#',
		Attr: [ 'data-sitemenu' => 'SiteMenuMain/SiteMenuDocs' ]
	)
	->ItemNew('Dashboard', 'mdi-logout', '/dashboard',
		If: ($User instanceof User\EntitySession)
	)
	->ItemNew('Log Out', 'mdi-logout', '/logout',
		If: ($User instanceof User\EntitySession)
	)
	->ItemNew('Log In', 'mdi-login', '/login',
		If: (!$User && $AllowLogin)
	)
	->ItemNew('Sign Up', 'mdi-account', '/signup',
		If: (!$User && $AllowSignup)
	)
);

$Menu->Items->Each(
	fn(Atlantis\Struct\DropdownItem $Item)
	=> $Surface->Area($ItemArea, [
		'Element' => $Element,
		'Menu'    => $Menu,
		'Item'    => $Item
	])
);

?>

<div class="pt-3 pb-3">
	<?php $Surface->Area('widgets/theme-switcher') ?>
</div>
