<?php

use Nether\Atlantis;
use Nether\User;

/**
 * @var Atlantis\Engine                $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var User\EntitySession             $User
 * @var Atlantis\UI\SiteMenuPage       $Element
 */

$Element->Title = $App->Config->Get(Atlantis\Key::ConfProjectName);

$AllowLogin = $App->Config[Atlantis\Key::ConfUserAllowLogin];
$AllowSignup = $App->Config[Atlantis\Key::ConfUserAllowSignup];
$ItemArea = $Surface->Get('Theme.SiteMenu.ItemArea');

////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////

$Menu = (
	Atlantis\Struct\DropdownMenu::New()
	->ItemNew('Home', 'mdi-home', '/')
	->ItemNew('Docs', 'mdi-file-document', '#',
		Attr: [ 'data-sitemenu' => 'SiteMenuRoot/SiteMenuDocs' ]
	)
);

////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////

if($User instanceof User\EntitySession) {
	$Menu->ItemNew('Dashboard', 'mdi-view-dashboard', '/dashboard');
	$Menu->ItemNew(sprintf('Log Out (%s)', $User->GetAlias(TRUE)), 'mdi-logout', '/logout');
}

else {
	if($AllowLogin)
	$Menu->ItemNew('Log In', 'mdi-login', '/login');

	if($AllowSignup)
	$Menu->ItemNew('Sign Up', 'mdi-account', '/signup');
}

////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////

$Menu->Items->Each(
	fn(Atlantis\Struct\DropdownItem $Item)
	=> $Surface->Area($ItemArea, [
		'Element' => $Element,
		'Menu'    => $Menu,
		'Item'    => $Item
	])
);

?>

<div class="pt-3 pb-3">
	<?php $Surface->Area('widgets/theme-switcher') ?>
</div>
