<span style="font-weight: bold; color: #7B9BD5;">██ CodeServerTool ██████████████████████████████████████████████████████████████</span>
<span style="color: #676767;">██ Version: 5.0.0-dev ██████████████████████████████████████████████████████████</span>

<span style="font-weight: bold; color: #9EB2D7;">USAGE:</span> codeserver.atl [command] [args]

<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help [command]:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7B9BD5;">install</span>
<span style="color: #676767;">Downloads Code-Server tarball and sets it up in ./local</span>

<span style="font-weight: bold; color: #7B9BD5;">patch-custom-css</span>
<span style="color: #676767;">No info provided.</span>

<span style="font-weight: bold; color: #7B9BD5;">run</span> --pass=…
<span style="color: #676767;">No info provided.</span>

	--pass=…
	<span style="color: #676767;">Omit to use the password in the config file. Specify to set a new password. No value will auto generate a new password.</span>

