<span style="font-weight: bold; color: #7B9BD5;">██ DateTool ████████████████████████████████████████████████████████████████████</span>
<span style="color: #676767;">██ Version: 5.0.0-dev ██████████████████████████████████████████████████████████</span>

<span style="font-weight: bold; color: #9EB2D7;">USAGE:</span> date.atl [command] [args]

<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help [command]:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7B9BD5;">datetime</span> --date=… --time=… --tz=… --unix=…
<span style="color: #676767;">Show date and time stamp info.</span>

	--date=…
	<span style="color: #676767;">A date component to use as input.</span>

	--time=…
	<span style="color: #676767;">A time component to use as input.</span>

	--tz=…
	<span style="color: #676767;">A timezone component to use as input.</span>

	--unix=…
	<span style="color: #676767;">Unix timestamp as an integer to use as input date. Overrides all other input options.</span>

