<span style="font-weight: bold; color: #7B9BD5;">██ DevTool █████████████████████████████████████████████████████████████████████</span>
<span style="color: #676767;">██ Version: 5.0.0-dev ██████████████████████████████████████████████████████████</span>

<span style="font-weight: bold; color: #9EB2D7;">USAGE:</span> dev.atl [command] [args]

<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help [command]:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7B9BD5;">ace</span>
<span style="color: #676767;">Generate an ace.json file listing the themes and modes.</span>

<span style="font-weight: bold; color: #7B9BD5;">cachebust</span> --delete --update
<span style="color: #676767;">Manage the cache.bust file the theme engine uses.</span>

	--delete
	<span style="color: #676767;">Delete the cache.bust file.</span>

	--update
	<span style="color: #676767;">Update the cache.bust file.</span>

<span style="font-weight: bold; color: #7B9BD5;">dyes</span>
<span style="color: #676767;">No info provided.</span>

<span style="font-weight: bold; color: #7B9BD5;">gen-cli-html</span>
<span style="color: #676767;">Generate the theme PHTML files for the CLI commmand helps.</span>

<span style="font-weight: bold; color: #7B9BD5;">jsondbg</span> --struct --json --touch --rewrite
<span style="color: #676767;">Debug tool for atlantis.json</span>

	--struct
	<span style="color: #676767;">Print the parsed structure.</span>

	--json
	<span style="color: #676767;">Print the JSON structure.</span>

	--touch
	<span style="color: #676767;">Touch the selected JSON file.</span>

	--rewrite
	<span style="color: #676767;">Rewrite the selected JSON file.</span>

<span style="font-weight: bold; color: #7B9BD5;">loc</span> [directory] [...] --nether --ext=…
<span style="color: #676767;">Count lines of code in the specified directories.</span>

	--nether
	<span style="color: #676767;">Include installed NetherPHP libraries.</span>

	--ext=…
	<span style="color: #676767;">Comma delimited list of file extensions to include.</span>

<span style="font-weight: bold; color: #7B9BD5;">pullenv</span>
<span style="color: #676767;">No info provided.</span>

<span style="font-weight: bold; color: #7B9BD5;">run</span> [cmdname] --dry --cmd --hush
<span style="color: #676767;">Run one of the pre-defined command sequences from the project config.</span>

	--dry
	<span style="color: #676767;">Only make believe.</span>

	--cmd
	<span style="color: #676767;">Show the command that it executes.</span>

	--hush
	<span style="color: #676767;">Do not show the output of commands unless error.</span>

<span style="font-weight: bold; color: #7B9BD5;">sync</span> [source] [dest] --soft
<span style="color: #676767;">Wrap RSYNC to do the one goddamn thing I use it for, to make a mirror of a source directory, in a way I can remember. The source is the authouritative copy, the mirror is the duplicate.</span>

	--soft
	<span style="color: #676767;">When updating a destination, do not delete files the source said have been deleted.</span>

<span style="font-weight: bold; color: #7B9BD5;">uuid</span>
<span style="color: #676767;">No info provided.</span>

