<span style="font-weight: bold; color: #7B9BD5;">██ DHDTool █████████████████████████████████████████████████████████████████████</span>
<span style="color: #676767;">██ Version: 5.0.0-dev ██████████████████████████████████████████████████████████</span>

<span style="font-weight: bold; color: #9EB2D7;">USAGE:</span> dhd.atl [command] [args]

<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help [command]:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7B9BD5;">update</span> --outfile=…
<span style="color: #676767;">Update the routes.phson file.</span>

	--outfile=…
	<span style="color: #676767;">File to update. (Default: ./routes.phson)</span>

