<span style="font-weight: bold; color: #7B9BD5;">██ Atlantis Graphics Tool ██████████████████████████████████████████████████████</span>
<span style="color: #676767;">██ Version: 5.0.0-dev ██████████████████████████████████████████████████████████</span>

<span style="font-weight: bold; color: #9EB2D7;">USAGE:</span> gfx.atl [command] [args]

<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help [command]:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7B9BD5;">genshare</span> [path/to/image.png] --force --width=… --height=… --scale=… --bg=… --ext=… --suffix=…
<span style="color: #676767;">Generate the social share sized versions of a graphic. Mostly used for site logos.</span>

	--force
	<span style="color: #676767;">Allows overwriting existing output file.</span>

	--width=…
	<span style="color: #676767;">Width of output. Default: 1920</span>

	--height=…
	<span style="color: #676767;">Height of output. Default: 1080</span>

	--scale=…
	<span style="color: #676767;">Percentage input fills the output. Default: 64 (%)</span>

	--bg=…
	<span style="color: #676767;">Background colour of the output. Should accept any CSS colour name or hex code.</span>

	--ext=…
	<span style="color: #676767;">Output file extension/format. Recommend sticking with "jpg" or "png". Default: jpg</span>

	--suffix=…
	<span style="color: #676767;">Suffix that gets added to the filename. Default: ogimage</span>

<span style="font-weight: bold; color: #7B9BD5;">qr</span> [data] --size=… --fresh=…
<span style="color: #676767;">No info provided.</span>

	--size=…
	<span style="color: #676767;">Size of the QR in pixels. (Default: 1200)</span>

	--fresh=…
	<span style="color: #676767;">Overwrite with fresh copy if already exists.</span>

<span style="font-weight: bold; color: #7B9BD5;">wm</span> [path/to/base.jpg] [path/to/watermark.png] --minv --mrot=… --mc=… --mo=… --tb[1-9]=…
<span style="color: #676767;">Overlay a watermark on a base image.</span>

	--minv
	<span style="color: #676767;">Invert the watermark colours.</span>

	--mrot=…
	<span style="color: #676767;">Rotate the watermark (degrees).</span>

	--mc=…
	<span style="color: #676767;">Number of times watermark is repeated (how many columns).</span>

	--mo=…
	<span style="color: #676767;">Opacity of watermark.</span>

	--tb[1-9]=…
	<span style="color: #676767;">Lines of text at the bottom of the image.</span>

