<span style="font-weight: bold; color: #7B9BD5;">██ ProjectTool █████████████████████████████████████████████████████████████████</span>
<span style="color: #676767;">██ Version: 5.0.0-dev ██████████████████████████████████████████████████████████</span>

<span style="font-weight: bold; color: #9EB2D7;">USAGE:</span> project.atl [command] [args]

<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help [command]:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7B9BD5;">init</span>
<span style="color: #676767;">Begin setting up the project from scratch.</span>

<span style="font-weight: bold; color: #7B9BD5;">setup</span> --fix
<span style="color: #676767;">Reconfigure anything that can be reconfigured easily.</span>

	--fix
	<span style="color: #676767;">Try to forcefully fix things considered errors.</span>

<span style="font-weight: bold; color: #7B9BD5;">db</span> --info=… --json=… --set=… --del=… --host=… --db=… --user=… --pass=…
<span style="color: #676767;">Manage the project database connection info.</span>

	--info=…
	<span style="color: #676767;">Specify the connection name to display the connection info.</span>

	--json=…
	<span style="color: #676767;">Specify the connection name to print the connection as JSON.</span>

	--set=…
	<span style="color: #676767;">Specify the connection name to add or update. ["Default"]</span>

	--del=…
	<span style="color: #676767;">Specify the connection name to delete from the config.</span>

	--host=…
	<span style="color: #676767;">Hostname of the DB Server.</span>

	--db=…
	<span style="color: #676767;">Name of the Database to open.</span>

	--user=…
	<span style="color: #676767;">Database auth username.</span>

	--pass=…
	<span style="color: #676767;">Database auth password.</span>

<span style="font-weight: bold; color: #7B9BD5;">dirs</span> --add --del --path=…
<span style="color: #676767;">Lists and Edit the directories managed by the Project JSON.</span>

	--add
	<span style="color: #676767;">Add the specified --path.</span>

	--del
	<span style="color: #676767;">Delete the specified --path.</span>

	--path=…
	<span style="color: #676767;">The path to manage.</span>

<span style="font-weight: bold; color: #7B9BD5;">perms</span> --add --del --path=… --mode=…
<span style="color: #676767;">No info provided.</span>

	--add
	<span style="color: #676767;">Add the specified path+mode to the config.</span>

	--del
	<span style="color: #676767;">Remove the specified path from the config.</span>

	--path=…
	<span style="color: #676767;">The path to manage.</span>

	--mode=…
	<span style="color: #676767;">The mode to chmod the path.</span>

<span style="font-weight: bold; color: #7B9BD5;">symlinks</span> --add --del --path=… --source=…
<span style="color: #676767;">Lists and Edit the Symlinks managed by the Project JSON.</span>

	--add
	<span style="color: #676767;">Add the specified --path.</span>

	--del
	<span style="color: #676767;">Delete the specified --path.</span>

	--path=…
	<span style="color: #676767;">The path to manage.</span>

	--source=…
	<span style="color: #676767;">The source to point at.</span>

