<span style="font-weight: bold; color: #7B9BD5;">██ CertTool ████████████████████████████████████████████████████████████████████</span>
<span style="color: #676767;">██ Version: 5.0.0-dev ██████████████████████████████████████████████████████████</span>

<span style="font-weight: bold; color: #9EB2D7;">USAGE:</span> ssl.atl [command] [args]

<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help [command]:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7B9BD5;">config</span>
<span style="color: #676767;">Tool to configure the SSL cert for this project.</span>

<span style="font-weight: bold; color: #7B9BD5;">renew</span> --issue
<span style="color: #676767;">Renew the SSL cert for this project.</span>

	--issue
	<span style="color: #676767;">Issue the SSL for the first time.</span>

<span style="font-weight: bold; color: #7B9BD5;">cron</span>
<span style="color: #676767;">Shows the line to be added to crontab to auto-renew SSL.</span>

<span style="font-weight: bold; color: #7B9BD5;">lookup</span> [domain]
<span style="color: #676767;">Check the status of an SSL cert for any domain on the internet.</span>

