<span style="font-weight: bold; color: #7B9BD5;">██ Tags ████████████████████████████████████████████████████████████████████████</span>
<span style="color: #676767;">██ Version: 0.0.0 ██████████████████████████████████████████████████████████████</span>

<span style="font-weight: bold; color: #9EB2D7;">USAGE:</span> tag.atl [command] [args]

<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help [command]:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7B9BD5;">add</span> [name] --alias=… --type=… --subtype=…
<span style="color: #676767;">No info provided.</span>

	--alias=…
	<span style="color: #676767;">Specify a custom alias rather than generating it based from the name of the tag.</span>

	--type=…
	<span style="color: #676767;">Specify a type: "tag", "site", "topic" (default: "tag")</span>

	--subtype=…
	<span style="color: #676767;">Specify a subtype (default: "normal")</span>

<span style="font-weight: bold; color: #7B9BD5;">del</span> --id=… --alias=…
<span style="color: #676767;">No info provided.</span>

	--id=…
	<span style="color: #676767;">ID of the tag to delete.</span>

	--alias=…
	<span style="color: #676767;">Alias of the tag to delete.</span>

<span style="font-weight: bold; color: #7B9BD5;">list</span> uuid glomp
<span style="color: #676767;">No info provided.</span>

	uuid
	<span style="color: #676767;">Include a UUID column in the report.</span>

	glomp
	<span style="color: #676767;">Dump one giant list no pagination.</span>

<span style="font-weight: bold; color: #7B9BD5;">z-import-geo-us</span>
<span style="color: #676767;">No info provided.</span>

