<span style="font-weight: bold; color: #7B9BD5;">██ UserTool ████████████████████████████████████████████████████████████████████</span>
<span style="color: #676767;">██ Version: 5.0.0-dev ██████████████████████████████████████████████████████████</span>

<span style="font-weight: bold; color: #9EB2D7;">USAGE:</span> user.atl [command] [args]

<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help [command]:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7B9BD5;">admin</span> [id/alias/email] --set=…
<span style="color: #676767;">Check and set admin status for a user.</span>

	--set=…
	<span style="color: #676767;">Set the admin status/level. 0 to just short of infinity.</span>

<span style="font-weight: bold; color: #7B9BD5;">logout</span> [id/alias/email]
<span style="color: #676767;">Forcefully log a user out of all their sessions.</span>

<span style="font-weight: bold; color: #7B9BD5;">passwd</span> [id/alias/email]
<span style="color: #676767;">Forcefully set a user password.</span>

<span style="font-weight: bold; color: #7B9BD5;">new</span>
<span style="color: #676767;">Launch user creation wizard.</span>

