<span style="font-weight: bold; color: #7B9BD5;">██ DevTool █████████████████████████████████████████████████████████████████████</span>
<span style="color: #676767;">██ Version: 5.0.0-dev ██████████████████████████████████████████████████████████</span>

<span style="font-weight: bold; color: #9EB2D7;">USAGE:</span> web.atl [command] [args]

<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help [command]:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9EB2D7;">•</span> <span style="font-weight: bold; color: #9EB2D7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7B9BD5;">config</span> --dry
<span style="color: #676767;">Prepare web server configuration files.</span>

	--dry
	<span style="color: #676767;">Show the resulting JSON instead of updating the file.</span>

<span style="font-weight: bold; color: #7B9BD5;">setup</span>
<span style="color: #676767;">Push and confirm web server configuration setup.</span>

<span style="font-weight: bold; color: #7B9BD5;">reload</span>
<span style="color: #676767;">Kick web server to reload configuration.</span>

