<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\Media\File $File
  * @var Database\ResultSet $Related
 */

$Tags ??= NULL;
$News ??= NULL;
$Links ??= NULL;

$PBefore = Atlantis\Routes\Profile\ProfileWeb::ProfileViewExtraSectionsBefore(
	$App, $File->Profile
);

$PAfter = Atlantis\Routes\Profile\ProfileWeb::ProfileViewExtraSectionsAfter(
	$App, $File->Profile
);

$PExtra = Atlantis\Profile\Entity::FetchProfileExtraData(
	$App, $File->Profile
);

$PMenu = Atlantis\Profile\Entity::FetchProfileAdminMenu(
	$App, $File->Profile, $PExtra
);

$PMenu = (function(Atlantis\Struct\DropdownMenu $PMenu, Atlantis\Media\File $File) {

	($PMenu->Items)
	->Remove('ProfileEditItemAddress')
	->Remove('CopyEntityID')
	->Remove('CopyTagsTo')
	->Remove('ProfileMediaUploadPhoto')
	->Remove('ProfileMediaAddVideoURL');

	foreach($PMenu->Items as $MK => $MI) {
		//if($MK === 'ProfileEditItemTitleAlias') {
		//	unset($MI->Attr['data-profile-cmd']);
		//	$MI->Title = 'Edit Photo Info';
		//	$MI->Attr['data-photo-cmd'] = 'edit';
		//	$MI->Attr['data-id'] = $File->ID;
		//	$MI->Attr['data-uuid'] = $File->UUID;
		//}

		//if($MK === 'ProfileTaggingEdit') {
		//	unset($MI->Attr['data-profile-cmd']);
		//	$MI->Attr['data-photolib-cmd'] = 'tags';
		//	$MI->Attr['data-id'] = $File->ID;
		//	$MI->Attr['data-uuid'] = $File->UUID;
		//}

		if($MK === 'ProfileStateDelete') {
			unset($MI->Attr['data-profile-cmd']);
			$MI->Attr['data-photolib-cmd'] = 'delete';
			$MI->Attr['data-id'] = $File->ID;
			$MI->Attr['data-uuid'] = $File->UUID;
		}

		if($MK == 'ProfileTaggingERLink') {
			$MI->Attr['data-parent-type'] = $File::EntType;
			$MI->Attr['data-id'] = $File->ID;
			$MI->Attr['data-uuid'] = $File->UUID;
		}

	}
	return $PMenu;
})($PMenu, $File);

?>

<div class="cargobay">
	<section>
		<div class="container">

			<div class="row align-items-start mb-4">
				<div class="col">
					<h2 class="fw-bold lh-1 mb-0">
						<?php if(!$File->Profile->Title): ?>
						Viewing Photo #<?php $Util->Print($File->ID) ?>
						<?php else: ?>
						<?php $Util->Print($File->Profile->Title) ?>
						<?php endif; ?>
					</h2>
				</div>

				<?php if($Route->IsUserAdmin()): ?>
				<div class="col-auto">
					<?php echo Nether\Atlantis\UI\Dropdown::FromSurfaceWith($Surface, [
						'Menu' => $PMenu,
						'MenuBtnStyleClass'=> 'btn-outline-light',
						'ItemBtnStyleClass'=> 'btn-outline-light'
					]) ?>
				</div>
				<?php endif; ?>
			</div>

			<div class="row">
				<div class="col-12">
					<img src="<?php $Util->Print($File->GetPublicURL('lg')) ?>" class="rounded w-100" alt="" />
				</div>
			</div>

			<?php

			$Surface->Area('profile/view', [
				'Profile'        => $File->Profile,
				'ExtraData'      => $PExtra,
				'SectionsBefore' => $PBefore,
				'SectionsAfter'  => $PAfter,
				'News'           => $News,
				'Tags'           => $Tags,
				'Related'        => $Related,
				'Links'          => $Links,
				'Embed'          => TRUE
			]);

			?>


		</div>
	</section>
</div>