<div class="jumbotron rounded mb-4">
	<div class="fw-bold text-uppercase">
		Admin: Upload Manager
	</div>
	<hr class="mt-0 mb-2" />

	<div class="mb-2">
		<a href="/dashboard/media/images" class="btn btn-dark btn-block text-align-left">
			<i class="mdi mdi-view-grid"></i>
			Browse Photos
		</a>
	</div>

	<div class="mb-2">
		<a href="/dashboard/media/videos-tp" class="btn btn-dark btn-block text-align-left">
			<i class="mdi mdi-view-grid"></i>
			Browse Videos
		</a>
	</div>

</div>