<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\Dashboard\AtlantisTrafficElement $Element
 */

$GetDateFor = function(string $When) {

	$Date = Common\Date::FromDateString($When);

	return $Date->Get(Common\Values::DateFormatYMD);
};

$GetSourceName = function(string $Name) {
	return match($Name) {
		't.co'              => 'Twitter',
		'facebook.com'      => 'Facebook',
		'instagram.com'     => 'Instagram',
		'appleid.apple.com' => 'Apple Log In',
		default             => $Name
	};
};

?>

<div class="jumbotron jumbotron-outline rounded">
	<div class="row">
		<div class="col">
			<span class="fw-bold text-uppercase">Traffic Past 24HR</span>
		</div>
	</div>
	<hr class="mt-0 mb-2" />

	<div class="row mb-4">
		<div class="col-12 col-md-auto mb-2 mb-md-0">
			<div>
				<div class="font-size-most-large fw-bold"><?php $Util->Print(number_format($Element->Hits)) ?></div>
				<div class="font-size-smallest text-uppercase text-muted">Hits</div>
			</div>
		</div>
		<div class="col-12 col-md-auto mb-2 mb-md-0">
			<div>
				<div class="font-size-most-large fw-bold"><?php $Util->Print(number_format($Element->Visitors)) ?></div>
				<div class="font-size-smallest text-uppercase text-muted">Visitors</div>
			</div>
		</div>
		<div class="col-12 col-md-auto mb-2 mb-md-0">
			<div>
				<div class="font-size-most-large fw-bold"><?php $Util->Print(number_format($Element->Rows->Total)) ?></div>
				<div class="font-size-smallest text-uppercase text-muted">Pages</div>
			</div>
		</div>
		<div class="col-12 col-md mb-0 mb-md-0">
			<div class="row tight justify-content-md-end mb-1">
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-dark btn-sm pt-1 pb-1" href="/dashboard/traffic/view?when=24hr">Past 24hr</a>
				</div>
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-dark btn-sm pt-1 pb-1" href="/dashboard/traffic/view?when=48hr">48hr</a>
				</div>
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-dark btn-sm pt-1 pb-1" href="/dashboard/traffic/view?when=1wk">Week</a>
				</div>
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-dark btn-sm pt-1 pb-1" href="/dashboard/traffic/view?when=1mo">Month</a>
				</div>
			</div>
			<div class="row tight justify-content-md-end mb-0">
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-secondary btn-sm pt-1 pb-1" href="/dashboard/traffic/view?when=<?php $Util->Print($GetDateFor('today')) ?>">Today</a>
				</div>
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-secondary btn-sm pt-1 pb-1" href="/dashboard/traffic/view?when=<?php $Util->Print($GetDateFor('yesterday')) ?>">Yesterday</a>
				</div>
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-secondary btn-sm pt-1 pb-1" href="/dashboard/traffic/view?when=<?php $Util->Print(sprintf('%s-%s', date('Y'), date('m'))) ?>">MTD</a>
				</div>
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-secondary btn-sm pt-1 pb-1" href="/dashboard/traffic/view?when=<?php $Util->Print(date('Y')) ?>">YTD</a>
				</div>
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-secondary btn-sm pt-1 pb-1" data-traffic-cmd="date" href="#">Date...</a>
				</div>
			</div>
		</div>
	</div>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>
					URL
				</th>
				<th class="th-shrink">
					Count
				</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($Element->Rows as $Row): /** @var Atlantis\Struct\TrafficRow $Row */ ?>
			<tr>
				<td>
					<a href="<?php $Util->Print($Row->URL) ?>"><?php $Util->Print($Row->Path) ?></a>
				</td>
				<td class="text-align-center">
					<?php $Util->Print($Row->GetGroupCount()) ?>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>
					Source
				</th>
				<th class="th-shrink">
					Count
				</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($Element->Sources as $Domain => $Count): ?>
			<tr>
				<td><?php $Util->Print($GetSourceName($Domain)) ?></td>
				<td><?php $Util->Print($Count) ?></td>
			</tr>
		<?php endforeach; unset($Domain, $Count); ?>
		</tbody>
	</table>

</div>

<script type="module">
import DialogUtil from '/share/nui/util/dialog.js';

jQuery(function() {

	jQuery('[data-traffic-cmd=date]')
	.on('click', function() {
		let diag = new DialogUtil.Window({
			title: 'View Traffic By Date...',
			labelAccept: 'Go',
			fields: [
				new DialogUtil.Field('date', 'When', 'Date'),
			],
			onAccept: function() {

				let data = this.getFieldData();
				let url = new URL(location.href);

				url.pathname = '/dashboard/traffic/view';
				url.searchParams.set('when', data.When);
				location.href = url;
				return;
			}
		});

		diag.show();
		return false;
	});

	return;
});
</script>