<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\Dashboard\AtlantisTrafficElement $Element
 */

?>

<div class="jumbotron jumbotron-outline rounded">
	<div class="fw-bold text-uppercase">
		Traffic
	</div>
	<hr class="mt-0 mb-2" />

	<div class="row mb-4">
		<div class="col-12 col-md-auto mb-2 mb-md-0">
			<div>
				<div class="font-size-most-large fw-bold"><?php $Util->Print($Element->Hits) ?></div>
				<div class="font-size-smallest text-uppercase text-muted">Hits Last 24hr</div>
			</div>
		</div>
		<div class="col-12 col-md-auto mb-0 mb-md-0">
			<div>
				<div class="font-size-most-large fw-bold"><?php $Util->Print('#') ?></div>
				<div class="font-size-smallest text-uppercase text-muted">Unique Visitors</div>
			</div>
		</div>
	</div>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>
					URL
				</th>
				<th class="th-shrink">
					Count
				</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($Element->Rows as $Row): /** @var Atlantis\Struct\TrafficRow $Row */ ?>
			<tr>
				<td>
					<a href="<?php $Util->Print($Row->URL) ?>"><?php $Util->Print($Row->Path) ?></a>
				</td>
				<td class="text-align-center">
					<?php $Util->Print($Row->GetGroupCount()) ?>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

</div>