<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\Media\Timeline $Timeline
 * @var Atlantis\Media\TimelineItem $Item
 */

$Surface->Area('dashboard/__header', [
	'Trail' => [
		Atlantis\Struct\Item::New(Title: 'Timelines', URL: '/dashboard/timelines'),
		Atlantis\Struct\Item::New(Title: $Timeline->Title, URL: $Timeline->GetEditURL()),
		Atlantis\Struct\Item::New(Title: 'Edit Delete', URL: $Item->GetDeleteURL())
	]
]);

?>

<div class="container pb-6">
	<div id="AtlDashTimelineFormEditItem" class="ta-center" data-atl-timeline-id="<?php $Util->Print($Timeline->ID) ?>" data-atl-timeline-form="item-delete" data-atl-timeline-item-id="<?php $Util->Print($Item->ID) ?>">

		<h3>Delete Timeline Item?</h3>
		<div class="quotron mb-4"><?php $Util->Print($Item->GetTitle()) ?></div>

		<form class="rounded">
			<div class="row gy-2">
				<div class="col-12 mb-0">
					<button type="submit" class="btn btn-danger">Delete</button>
					<a href="<?php $Util->Print($Timeline->GetEditURL()) ?>" class="btn btn-secondary">Cancel</a>
				</div>
			</div>
		</form>

	</div>
</div>

<script type="module">
import Timeline from '<?php $Util->Print($App->GetCacheBustedURL('/share/atlantis/js/ents/timeline.js')) ?>';

jQuery(function(){
	Timeline.BindDocument();
	return;
});
</script>
