<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine                $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router                  $Router
 * @var Surface\Engine                 $Surface
 * @var User\EntitySession             $User
 *
 * @var Blog\Routes\BlogDashboard      $Route
 * @var Common\Datastore               $SiteTags
 * @var Common\Datastore               $Values
 * @var ?Blog\Post                     $Post
 * @var string                         $PluginData
 */


?>


<script type="module">
///...

jQuery(function(){

	///...

	return;
});
</script>
