<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore $Blogs
 * @var Blog\Post $Post
 * @var string $Editor
 */

?>

<div class="row">
	<div class="col-6 col-md-4 mb-4">
		<div class="jumbotron position-relative rounded text-align-center">
			<div class="font-size-most-large"><i class="mdi mdi-text-box-edit-outline"></i></div>
			<div>Write Post</div>

			<a href="<?php $Util->Print($Route->QueryCooker(['editor'=> 'html'])) ?>" class="position-absolutely border-0"></a>
		</div>
	</div>
	<div class="col-6 col-md-4 mb-4">
		<div class="jumbotron position-relative rounded text-align-center">
			<div class="font-size-most-large"><i class="mdi mdi-web-plus"></i></div>
			<div>Link</div>

			<a href="<?php $Util->Print($Route->QueryCooker(['editor'=> 'link'])) ?>" class="position-absolutely border-0"></a>
		</div>
	</div>
</div>
