<?php

$Items = new Nether\Object\Datastore($Surface->Get('Sensei.Breadcrumbs'));

?>

<div class="mb-6 text-muted font-size-smaller font-family-monotype letter-space-loose line-height-normal mb-3">
	<a href="/docs" class="Block Primary">docs</a> \
	<?php foreach($Items as $Title => $URL): ?>
	<a href="<?php $Printer($URL) ?>"><?php $Printer($Title) ?></a>
	<?php endforeach; unset($Item); ?>
</div>
