<?php

use Nether\Sensei\Inspectors\ClassInspector;
use Nether\Sensei\Inspectors\ConstantInspector;
use Nether\Sensei\Inspectors\PropertyInspector;
use Nether\Sensei\Inspectors\MethodInspector;
use nether\Sensei\Inspectors\ArgumentInspector;

/**
 * @var ClassInspector $Class
 */

$MethodsLocal = $Class->GetMethodsLocal();
$PropsLocal = $Class->GetPropertiesLocal();
$ConstsLocal = $Class->GetConstantsLocal();

$MethodsRemote = $Class->GetMethodsInherited();
$PropsRemote = $Class->GetPropertiesInherited();
$ConstsRemote = $Class->GetConstantsInherited();

?>

<div class="container pt-6 pb-6">

	<div class="SenseiClassHeader <?php $Printer($Class->Info ? 'mb-4' : 'mb-0') ?>">
		<div class="text-muted font-size-smaller font-family-monotype letter-space-loose line-height-normal mb-3">
			<a href="/docs" class="Block Primary">docs</a> \
			<?php echo (
				$Class->GetNamespaceName()
				? Nether\Sensei\Util::GenerateNamespaceLinkChainHTML($Class->GetNamespaceName())
				: ''
			); ?>
		</div>
		<h1 class="font-size-most-large fw-bold font-family-monotype letter-space-loose line-height-normal mb-3">
			<?php if($Class->Final): ?>
			<span class="Block Final">final</span>
			<?php endif; ?>
			<?php if($Class->Abstract): ?>
			<span class="Block Abstract">abstract</span>
			<?php endif; ?>
			<span class="Block <?php $Printer(ucfirst($Class->GetTypeWord())) ?>"><?php $Printer($Class->GetTypeWord()) ?></span>
			<?php $Printer($Class->GetBaseName()) ?>
		</h1>
		<?php foreach($Class->Interfaces as $Key => $Interface): ?>
		<div class="text-muted font-family-monotype letter-space-loose line-height-normal mb-3">
			<span class="font-family-monotype Block Interface">interface</span>
			<?php echo (
				Nether\Sensei\Util::IsBuiltInInterface($Interface)
				? sprintf(
					'<a href="%s" title="PHP Manual" target="_blank">%s <i class="im im-external-link font-size-smaller"></i></a>',
					Nether\Sensei\Util::GetClassManualURL($Interface),
					$Interface
				)
				: Nether\Sensei\Util::GenerateClassLinkChainHTML($Interface)
			) ?>
		</div>
		<?php endforeach; ?>
	</div>

	<div class="SenseiClassInfo mb-8">
		<?php if($Class->Info): ?>
		<blockquote class="blockquote pt-0 pb-0 opacity-50 font-family-monotype edged-left"><?php $Printer(Nether\Sensei\Util::TrimNetherDoc($Class->Info)) ?></blockquote>
		<?php endif; ?>
	</div>

	<div class="SenseiClassHighlights mb-8">
		<div class="row">
			<div class="col-6 col-md-4 mb-4">
				<div class="PrettyModernBox">
					<h3>
						<a href="#constants-local">Constants</a>
						<hr class="border-colour-constant" />
					</h3>
					<blockquote>
						<a href="#constants-local"><?php $Printer($ConstsLocal->Count()) ?></a>
						<?php if($ConstsRemote->Count()): ?>
						<a href="#constants-inherited" class="text-muted fs-italic">(+<?php $Printer($ConstsRemote->Count()) ?>)</a>
						<?php endif; ?>
					</blockquote>
				</div>
			</div>
			<div class="col-6 col-md-4 mb-4">
				<div class="PrettyModernBox">
					<h3>
						<a href="#properties-local">Properties</a>
						<hr class="border-colour-property" />
					</h3>
					<blockquote>
						<a href="#properties-local"><?php $Printer($PropsLocal->Count()) ?></a>
						<?php if($PropsRemote->Count()): ?>
						<a href="#properties-inherited" class="text-muted fs-italic">(+<?php $Printer($PropsRemote->Count()) ?>)</a>
						<?php endif; ?>
					</blockquote>
				</div>
			</div>
			<div class="col-6 col-md-4 mb-4">
				<div class="PrettyModernBox">
					<h3>
						<a href="#methods-local">Methods</a>
						<hr class="border-colour-method" />
					</h3>
					<blockquote>
						<a href="#methods-local"><?php $Printer($MethodsLocal->Count()) ?></a>
						<?php if($MethodsRemote->Count()): ?>
						<a href="#methods-inherited" class="text-muted fs-italic">(+<?php $Printer($MethodsRemote->Count()) ?>)</a>
						<?php endif; ?>
					</blockquote>
				</div>
			</div>

		</div>
	</div>

	<?php if($ConstsLocal->Count()): ?>
		<div class="pb-4 mb-8">
			<h2 id="constants-local" class="PrettyBrandText border-colour-constant mb-6">Local Constants</h2>
			<div class="row">
				<?php foreach($ConstsLocal as $Key => $Constant): /** @var ConstantInpector $Method */ ?>
				<div class="col-12 col-md-6 col-lg-4">
					<div class="jumbotron rounded mb-4">
						<div class="SenseiClassMethod <?php $Printer($ConstsLocal->IsLastKey($Key) ? 'mb-0' : 'mb-0') ?>">
						<?php $Surface->Area('sensei/class-constant', [ 'Class'=> $Class, 'Constant'=> $Constant ]); ?>
						</div>
					</div>
				</div>
				<?php endforeach; ?>
			</div>
		</div>
	<?php endif; ?>

	<?php if($ConstsRemote->Count()): ?>
		<div class="pb-4 mb-8">
			<h2 id="constants-local" class="PrettyBrandText border-colour-constant mb-6">Inherited Constants</h2>
			<div class="row">
				<?php foreach($ConstsRemote as $Key => $Constant): /** @var ConstantInpector $Method */ ?>
				<div class="col-12 col-md-6 col-lg-4">
					<div class="jumbotron rounded mb-4">
						<div class="SenseiClassMethod <?php $Printer($ConstsRemote->IsLastKey($Key) ? 'mb-0' : 'mb-0') ?>">
						<?php $Surface->Area('sensei/class-constant', [ 'Class'=> $Class, 'Constant'=> $Constant ]); ?>
						</div>
					</div>
				</div>
				<?php endforeach; ?>
			</div>
		</div>
	<?php endif; ?>

	<?php if($MethodsLocal->Count()): ?>
		<div class="pb-4 mb-8">
			<h2 id="methods-local" class="PrettyBrandText border-colour-method mb-6">Local Methods</h2>
			<?php foreach($MethodsLocal as $Key => $Method): /** @var MethodInspector $Method */ ?>
			<div class="jumbotron rounded mb-4">
				<div class="SenseiClassMethod <?php $Printer($MethodsLocal->IsLastKey($Key) ? 'mb-0' : 'mb-0') ?>">
				<?php $Surface->Area('sensei/class-method', [ 'Class'=> $Class, 'Method'=> $Method ]); ?>
				</div>
			</div>
			<?php endforeach; ?>
		</div>
	<?php endif; ?>

	<?php if($MethodsRemote->Count()): ?>
		<div class="pb-4 mb-8">
			<h2 id="methods-inherited" class="PrettyBrandText border-colour-method mb-6">Inherited Methods</h2>
			<?php foreach($MethodsRemote as $Key => $Method): /** @var MethodInspector $Method */ ?>
			<div class="jumbotron rounded mb-4">
				<div class="SenseiClassMethod <?php $Printer($MethodsRemote->IsLastKey($Key) ? 'mb-0' : 'mb-4') ?>">
				<?php $Surface->Area('sensei/class-method', [ 'Class'=> $Class, 'Method'=> $Method ]); ?>
				</div>
			</div>
			<?php endforeach; ?>
		</div>
	<?php endif; ?>

</div>