
	<div class="PrettyModernBox">
		<h3>
			<span>Codebase Documentation</span>
			<hr />
		</h3>
		<div>
			<p class="mb-4">
				The codebase documentation does not seem to have been
				generated yet.
			</p>

			<div>Build the Nether Docs:</div>
			<pre class="opacity-75 mb-4">$ <span class="opacity-50">vendor/bin/</span>nsen build --nether</pre>

			<div>Include Nether &amp; Local Code:</div>
			<pre class="opacity-75 mb-4">$ <span class="opacity-50">vendor/bin/</span>nsen build core routes --nether</pre>

			<div>Only Local Code:</div>
			<pre class="opacity-75 mb-0">$ <span class="opacity-50">vendor/bin/</span>nsen build core routes</pre>
		</div>
	</div>