<div class="row">
	<div class="col-12 mb-4">
		<div class="PrettyModernBox">
			<h3>
				<hr />
				<span>Guides</span>
				<hr />
			</h3>
			<div>
				<i class="mdi mdi-circle-small"></i> <a class="underdot" href="/docs/afs">Atlantis From Scratch</a>
			</div>
			<div>
				<i class="mdi mdi-circle-small"></i> <a class="underdot" href="/docs/css">CSS Reference</a>
			</div>
		</div>
	</div>
	<div class="col-12 mb-4">
		<div class="PrettyModernBox">
			<h3>
				<hr />
				<span>External</span>
				<hr />
			</h3>
			<div>
				<i class="mdi mdi-link"></i>
				<a class="underdot" href="https://api.jquery.com/" target="_blank">jQuery</a>
			</div>
			<div>
				<i class="mdi mdi-link"></i>
				<a class="underdot" href="https://getbootstrap.com/docs/5.3/layout/breakpoints/" target="_blank">Bootstrap 5.3</a>
			</div>
			<div>
				<i class="mdi mdi-link"></i>
				<a class="underdot" href="https://pictogrammers.com/library/mdi/" target="_blank">Material Design Icons</a>
			</div>
			<div>
				<i class="mdi mdi-link"></i>
				<a class="underdot" href="https://simpleicons.org/" target="_blank">Simple Icons</a>
			</div>
			<div>
				<i class="mdi mdi-link"></i>
				<a class="underdot" href="https://simplelightbox.com/" target="_blank">Simple Lightbox</a>
			</div>
		</div>
	</div>
</div>