<?php

use Nether\Sensei\Codebase;
use Nether\Sensei\Inspectors\NamespaceInspector;
use Nether\Sensei\Inspectors\ClassInspector;
use Nether\Sensei\Inspectors\ConstantInspector;
use Nether\Sensei\Inspectors\PropertyInspector;
use Nether\Sensei\Inspectors\MethodInspector;
use nether\Sensei\Inspectors\ArgumentInspector;

/**
 * @var Codebase $Codebase
 */

?>

<div class="container pt-6 pb-6">

	<div class="mb-6 text-muted font-size-smaller font-family-monotype letter-space-loose line-height-normal mb-3">
		<a href="/docs" class="Block Primary">docs</a> \
	</div>

	<?php

	if($Codebase instanceof Codebase)
	$Surface->Area('sensei/codebase-index', $__SCOPE);
	else
	$Surface->Area('sensei/codebase-gen', $__SCOPE);

	?>

</div>