<?php

use Nether\Sensei\Util;

/**
 * @var Nether\Sensei\Codebase $Codebase
 * @var Nether\Sensei\Struct\CodebaseStats $CodebaseStats;
 */

?>

<div class="SenseiClassHighlights mb-6">
	<div class="row">
		<?php foreach($CodebaseStats->Titles as $Key => $Title): ?>
		<div class="col-6 mb-4">
			<div class="PrettyModernBox">
				<h3 class="font-size-larger">
					<span><?php $Printer($Title) ?></span>
					<hr class="border-colour-<?php $Printer($Key) ?>" />
				</h3>
				<blockquote>
					<a href="?type=<?php $Printer($Key) ?>">
						<?php $Printer($CodebaseStats->Counts[$Key]) ?>
					</a>
				</blockquote>
			</div>
		</div>
		<?php endforeach; unset($Key, $Name); ?>
	</div>
</div>

<?php foreach($Codebase->Namespaces as $Namespace): ?>
<div class="mb-8">
	<div class="text-muted fw-bold font-size-largerest font-family-monotype letter-space-loose line-height-normal mb-3">
		<span class="font-family-monotype Block Namespace">namespace</span>
		<?php echo Nether\Sensei\Util::GenerateNamespaceLinkChainHTML($Namespace->Name) ?>
	</div>
	<?php foreach($Namespace->Classes as $Class): ?>
		<div class="font-family-monotype letter-space-loose line-height-normal mb-3">
			<span class="font-family-monotype Block <?php $Printer(ucfirst($Class->GetTypeWord())) ?>"><?php $Printer($Class->GetTypeWord()) ?></span>
			<a href="/docs/<?php $Printer($Class->GetURI('.class')) ?>"><?php $Printer($Class->GetBaseName()) ?></a>
		</div>
	<?php endforeach; ?>
</div>
<?php endforeach; unset($Namespace, $Class); ?>

