<div class="row">
	<div class="col-12 mb-4">
		<div class="PrettyModernBox">
			<h3>
				<hr />
				<span>Guides</span>
				<hr />
			</h3>
			<div>
				<i class="mdi mdi-circle-small"></i> <a class="underdot" href="/docs/afs">Atlantis From Scratch</a>
			</div>
			<div>
				<i class="mdi mdi-circle-small"></i> <a class="underdot" href="/docs/css">CSS Reference</a>
			</div>
		</div>
	</div>
</div>