<?php

use Nether\Sensei\Codebase;
use Nether\Sensei\Inspectors\NamespaceInspector;
use Nether\Sensei\Inspectors\ClassInspector;
use Nether\Sensei\Inspectors\ConstantInspector;
use Nether\Sensei\Inspectors\PropertyInspector;
use Nether\Sensei\Inspectors\MethodInspector;
use nether\Sensei\Inspectors\ArgumentInspector;

/**
 * @var Codebase $Codebase
 */

?>

<div class="container pt-6 pb-6">

	<?php $Surface->Area('sensei/breadcrumbs') ?>

	<div class="row">
		<div class="col">
			<?php
			if($Codebase instanceof Codebase)
			$Surface->Area('sensei/index-codebase', $__SCOPE);
			else
			$Surface->Area('sensei/index-codebase-gen', $__SCOPE);
			?>
		</div>

		<div class="col-12 col-lg-4">
			<?php $Surface->Area('sensei/index-guides') ?>
		</div>
	</div>


</div>