<?php

use Nether\Sensei\Util;

/**
 * @var Nether\Sensei\Codebase $Codebase
 * @var Nether\Sensei\Struct\CodebaseStats $CodebaseStats;
 */

?>

<div class="SenseiClassHighlights mb-6">
	<div class="row">
		<?php foreach($CodebaseStats->Titles as $Key => $Title): ?>
		<div class="col-6 col-md-6 col-lg-4 mb-4">
			<div class="PrettyModernBox">
				<h3 class="font-size-larger">
					<span><?php $Printer($Title) ?></span>
					<hr class="border-colour-<?php $Printer($Key) ?>" />
				</h3>
				<blockquote>
					<a href="?type=<?php $Printer($Key) ?>">
						<?php $Printer($CodebaseStats->Counts[$Key]) ?>
					</a>
				</blockquote>
			</div>
		</div>
		<?php endforeach; unset($Key, $Name); ?>
	</div>
</div>

<?php foreach($Codebase->Namespaces as $Namespace): ?>
<div class="Collapser">
	<header>
		<div class="font-size-smaller text-muted fw-bold font-family-monotype mb-1">
			<div><span class="font-family-monotype Block Namespace">namespace</span></div>
			<?php echo Nether\Sensei\Util::GenerateNamespaceLinkChainHTML($Namespace->Name) ?>
		</div>
		<span class="Indicator"><i class="mdi mdi-plus-thick"></i></span>
	</header>
	<section>
		<?php foreach($Namespace->Classes as $Class): ?>
		<div class="font-family-monotype mb-1">
			<span class="font-family-monotype Block <?php $Printer(ucfirst($Class->GetTypeWord())) ?>"><?php $Printer($Class->GetTypeWord()) ?></span>
			<a href="/docs/<?php $Printer($Class->GetURI('.class')) ?>"><?php $Printer($Class->GetBaseName()) ?></a>
		</div>
		<?php endforeach; ?>
	</section>
</div>
<?php endforeach; unset($Namespace, $Class); ?>

<script type="module">
import Collapser from '/share/nui/util/collapser.js';

jQuery(function(){

	jQuery('.Collapser')
	.each(function(){
		new Collapser(this);
		return;
	});

	return;
});
</script>


