<?php

use Nether\Atlantis;
use Nether\Common;
use Nether\Surface;

/**
 * @var Surface\Engine $Surface
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Atlantis\UI\PromoVideo $Element
 * @var string $UUID
 * @var string $VideoURL
 * @var string $Overlay
 * @var string $Ratio
 * @var string $Title
 * @var string $Subline
 * @var bool $Typeify
 */

$UUID ??= Common\UUID::ForElementHTML();
$Ratio ??= $Element->Ratio;
$VideoURL ??= $Element->VideoURL;
$Overlay ??= $Element->Overlay ?? '';
$Title ??= $Element->Title ?? '';
$Subline ??= $Element->Subline ?? '';
$Typeify ??= $Element->Typeify;

$SizeTitle ??= $Element->SizeTitle;
$SizeSubline ??= $Element->SizeSubline;
$Presize ??= $Element->Presize;
$Justify ??= $Element->Justify;

?>

<div id="<?php $Util->Print($UUID) ?>" class="ratiobox <?php $Util->Print($Ratio) ?>">
	<video class="position-absolutely" style="object-fit:cover;" muted autoplay loop playsinline>
		<source src="<?php $Util->Print($VideoURL) ?>" type="video/mp4" />
	</video>
	<div class="position-absolutely <?php $Util->Print($Overlay) ?>"></div>
	<div class="position-absolutely">
		<div class="container h-100">
			<div class="row h-100 <?php $Util->Print($Justify) ?> align-items-center">
				<div class="col-auto">
					<?php if($Typeify): ?>
						<?php if($Title): ?>
						<div class="<?php $Util->Print($SizeTitle) ?> line-height-normal fw-bold" data-typeify="true" data-title="<?php $Util->Print($Title) ?>">
							<?php if(!$Typeify) $Util->Print($Title) ?>
						</div>
						<?php endif; ?>
						<?php if($Subline): ?>
						<div class="<?php $Util->Print($SizeSubline) ?> line-height-normal fw-light" data-typeify="true" data-title="<?php $Util->Print($Subline) ?>">
							<?php if(!$Typeify) $Util->Print($Subline) ?>
						</div>
						<?php endif; ?>
						<?php if($Presize): ?>
						<div class="<?php $Util->Print($SizeTitle) ?> line-height-normal fw-bold" style="height:0px;overflow:hidden;opacity:0.0;"><?php $Util->Print($Title) ?></div>
						<div class="<?php $Util->Print($SizeSubline) ?> line-height-normal fw-light" style="height:0px;overflow:hidden;opacity:0.0;"><?php $Util->Print($Subline) ?></div>
						<?php endif; ?>
					<?php else: ?>
						<?php if($Title): ?>
						<div class="<?php $Util->Print($SizeTitle) ?> line-height-normal fw-bold">
							<?php $Util->Print($Title) ?>
						</div>
						<?php endif; ?>
						<?php if($Subline): ?>
						<div class="<?php $Util->Print($SizeSubline) ?> line-height-normal fw-light">
							<?php $Util->Print($Subline) ?>
						</div>
						<?php endif; ?>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
</div>

<?php if($Typeify): ?>
<script type="module">
import Typeify from '/share/nui/util/typeify.js?v=<?php $Util->CacheBuster() ?>';

jQuery(()=> new Typeify({
	selector: '#<?php $Util->Print($UUID) ?>',
	autorun: 100,
	cursor: '_',
	cursorKeep: true
}));

</script>
<?php endif; ?>
