<?php

/**
 * @var Nether\Atlantis\Struct\TemplateHelper $Util
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Atlantis\UI\Dropdown $Element
 */

//Nether\Common\Dump::Var($Element, TRUE);

?>

<div class="dropdown">
	<button class="btn <?php $Util->Print($Element->MenuBtnStyleClass) ?> dropdown-toggle" type="button" data-bs-toggle="dropdown">
		<?php if($Element->Menu->Icon): ?><i class="<?php $Util->Print($Element->Menu->Icon) ?> m-0 p-0 mr-1"></i>
		<?php endif; ?>
		<?php if($Element->Menu->Title): ?><?php $Util->Print($Element->Menu->Title) ?>
		<?php endif; ?>
		<?php if(!$Element->Menu->Title && !$Element->Menu->Icon): ?>Menu
		<?php endif; ?>
	</button>

	<div class="dropdown-menu dropdown-menu-end">
		<?php

		foreach($Element->Menu->Items as $Key => $Item) {
			/** @var Nether\Atlantis\Struct\DropdownItem $Item */

			if($Item->Title === '-')
			$Surface->Area(
				'elements/dropdown/item-hr',
				[ 'Element'=> $Element, 'Key'=> $Key, 'Item'=> $Item ]
			);

			elseif($Item->Title === '~')
			$Surface->Area(
				'elements/dropdown/item-space',
				[ 'Element'=> $Element, 'Key'=> $Key, 'Item'=> $Item ]
			);

			elseif(str_starts_with($Item->Title, '# '))
			$Surface->Area(
				'elements/dropdown/item-title',
				[ 'Element'=> $Element, 'Key'=> $Key, 'Item'=> $Item ]
			);

			else
			$Surface->Area(
				'elements/dropdown/item-button',
				[ 'Element'=> $Element, 'Key'=> $Key, 'Item'=> $Item ]
			);
		}

		?>
	</div>

</div>