<?php

use Nether\Common;
use Nether\User;
use Nether\Database;

/**
 * @var User\Entity $User - the currently logged in user
 * @var User\Entity $Who - the user being inspected.
 * @var Database\Struct\PrototypeFindResult $AccessTypes
 */

$Surface->Area('admin/breadcrumbs', [ 'Trail' => [
	'Users'               => '/ops/users/list',
	"User ID: {$Who->ID}" => NULL
]]);

?>

<div class="row mb-4">

	<!-- LEFT SIDEBAR -->
	<div class="col-2">

		<!-- USER PICTURE -->
		<div class="ratiobox square mb-4">
			<div class="position-absolutely bg-black rounded">
				<span class="position-absolute position-v-center position-h-center text-decoration-none">
					<i class="mdi mdi-fw mdi-account font-size-largerer text-white opacity-20"></i>
				</span>
			</div>
		</div>

		<!-- ACCOUNT CREATED -->
		<div class="text-primary font-size-smaller fw-bold text-uppercase">Joined:</div>
		<div class="mb-0"><?php $Printer($Who->DateCreated) ?></div>
		<div class="mb-0"><?php $Printer(($Who->DateCreated)(Common\Values::DateFormatT12Z)) ?></div>
		<div class="opacity-50 font-size-smaller mb-4"><?php $Printer(Common\Units\Timeframe::CalcSuffixedString($Who->TimeCreated, Precision: 2)) ?></div>

		<!-- ACCOUNT LAST SEEN -->
		<div class="text-primary font-size-smaller fw-bold text-uppercase">Last Seen:</div>
		<div class="mb-4"><?php $Printer(Common\Units\Timeframe::CalcSuffixedString($Who->TimeSeen)) ?></div>

		<?php if($Who->TimeBanned !== 0): ?>
		<!-- ACCOUNT BAN STATUS -->
		<div class="text-danger font-size-smaller fw-bold text-uppercase">Banned:</div>
		<div class="mb-4"><?php $Printer(Common\Units\Timeframe::CalcSuffixedString($Who->TimeBanned)) ?></div>
		<?php endif; ?>

		<!-- ACCOUNT REMOTE ADDR -->
		<div class="text-primary font-size-smaller fw-bold text-uppercase">Remote Addr:</div>
		<div class="font-family-monotype mb-4"><?php $Printer($Who->RemoteAddr) ?></div>

		<!-- COMMAND BUTTONS -->
		<div class="mb-4">
			<div class="mb-2">
				<?php if($Who->TimeBanned === 0): ?><button class="btn btn-block btn-primary CmdUserBan" data-user-id="<?php $Printer($Who->ID) ?>"><i class="mdi mdi-fw mdi-ban"></i> Ban</button>
				<?php else: ?><button class="btn btn-block btn-danger CmdUserUnban" data-user-id="<?php $Printer($Who->ID) ?>"><i class="mdi mdi-fw mdi-ban"></i> Unban</button>
				<?php endif; ?>
			</div>
		</div>

	</div>

	<!-- RIGHT AREA -->
	<div class="col">

		<div class="font-size-smaller fw-bold text-uppercase">Email</div>
		<form id="UserEmail" class="UserPatchForm" method="post">
			<div class="row tight mb-4">
				<div class="col">
					<input type="hidden" name="ID" value="<?php $Printer($Who->ID) ?>" />
					<input type="text" name="Email" value="<?php $Printer($Who->Email) ?>" class="form-control" />
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary FancyStateButton">
						<i class="mdi mdi-fw mdi-content-save Idle"></i>
						<span>Save</span>
						<i class="mdi mdi-fw mdi-check Success"></i>
						<i class="mdi mdi-fw mdi-close Error"></i>
					</button>
				</div>
			</div>
		</form>

		<div class="font-size-smaller fw-bold text-uppercase">Alias</div>
		<form id="UserAlias" class="UserPatchForm" method="post">
			<div class="row tight mb-4">
				<div class="col">
					<input type="hidden" name="ID" value="<?php $Printer($Who->ID) ?>" />
					<input type="text" name="Alias" value="<?php $Printer($Who->Alias) ?>" class="form-control" />
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary FancyStateButton"><i class="mdi mdi-content-save Idle"></i><span>Save</span><i class="mdi mdi-check Success"></i><i class="mdi mdi-close Error"></i></button>
				</div>
			</div>
		</form>

	</div>

</div>

<!-- USER ACCESS PANEL -->
<dl class="PrettyModernBox">
	<dt class="mb-4">
		<span>User Access</span>
		<hr class="opacity-10" />
	</dt>
	<dd class="mb-4">
		<form id="AccessForm" method="post">
			<div class="row tight">
				<div class="col">
					<div class="fw-bold">Key:</div>
					<input type="text" name="Key" class="form-control" list="AccessTypeDatalist" />
					<datalist id="AccessTypeDatalist">
						<?php foreach($DefinedAccessTypes as $Access): ?>
						<option value="<?php $Printer($Access->Key) ?>"><?php $Printer($Access->Key) ?></option>
						<?php endforeach; unset($Access); ?>
					</datalist>
				</div>
				<div class="col">
					<div class="fw-bold">Value:</div>
					<input type="text" name="Value" class="form-control" />
				</div>
				<div class="col-auto">
					<div class="fw-bold">&nbsp;</div>
					<input type="hidden" name="ID" value="<?php $Printer($Who->ID) ?>" />
					<button type="submit" class="btn btn-primary"><i class="mdi mdi-fw mdi-plus"></i></button>
				</div>
			</div>
		</form>
	</dd>
	<dd class="HideTheLastHR">
		<?php foreach($AccessTypes as $Access): /** @var Nether\User\EntityAccessType $Access */ ?>
		<div class="row align-items-center">
			<div class="col"><code><?php $Printer($Access->Key) ?></code></div>
			<div class="col-auto"><code><?php $Printer($Access->Value) ?></code></div>
			<div class="col-auto">
				<button class="btn btn-danger CmdAccessDelete" data-access-id="<?php $Printer($Access->ID) ?>"><i class="mdi mdi-fw mdi-close"></i></button>
			</div>
		</div>
		<hr class="opacity-10" />
		<?php endforeach; unset($Access); ?>
		<?php if(!$AccessTypes->Count()): ?>
		<div class="text-center fst-italic">This user currently has no extra access data.</div>
		<?php endif; ?>
	</dd>
</dl>

<script type="module">
import NUI from '/share/nui/nui.js?v=<?php $Printer($CacheBuster) ?>';

jQuery(function(){

	jQuery('#AccessForm')
	.on('submit', function(){

		let form = new NUI.Form(this);
		let req = new NUI.Request('SETACCESS', '/api/user/entity');

		(req.send(form.getData()))
		.then(req.goto)
		.catch(req.catch);

		return false;
	});

	jQuery('.CmdAccessDelete')
	.on('click', function(){

		let req = new NUI.Request('DELACCESS', '/api/user/entity');
		let data = NUI.Form.ObjectArrayToDataString([
			{ name: 'AccessID', value: jQuery(this).attr('data-access-id') }
		]);

		(req.send(data))
		.then(req.goto)
		.catch(req.catch);

		return false;
	});

	jQuery('.CmdUserBan')
	.on('click', function(){

		let data = NUI.Form.ObjectArrayToDataString([
			{ name: "ID", value: jQuery(this).attr('data-user-id') },
			{ name: "Reason", value: '' }
		]);

		let req = new NUI.Request('BAN', '/api/user/entity');

		(req.send(data))
		.then(req.goto)
		.catch(req.catch);

		return;
	});

	jQuery('.CmdUserUnban')
	.on('click', function(){

		let data = NUI.Form.ObjectArrayToDataString([
			{ name: "ID", value: jQuery(this).attr('data-user-id') }
		]);

		let req = new NUI.Request('UNBAN', '/api/user/entity');

		(req.send(data))
		.then(req.goto)
		.catch(req.catch);

		return;
	});

	jQuery('.UserPatchForm')
	.on('submit', function(){

		let form = new NUI.Form(this);
		let req = new NUI.Request('PATCH', '/api/user/entity');
		let btn = form.element.find('button[type=submit]');

		(req.send(form.getData()))
		.then(function(result) {

			btn
			.removeClass('btn-primary')
			.addClass('btn-success');

			setTimeout(
				function(){
					btn
					.removeClass('btn-success')
					.addClass('btn-primary');

					return;
				},
				1000
			);

			return;
		})
		.then(req.goto)
		.catch(req.catch);

		return false;
	});

	return;
});

</script>
