<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

use Nether\Atlantis\User\AccessTypeDef;
use Nether\User\EntityAccessType;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var User\EntitySession $User - the currently logged in user
 * @var User\EntitySession $Who - the user being inspected.
 * @var Database\ResultSet $Access - the Access Types for $Who
 * @var Atlantis\User\AccessTypeList $DefinedAccessTypes;
 * @var Common\Datastore $AuthList;
 */

################################################################################
################################################################################

$Trail = [
	'Users'     => '/ops/users',
	$Who->Email => sprintf('/ops/users/%d', $Who->ID)
];

$Breadcrumbs = (fn()=> $Surface->GetArea('admin/breadcrumbs', [
	'Trail' => $Trail
]));

$GetAccessTypeIcon = (function(Atlantis\User\AccessTypeDef $D) {

	if(str_starts_with($D->Key, 'Atlantis.Priv'))
	return 'mdi-key';

	return 'mdi-plus o-25';
});

$DefinedAccessTypes->Sort(
	fn(Atlantis\User\AccessTypeDef $A, Atlantis\User\AccessTypeDef $B)
	=> ($A->Key <=> $B->Key)
);

################################################################################
############################################################################# ?>

<style type="text/css">
.access-type-item:hover {
	cursor: pointer;
	background: color-mix(in srgb, var(--theme-primary) 50%, #00000000);
}
</style>

<div class="container">

	<?php echo $Breadcrumbs(); ?>

	<div id="UserInfoForm">

		<!-- USER HEADER -->
		<div class="row align-items-center mb-4">
			<div class="col-2">
				<div class="ratiobox wallpapered sqwuare rounded">
					<div class="pos-absolute pos-h-center pos-v-center fs-mostest-large o-25">
						<i class="mdi mdi-account"></i>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="fs-larger fw-bold">
					<?php $Util->Print($Who->Email) ?>
				</div>
				<hr class="mt-1 mb-2" />
				<div>
					<div class="row align-items-center g-2 mb-2">
						<div class="col-auto tt-upper fw-bold">Login via:</div>
						<?php if($AuthList->Get('Apple')): ?>
						<div class="col-auto"><i data-bs-toggle="tooltip" class="si si-apple" title="Apple"></i></div>
						<?php endif; ?>
						<?php if($AuthList->Get('Discord')): ?>
						<div class="col-auto"><i data-bs-toggle="tooltip" class="si si-discord" title="Discord"></i></div>
						<?php endif; ?>
						<?php if($AuthList->Get('Github')): ?>
						<div class="col-auto"><i data-bs-toggle="tooltip" class="si si-github" title="Github"></i></div>
						<?php endif; ?>
						<?php if($AuthList->Get('Google')): ?>
						<div class="col-auto"><i data-bs-toggle="tooltip" class="si si-google" title="Google"></i></div>
						<?php endif; ?>
						<?php if($AuthList->Get('Password')): ?>
						<div class="col-auto"><i data-bs-toggle="tooltip" class="mdi mdi-keyboard" title="Username/Password"></i></div>
						<?php endif; ?>
					</div>
					<div class="ff-mono">
						<?php if($Who->Alias): ?>
						<i data-bs-toggle="tooltip" title="User Alias (Set)" class="mdi mdi-account"></i>
						<?php else: ?>
						<i data-bs-toggle="tooltip" title="User Alias (Auto)" class="mdi mdi-account-outline"></i>
						<?php endif; ?>
						<?php $Util->Print($Who->GetAlias()) ?>
					</div>
					<div class="ff-mono">
						<i data-bs-toggle="tooltip" title="Date Created" class="mdi mdi-clock-plus"></i>
						<?php $Util->Print($Who->DateCreated->Get()) ?>
						(<?php $Util->Print($Who->GetSinceCreated()) ?>)
					</div>
					<?php if($Who->HasBeenSeen()): ?>
					<div class="ff-mono">
						<i data-bs-toggle="tooltip" title="Date Last Seen" class="mdi mdi-clock-check"></i>
						<?php $Util->Print($Who->DateSeen->Get()) ?>
						(<?php $Util->Print($Who->GetSinceSeen()) ?>)
					</div>
					<?php endif; ?>
					<?php if($Who->IsBanned()): ?>
					<div class="ff-mono">
						<i data-bs-toggle="tooltip" title="Date Banned" class="mdi mdi-clock-remove"></i>
						<?php $Util->Print($Who->DateBanned->Get()) ?>
						(<?php $Util->Print($Who->GetSinceBanned()) ?>)
					</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<!-- ACCESS TYPES -->
		<div class="glassbox rounded p-4 mb-4">

			<div class="row align-items-center">
				<div class="col-12">
					<span class="fw-bold tt-upper">Access Types</span>
				</div>
			</div>
			<hr class="mb-4" />

			<!-- USER PRIV TABLE -->
			<div id="UserAccessTypes" class="row align-items-center">
				<?php foreach($Access as $A): /** @var EntityAccessType $A */ ?>
				<div class="col ff-mono">
					<?php $Util->Print($A->Key) ?>
				</div>
				<div class="col ff-mono ta-center">
					<?php $Util->Print($A->Value) ?>
				</div>
				<div class="col-auto">
					<button type="button" class="btn btn-outline-light" data-user-priv-delete data-access-id="<?php $Util->Print($A->ID) ?>">
						<i class="mdi mdi-delete mr-0"></i>
					</button>
				</div>
				<div class="col-12">
					<hr />
				</div>
				<?php endforeach; ?>

				<?php if($Access->Count() === 0): ?>
				<div class="col-12 ta-center fst-italic o-50">
					No items to display.
					<hr class="my-4" />
				</div>
				<?php endif; ?>
			</div>

			<!-- ACCESS TYPE SHORTCUTS -->
			<div class="mb-4">
				<div class="atl-collapser">
					<header>
						<div>
							Access Types
						</div>
						<span class="Indicator"><i class="mdi mdi-plus-thick"></i></span>
					</header>
					<section class="p-0 border-0">

						<?php foreach($DefinedAccessTypes as $DAT): /** @var Atlantis\User\AccessTypeDef $DAT */ ?>
						<div class="access-type-item p-3" data-form-fill-access-type>
							<div class="row align-items-center g-2">
								<div class="col-auto">
									<div class="ratiobox square bg-grey-dk" style="width:48px;">
										<div class="pos-absolute pos-h-center pos-v-center">
											<i class="mdi <?php $Util->Print($GetAccessTypeIcon($DAT)) ?>"></i>
										</div>
									</div>
								</div>
								<div class="col">
									<dl class="p-0 m-0">
										<dt class="m-0 tt-normal ff-mono fw-bold fs-large">
											<span data-access-type-key><?php $Util->Print($DAT->Key) ?></span>
										</dt>
										<dd class="m-0 tt-normal fw-light fs-small o-50">
											<span data-access-type-info><?php $Util->Print($DAT->Info) ?></span>
										</dd>
									</dl>
								</div>
								<div class="col-auto ff-mono fw-bold fs-larger">
									<span data-access-type-value><?php $Util->Print($DAT->Value) ?></span>
								</div>
							</div>
						</div>
						<hr class="my-0" />
						<?php endforeach; ?>

					</section>
				</div>
			</div>

			<!-- ACCESS GRANT FORM -->
			<form method="post" data-user-priv-grant-form <?php echo $Who->GetDataAttrForHTML() ?>>
			<div id="UserAccessNew" class="row">
				<div class="col">
					<input name="PrivKey" type="text" class="form-control ff-mono" data-form-fill-access-type-key />
				</div>
				<div class="col">
					<input name="PrivVal" type="text" class="form-control ff-mono" data-form-fill-access-type-value />
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-outline-light">
						<i class="mdi mdi-plus-thick mr-0"></i>
					</button>
				</div>
			</div>
			</form>

		</div>

		<!-- MISC ADMIN -->
		<div class="glassbox rounded p-4">
			<div class="row justify-content-center align-items-center g-4">
				<div class="col-12 col-md-4">
					<button class="btn btn-block btn-outline-danger fs-larger rounded-less" data-user-delete data-goto="/ops/users" <?php echo $Who->GetDataAttrForHTML(); ?>>
						<i class="mdi mdi-delete"></i>
						Delete
					</button>
				</div>
			</div>
		</div>

	</div>

	<div class="mb-6">
	</div>

</div>

<script type="module">
import UserEntityUtil from '/share/atlantis/js/util-user-entity.js';

function BindAccessTypeShortcuts() {

	jQuery('[data-form-fill-access-type]')
	.on('click', function() {

		let that = jQuery(this);
		let key = that.find('[data-access-type-key]').text();
		let val = that.find('[data-access-type-value]').text();
		let nfo = that.find('[data-access-type-info]').text();

		jQuery('[data-form-fill-access-type-key]').val(key);
		jQuery('[data-form-fill-access-type-value]').val(val).focus();
		console.log(`${key} = ${val} // ${nfo}`);

		return;
	});

};

jQuery(function() {

	BindAccessTypeShortcuts();

	UserEntityUtil.WhenDocumentReady();

	return;
});
</script>
