<?php ##########################################################################
################################################################################

use Nether\Atlantis;

################################################################################
################################################################################

$Filename = sprintf('%s/surface-design-php.txt', dirname(__FILE__));
$Content = file_get_contents($Filename);

echo Atlantis\UI\AceEditor::FromSurfaceWith($Surface, [
	'Lang'    => 'php',
	'Content' => $Content
]);
