<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\Media\VideoThirdParty $Video
 */

$AdminMenu = NULL;

if($Route->IsUserAdmin())
$AdminMenu = (
	Atlantis\Struct\DropdownMenu::New()
	->ItemNew('Edit Title', 'mdi-pencil', Attr: [ 'data-abuser-cmd'=> 'name' ])
	->ItemNew('Edit Tags', 'mdi-pencil', Attr: [ 'data-abuser-cmd'=> 'tags' ])
	->ItemNew('Edit Description', 'mdi-pencil', Attr: [ 'data-abuser-cmd'=> 'details' ])
	->ItemNew('Disable Video', 'mdi-eye-off', Attr: [ 'data-abuser-cmd'=> 'disable' ], If: $Video->Enabled)
	->ItemNew('Enable Video', 'mdi-eye', Attr: [ 'data-abuser-cmd'=> 'enable' ], If: !$Video->Enabled)
);

?>

<div class="row align-items-center">

	<div class="col">
		<h2 class="fw-bold mb-0">
			Video:
			<?php $Util->Print($Video->Title) ?>
		</h2>
	</div>

	<?php if($Route->IsUserAdmin()): ?>
	<div class="col-auto">
		<?php $Surface->Area('widgets/dropdown', [ 'Menu'=> $AdminMenu ]) ?>
	</div>
	<?php endif; ?>

</div>
<hr class="mt-0 mb-4" />

<div class="ratiobox widescreen bg-dark rounded">

</div>


