<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\Media\VideoThirdParty $Video
 */

$AdminMenu = NULL;

if($Route->IsUserAdmin())
$AdminMenu = (
	Atlantis\Struct\DropdownMenu::New()
	->ItemNew('Edit Video Info', 'mdi-pencil', Attr: [ 'data-videotp-cmd'=> 'edit', 'data-id'=> $Video->ID, 'data-uuid'=> $Video->UUID ])
	->ItemNew('Edit Description', 'mdi-pencil', Attr: [ 'data-videotp-cmd'=> 'details', 'data-id'=> $Video->ID, 'data-uuid'=> $Video->UUID ])
	->ItemNew('Edit Tags', 'mdi-pencil', Attr: [ 'data-videotp-cmd'=> 'tags', 'data-id'=> $Video->ID, 'data-uuid'=> $Video->UUID ])
	->ItemNew('Disable Video', 'mdi-eye-off', Attr: [ 'data-videotp-cmd'=> 'disable', 'data-id'=> $Video->ID, 'data-uuid'=> $Video->UUID ], If: $Video->Enabled)
	->ItemNew('Enable Video', 'mdi-eye', Attr: [ 'data-videotp-cmd'=> 'enable', 'data-id'=> $Video->ID, 'data-uuid'=> $Video->UUID ], If: !$Video->Enabled)
	->ItemNew('-')
	->ItemNew('Delete Video', 'mdi-trash-can', Attr: [ 'data-videotp-cmd'=> 'delete', 'data-id'=> $Video->ID, 'data-uuid'=> $Video->UUID ] )
);

?>

<hr
id="VideoEntityInfo" class="d-none"
data-id="<?php $Util->Print($Video->ID) ?>"
data-uuid="<?php $Util->Print($Video->UUID) ?>"
/>

<div class="row align-items-center mb-2">
	<div class="col">
		<h2 class="fw-bold lh-1 mb-0">
			Video:
			<?php $Util->Print($Video->Title) ?>
		</h2>
	</div>
	<?php if($Route->IsUserAdmin()): ?>
	<div class="col-auto">
		<?php $Surface->Area('widgets/dropdown', [ 'Menu'=> $AdminMenu ]) ?>
	</div>
	<?php endif; ?>
</div>

<div class="mb-2">
	<span class="fw-bold text-uppercase">Date Posted:</span>
	<?php $Util->Print($Video->DatePosted->Get( Common\Values::DateFormatFancyDate )) ?>
</div>

<div class="mb-2">
	<?php $Surface->Area('tag/buttons', [ 'Tags'=> $Tags ]) ?>
</div>

<div class="ratiobox widescreen bg-dark text-light rounded mb-6">
	<div class="position-absolute position-v-center position-h-center">
		<i class="mdi mdi-loading mdi-spin font-size-most-large"></i>
	</div>
	<div class="position-absolutely">
		<?php echo $Video->GetPlayerHTML($Surface) ?>
	</div>
</div>

<div class="mb-4">
	<h2 class="text-uppercase">Description</h2>
	<hr class="mt-2 mb-4" />

	<div id="VideoDetails"><?php if($Video->Details): ?><?php echo $Video->Details ?><?php endif; ?></div>
	<?php if(!$Video->Details): ?>
	<div class="fst-italic">No additional information has been addded.</div>
	<?php endif; ?>
</div>
