<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\Routes\User\UserSessionWeb $Route
 * @var Local\FAQ\Group $Group
 * @var Local\FAQ\Entity $Entity
 */

################################################################################
################################################################################

$Surface->Area('dashboard/__header', [
	'Trail' => [
		Atlantis\Struct\Item::New(Title: 'Page Elements', URL: '/dashboard/pgel'),
		Atlantis\Struct\Item::New(Title: 'Delete Element')
	]
]);

?>

<div class="atl-page-dashboard container mb-6">
	<div class="jumbotron jumbotron-theme p-3 hr-hide-last mb-4">

		<form id="SubmitPgEl" method="post">
			<div class="row align-items-center">
				<div class="col-12 mb-4">
					<div class="fw-bold ta-center">Are you sure you want to delete this element?</div>
					<div class="fw-bold ta-center tc-red">This cannot be undone.</div>
				</div>
				<div class="col-12 mb-4">
					<hr />
					<h4>Title: <?php $Util->Print($Entity->GetTitle() ?: 'Untitled Element') ?></h4>
					<div>
						<div class="fw-bold mb-2">Content:</div>
						<?php echo $Entity->CData ?>
					</div>
					<hr />
				</div>
				<div class="col-12 ta-center">
					<input type="hidden" name="ID" value="<?php $Util->Print($Entity->ID) ?>" />
					<input type="hidden" name="Type" value="plain" />
					<div class="row justify-content-center g-4">
						<div class="col-auto">
							<a href="/dashboard/pgel" class="btn btn-secondary fs-large">
								Cancel
							</a>
						</div>
						<div class="col-auto">
							<button type="submit" class="btn btn-primary fs-large">
								<i class="mdi mdi-trash-can-outline"></i>
								Delete
							</button>
						</div>
					</div>
				</div>
			</div>
		</form>

	</div>
</div>

<script type="module">
import PageElement from '/share/local/js/pgel.js';

jQuery(function() {

	let pg = new PageElement;
	pg.mode = 'DELETE';

	return;
});
</script>

