<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

use Nether\Atlantis\Plugin\Interfaces\Dashboard\InfoWidgetInterface;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Routes\PageAdmin $Route
 * @var Local\Page\Element $Element
 */

################################################################################
################################################################################

$Surface->Area('dashboard/__header', [
	'Trail' => [
		Atlantis\Struct\Item::New(Title: 'Page Elements', URL: '/dashboard/pgel'),
		Atlantis\Struct\Item::New(Title: 'Edit Element')
	]
]);

$CType = 'squire';

?>

<div class="atl-page-dashboard container mb-6">


	<form id="SubmitPgEl" method="post">
		<div class="row align-items-center">

			<div class="col-12 mb-4">
				<div class="mb-4">
					<div class="tt-upper fw-bold mb-2">Title:</div>
					<input type="text" name="Title" class="form-control" value="<?php $Util->Print($Element->GetTitle()) ?>" />
				</div>
				<div>
					<div class="tt-upper fw-bold mb-2">Content:</div>

					<?php if($CType === Local\Page\Element::CTypeSquire): ?>
					<div id="Editor1" class="Editor d-none"><?php echo $Element->CData ?></div>
					<?php endif; ?>

				</div>
			</div>

			<div class="col-12 ta-center">
				<input type="hidden" name="ID" value="<?php $Util->Print($Element->ID) ?>" />
				<input type="hidden" name="Type" value="<?php $Util->Print($Element->CType) ?>" />
				<button type="submit" class="btn btn-primary fs-large">
					<i class="mdi mdi-content-save"></i>
					Save
				</button>
			</div>

		</div>
	</form>

</div>

<script type="module">
import API from '/share/nui/api/json.js';
import Editor from '/share/nui/modules/editor/editor.js';
import PageElement from '/share/local/js/pgel.js';

jQuery(function() {

	let editobj = jQuery('#Editor1');
	let editapi = new Editor('#Editor1');
	let pgel = new PageElement;

	editobj.data('editor', editapi);
	pgel.mode = 'PATCH';
	pgel.inEditor = editapi;

	return;
});
</script>

