<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Database\ResultSet $Elements
 */

$Surface->Area('dashboard/__header', [
	'Trail' => [
		Atlantis\Struct\Item::New(Title: 'Page Elements', URL: '/dashboard/pgel')
	]
]);

?>

<div class="container mb-6">
	<div class="pt-6 pb-6">

		<div class="row justify-content-end mb-4">
			<div class="col-auto">
				<a href="/dashboard/pgel/new" class="btn btn-outline-dark">
					<i class="mdi mdi-plus"></i>
					New
				</a>
			</div>
		</div>

		<div class="mb-4">
			<table class="table table-light table-striped rounded">
				<thead>
					<th class="th-grow">Element</th>
					<th class="th-shrink"></th>
				</thead>
				<tbody>
					<?php foreach($Elements as $El): /** @var Local\Page\Element $El */ ?>
					<tr>
						<td>
							<div><a href="<?php $Util->Print($El->GetEditURL()) ?>"><?php $Util->Print($El->GetTitle()) ?></a></div>
						</td>
						<td>
							<div class="row g-2 flex-nowrap">
								<div class="col-auto">
									<div class="dropdown">
										<button class="px-3 btn btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
											Menu
										</button>
										<ul class="dropdown-menu">

											<?php if($El->IsLocked()): ?>
											<li>
												<span class="dropdown-item">
													<i class="mdi mdi-lock mr-1"></i>
													Editing is Disabled
												</span>
											</li>
											<?php else: ?>
											<li>
												<a href="<?php $Util->Print($El->GetEditURL()) ?>" class="dropdown-item">
													<i class="mdi mdi-pencil mr-1"></i>
													Edit
												</a>
											</li>
											<?php if($El->CanUserDelete($User)): ?>
											<li>
												<a href="<?php $Util->Print($El->GetDeleteURL()) ?>" class="dropdown-item">
													<i class="mdi mdi-delete mr-1"></i>
													Delete
												</a>
											</li>
											<?php endif; ?>
											<?php endif; ?>

											<li><hr class="dropdown-divider" /></li>

											<li>
												<a href="#" class="dropdown-item" data-nui-copy-value="<?php $Util->Print($El->ID) ?>">
													Copy ID<br />
													<span class="ff-mono fw-light fs-smaller o-50"><?php $Util->Print($El->ID) ?></span>
												</a>
											</li>
											<li>
												<a href="#" class="dropdown-item" data-nui-copy-value="<?php $Util->Print($El->UUID) ?>">
													Copy UUID<br />
													<span class="ff-mono fw-light fs-smaller o-50 fade-out-end">
														<?php $Util->Print($El->UUID) ?>
													</span>
												</a>
											</li>

										</ul>
									</div>
								</div>
							</div>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>

		<?php echo Atlantis\UI\Pager::FromSurfaceWithResultSet($Surface, $Elements) ?>

	</div>
</div>