<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore $UserPrivList
 */

################################################################################
################################################################################

$Breadcrumbs = function() use($Surface) {
	return $Surface->GetArea('admin/breadcrumbs', [ 'Trail' => [ ]]);
};

################################################################################
############################################################################# ?>

<div class="container">
	<?php echo $Breadcrumbs() ?>
</div>

<div class="container mb-6">

	<?php if($UserPrivList->IsTrue('CMS')): ?>
	<div class="glassbox rounded p-3 mb-4">
		<div class="row g-2">
			<div class="col-12">
				<div class="fw-bold fs-larger">CMS</div>
				<hr class="my-2" />
			</div>
			<div class="col-12 col-md-4">
				<a href="/ops/profiles" class="btn btn-block btn-outline-light">
					<div class="ta-center fs-most-large"><i class="mdi mdi-note-multiple-outline"></i></div>
					Profiles
				</a>
			</div>
			<div class="col-12 col-md-4">
				<a href="/ops/tags" class="btn btn-block btn-outline-light">
					<div class="ta-center fs-most-large"><i class="mdi mdi-tag-multiple-outline"></i></div>
					Tags
				</a>
			</div>
			<div class="col-12 col-md-4">
				<a href="/ops/deckmgr" class="btn btn-block btn-outline-light">
					<div class="ta-center fs-most-large"><i class="mdi mdi-monitor-screenshot"></i></div>
					Slide Decks
				</a>
			</div>
		</div>
	</div>
	<?php endif; ?>

	<?php if($UserPrivList->IsTrue('System')): ?>
	<div class="glassbox rounded p-3 mb-6">
		<div class="row g-2">
			<div class="col-12">
				<div class="fw-bold fs-larger">System</div>
				<hr class="my-2" />
			</div>
			<div class="col-12 col-md-4">
				<a href="/ops/api" class="btn btn-block btn-outline-light">
					<div class="ta-center fs-most-large"><i class="mdi mdi-api"></i></div>
					API
				</a>
			</div>
			<div class="col-12 col-md-4">
				<a href="/ops/email" class="btn btn-block btn-outline-light">
					<div class="ta-center fs-most-large"><i class="mdi mdi-email-arrow-right-outline"></i></div>
					Email
				</a>
			</div>
			<div class="col-12 col-md-4">
				<a href="/ops/users" class="btn btn-block btn-outline-light">
					<div class="ta-center fs-most-large"><i class="mdi mdi-account-multiple-outline"></i></div>
					Users
				</a>
			</div>
		</div>
	</div>
	<?php endif; ?>

</div>

