<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore $Trail
 * @var Database\ResultSet $Profiles
 */


$Surface
->Area('media/dashboard/scripts', $__SCOPE)
->Area('dashboard/nav', [ 'Trail' => $Trail ]);

?>

<div class="jumbotron rounded p-2 mb-6">
	<form method="get">
		<div class="row align-items-center">
			<div class="col-12 mb-2">
				<input type="text" name="q" class="form-control" placeholder="Search..." value="<?php $Util->Print($Route->Data->Q) ?>" />
			</div>
			<div class="col-12 mb-2">

				<div class="row tight align-items-center">
					<div class="col-auto">
						<select name="sitetag" class="form-select">
							<option value="">Filter By Site...</option>
							<optgroup label="Site Tags">
								<?php foreach($SiteTags as $ST): ?>
								<option value="<?php $Util->Print($ST->Alias) ?>" <?php echo $Util->GetSelectedHTML($SiteTag&&$ST->Alias===$SiteTag->Alias) ?>><?php $Util->Print($ST->Name) ?></option>
								<?php endforeach; ?>
							</optgroup>
						</select>
					</div>
					<div class="col-auto">
						<select name="sort" class="form-select">
							<option value="title-az" <?php $Util->Print($Util->GetSelectedHTML($Route->Data->Sort === 'title-az')) ?>>Sort By Title</option>
							<option value="title-za" <?php $Util->Print($Util->GetSelectedHTML($Route->Data->Sort === 'title-za')) ?>>Sort By Title (Reverse)</option>
						</select>
					</div>
					<div class="col-auto">
						<div class="form-check">
							<label class="form-check-label fw-bold text-uppercase">
								<input type="checkbox" name="untagged" value="1" class="form-check-input" <?php $Util->Print($Util->GetCheckedHTML($Filters['Untagged'] === TRUE)) ?> />
								Untagged Only
							</label>
						</div>
					</div>
				</div>
			</div>
			<div class="col-12"></div>
			<div class="col-auto">
				<button type="submit" class="btn btn-dark">
					<i class="mdi mdi-magnify"></i>
					Search
				</button>
			</div>
			<?php if($Searched): ?>
			<div class="col-auto">
				(<a href="?">Reset</a>)
			</div>
			<?php endif; ?>
		</div>
	</form>
</div>

<div class="row align-items-center">
	<div class="col">
		<span class="fw-bold text-uppercase">
			<?php $Util->Print($Profiles->Total) ?> Profiles Found
		</span>
	</div>
	<div class="col-auto">
		<button class="btn btn-outline-dark btn-block" data-profile-cmd="new">
			<i class="mdi mdi-plus"></i>
			New Profile
		</button>
	</div>
</div>
<hr />

<?php

$Surface
->Area('atlantis/dashboard/profile/list', [ 'Profiles'=> $Profiles ])
->Area('widgets/pager', [ 'Results'=> $Profiles ])

?>