<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Avenue\Router $Router
 * @var Nether\Avenue\Route $Route
 * @var Nether\Surface\Engine $Surface
 */

$LibraryLinks = [
	'Atlantis' => 'https://github.com/netherphp/atlantis',
	'Avenue' => 'https://github.com/netherphp/avenue',
	'Blog' => 'https://github.com/netherphp/blog',
	'Common' => 'https://github.com/netherphp/common',
	'Console' => 'https://github.com/netherphp/console',
	'Database' => 'https://github.com/netherphp/database',
	'Email' => 'https://github.com/netherphp/email',
	'Ki' => 'https://github.com/netherphp/ki',
	'Sensei' => 'https://github.com/netherphp/sensei',
	'Storage' => 'https://github.com/netherphp/storage',
	'Surface' => 'https://github.com/netherphp/surface',
	'User' => 'https://github.com/netherphp/user'
];

?>

<footer class="PageFooter">
	<div class="container">
		<div class="row justify-content-between">
			<div class="col-12 col-md-6 mb-4 mb-lg-0">
				<h4 class="PrettyBrandText">Nether</h4>
				<div class="font-size-smaller">
					A PHP 8 Framework.
				</div>
				<hr />
				<div class="row font-size-smallerer fw-bold text-uppercase letter-space-some PrettyFooterLinkGrid">
					<?php foreach($LibraryLinks as $LinkTitle => $LinkURL): ?>
					<div class="col-auto mb-4">
						<a href="<?php $Printer($LinkURL) ?>" class="d-block text-underline-none fg-tertiary"><?php $Printer($LinkTitle) ?></a>
					</div>
					<?php endforeach; ?>
				</div>
				<div>
					<button class="btn btn-sm pt-1 pb-1 btn-light" data-nui-theme-toggle="--toggle"><i class="mdi mdi-fw mdi-lightbulb-night font-size-larger"></i></button>
					<button class="btn btn-sm pt-1 pb-1 btn-dark" data-nui-theme-toggle="--toggle"><i class="mdi mdi-fw mdi-lightbulb-on font-size-larger"></i></button>
				</div>
			</div>
			<div class="col-12 col-md mb-0 mb-lg-0 text-align-right">
				<div class="text-uppercase opacity-70 font-size-smaller fw-bold mb-2">
					<a class="text-underline-none" href="#" onclick="window.scrollTo({top: 0, behavior: 'smooth'}); return false;">Back To Top 💦</a>
				</div>

				<?php if($App->IsDev()) $Surface->Area('design/footer-dev') ?>

			</div>
		</div>
	</div>
</footer>
