<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Avenue\Router $Router
 * @var Nether\Avenue\Route $Route
 * @var Nether\Surface\Engine $Surface
 */

?>
<footer id="PageFooter">
	<div class="container">
		<div class="row justify-content-between">
			<div class="col-12 col-lg-3 mb-4 mb-lg-0">
				<h4 class="PrettyBrandText">Nether</h4>
				<div class="text-muted font-size-smaller fst-italic">
					A PHP 8 Framework.
				</div>
				<hr class="opacity-25" />
				<div class="row text-muted font-size-smallerer fw-bold text-uppercase letter-space-some PrettyFooterLinkGrid">
					<div class="col-4 mb-4">
						<a href="https://github.com/netherphp/atlantis" class="d-block text-underline-none fg-tertiary">Atlantis</a>
					</div>
					<div class="col-4 mb-4">
						<a href="https://github.com/netherphp/avenue" class="d-block text-underline-none fg-primary">Avenue</a>
					</div>
					<div class="col-4 mb-4">
						<a href="https://github.com/netherphp/console" class="d-block text-underline-none fg-primary">Console</a>
					</div>
					<div class="col-4 mb-4">
						<a href="https://github.com/netherphp/ki" class="d-block text-underline-none fg-primary">Ki</a>
					</div>
					<div class="col-4 mb-4">
						<a href="https://github.com/netherphp/object" class="d-block text-underline-none fg-primary">Object</a>
					</div>
					<div class="col-4 mb-4">
						<a href="https://github.com/netherphp/surface" class="d-block text-underline-none fg-primary">Surface</a>
					</div>
				</div>
			</div>
			<div class="col-12 col-lg mb-0 mb-lg-0 text-align-right">
				<div class="text-uppercase opacity-70 font-size-smaller fw-bold mb-2">
					<a class="text-underline-none" href="#" onclick="window.scrollTo({top: 0, behavior: 'smooth'}); return false;">Back To Top 💦</a>
				</div>
				<?php if($App->IsDev()): ?>
				<div class="white-space-nowrap opacity-40">
					<div><code class="text-white">
						<span class="opacity-70">env[</span> <?php printf('%s (%s)', $App->GetProjectEnvType(), $App->GetProjectEnv()); ?> <span class="opacity-70">]</span>
						<span class="opacity-70">t[</span> <?php printf('%.03fs', (microtime(TRUE) - ProjectTime)); ?> <span class="opacity-70">]</span>
					</code>
					</div>
					<div><code class="text-white"><span class="opacity-70">req[</span> <?php $Printer($Router->Request->Domain) ?> <span class="opacity-70">/</span> <?php $Printer(ltrim($Router->Request->Path, '/')) ?> <span class="opacity-70">]</span></code></div>
					<div><code class="text-white"><span class="opacity-70">rt[</span> <?php $Printer($Route->Handler->Class) ?> <span class="opacity-70">::</span> <?php $Printer($Route->Handler->Method) ?> <span class="opacity-70">]</span></code></div>
				</div>
				<?php endif; ?>
			</div>
		</div>
	</div>
</footer>
