<?php

$SiteMenu = Nether\Atlantis\UI\SiteMenu::FromSurface($Surface);

$ID = $SiteMenu->GetID();
$Selector = $SiteMenu->GetSelectorID();

?>

<div id="<?php $Util->Print($ID) ?>" class="PageMenuStack">

	<?php

	echo Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
		'UUID'    => 'SiteMenuMain',
		'Title'   => 'Main Menu',
		'Content' => 'area:sitemenu-main/index'
	]);

	echo Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
		'UUID'    => 'SiteMenuDocs',
		'Title'   => 'Documentation',
		'Content' => 'area:sitemenu-main/docs'
	]);

	?>

<!--
	<div id="SiteMenuMain" class="offcanvas offcanvas-end offcanvas-glass z-index-high" data-bs-scroll="true" data-bs-backdrop="false">

		<div class="offcanvas-header">
			<h5 class="offcanvas-title">Website</h5>
			<button type="button" data-sitemenu-close="parent" class="btn-close">
			</button>
		</div>

		<div class="offcanvas-body">
			<div class="ratiobox widescreen wallpapered rounded bg-black mt-4 mb-4" style="background-image:url(/themes/default/gfx/bob.jpg);">
				<div class="position-absolutely grad-focus-darker rounded"></div>
				<div class="position-absolute position-h-center position-v-center">
					W U Z Z U P
				</div>
			</div>
			<nav>
				<div>
					<a href="/" class="border-0">Home</a>
				</div>
				<div><hr /></div>
				<a href="/docs" data-sitemenu="SiteMenuDocs">
					<div class="row">
						<div class="col">
							Docs
						</div>
						<div class="col-auto">
							<i class="mdi mdi-chevron-right"></i>
						</div>
					</div>
				</a>

				<div><hr /></div>
				<a href="#" data-sitemenu="SiteMenuSecond">
					<div class="row">
						<div class="col">
							Second Level
						</div>
						<div class="col-auto">
							<i class="mdi mdi-chevron-right"></i>
						</div>
					</div>
				</a>

			</nav>
		</div>
	</div>

	<div id="SiteMenuSecond" data-sitemenu-path="SiteMenuMain" class="offcanvas offcanvas-end offcanvas-glass z-index-high" data-bs-scroll="true" data-bs-backdrop="false">
		<button type="button" data-sitemenu-close="parent" class="btn-close opacity-100 position-absolute position-top position-right m-2"></button>
		<div class="offcanvas-body">
			<strong>Second Level</strong>

			<div><hr /></div>
			<a href="#" data-sitemenu="SiteMenuThird">
				<div class="row">
					<div class="col">
						Third Level
					</div>
					<div class="col-auto">
						<i class="mdi mdi-chevron-right"></i>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div id="SiteMenuThird" data-sitemenu-path="SiteMenuMain/SiteMenuSecond" class="offcanvas offcanvas-end offcanvas-glass z-index-high" data-bs-scroll="true" data-bs-backdrop="false">
		<button type="button" data-sitemenu-close="parent" class="btn-close opacity-100 position-absolute position-top position-right m-2"></button>
		<div class="offcanvas-body">
			<strong>Third Level</strong>

			<div><hr /></div>
			<a href="#" data-sitemenu="SiteMenuMain/SiteMenuThird/SiteMenuSecond">
				<div class="row">
					<div class="col">
						Surprise Reorder
					</div>
					<div class="col-auto">
						<i class="mdi mdi-chevron-right"></i>
					</div>
				</div>
			</a>
		</div>
	</div>

	<div id="SiteMenuDocs" data-sitemenu-path="SiteMenuMain" class="offcanvas offcanvas-end offcanvas-glass z-index-high" data-bs-scroll="true" data-bs-backdrop="false">
		<button type="button" data-sitemenu-close="parent" class="btn-close opacity-100 position-absolute position-top position-right m-2"></button>
		<div class="offcanvas-body">
			totally docs
		</div>
	</div>
-->

</div>

<?php $SiteMenu->PrintJSModule() ?>