<?php

use Nether\Atlantis;
use Nether\Common;

/**
 * @var Atlantis\Engine $App
 */

$ProjectName = $App->Config->Get(Atlantis\Key::ConfProjectName);
$LogoImageURL = $Surface->Get('Theme.Header.Logo.ImageURL');

$Contain = $Surface->Get('Theme.Header.Contain');
$ShowMenuLabel = $Surface->Get('Theme.Header.ShowMenuLabel') ?? TRUE;

?>

<header class="PageHeader">
	<div class="<?php $Util->Print($Contain ? 'container' : 'container-fluid') ?>">
		<div class="row align-items-center justify-content-between">

			<!-- LOGO -->
			<div class="col-auto">
				<a href="/">
					<?php if($LogoImageURL): ?>
					<img src="<?php $Util->Print($LogoImageURL) ?>" class="on-light-invert" style="max-height:20px;" />
					<?php else: ?>
					<span class="fw-bold"><?php $Util->Print($ProjectName) ?></span>
					<?php endif; ?>
				</a>
			</div>

			<!-- SPACER -->
			<div class="col"><hr class="opacity-10" /></div>

			<div class="col-auto">
				<button class="btn btn-dark d-flex align-items-center px-2 py-0 gap-2" data-sitemenu="SiteMenuMain">
					<span>
						<span class="o-70">Menu</span>
					</span>
					<span>
						<i class="mdi mdi-menu fs-largerest mr-0"></i>
					</span>
				</button>
			</div>

		</div>

	</div>
</header>

<?php

echo Nether\Atlantis\UI\SiteMenu::FromSurfaceWith($Surface, [
	'Pages' => [
		Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
			'UUID'    => 'SiteMenuMain',
			'Content' => 'area:sitemenu-main/root'
		]),
		Nether\Atlantis\UI\SiteMenuPage::FromSurfaceWith($Surface, [
			'UUID'    => 'SiteMenuDocs',
			'Content' => 'area:sitemenu-main/docs'
		])
	]
]);

?>
