<?php

use Nether\Atlantis;

/**
 * @var Atlantis\Engine $App
 */

$AllowUserLogin = $App->Config[Atlantis\Library::ConfUserAllowLogin];
$AllowUserSignup = $App->Config[Atlantis\Library::ConfUserAllowSignup];

?>

<?php if($App->User): ?>
<div class="col-auto">
	<a href="/dashboard">
		<?php $Printer($App->User->Alias ?? 'Dashboard') ?>
	</a>
</div>
<div class="col-auto">
	<a href="/logout">
		Log Out
	</a>
</div>
<?php else: ?>
<?php if($AllowUserLogin): ?>
<div class="col-auto">
	<a href="/login">
		Login
	</a>
</div>
<?php endif; ?>
<?php if($AllowUserSignup): ?>
<div class="col-auto">
	<a href="/signup">
		Signup
	</a>
</div>
<?php endif; ?>
<?php endif; ?>