<?php

/**
 * @var Nether\Atlantis\Engine $App
 */

$UserAllowSignup = $App->Config[Nether\Atlantis\Library::ConfUserAllowSignup];

?>

<?php if($App->User): ?>
<div class="col-auto">
	<a href="/dashboard">
		<?php $Printer($App->User->Alias) ?>
	</a>
</div>
<div class="col-auto">
	<a href="/logout">
		Log Out
	</a>
</div>
<?php else: ?>
<div class="col-auto">
	<a href="/login">
		Login
	</a>
</div>
<?php if($UserAllowSignup): ?>
<div class="col-auto">
	<a href="/join">
		Join
	</a>
</div>
<?php endif; ?>
<?php endif; ?>