<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Database\Struct\PrototypeFindResult $BlogUsers
 */

($Surface)
->Set('Page.Title', 'Manage Blogs - Dashboard')
->Area('dashboard/nav', [ 'Trail' => [
	'Blog'           => '/dashboard/blog/list',
	'Manage Blogs'   => '/dashboard/blog/list'
]]);

?>

<?php foreach($BlogUsers as $Blog): /** @var Nether\Blog\BlogUser $Blog */ ?>
<div class="row tight align-items-center mb-4">
	<div class="col-auto">
		<div class="font-size-largerer">
			<?php if($Blog->CanAdmin()): ?>
			<i class="mdi mdi-fw mdi-account-cog"></i>
			<?php elseif($Blog->CanEdit()): ?>
			<i class="mdi mdi-fw mdi-account-wrench"></i>
			<?php elseif($Blog->CanWrite()): ?>
			<i class="mdi mdi-fw mdi-account-edit"></i>
			<?php endif; ?>
		</div>
	</div>
	<div class="col">
		<a href="<?php $Printer($Blog->Blog->GetURL()) ?>"><?php $Printer($Blog->Blog->Title) ?></a>
	</div>
	<div class="col-auto">
		<a href="<?php $Printer($Blog->Blog->GetURL()) ?>" class="btn btn-primary">View</a>
	</div>
	<?php if($Blog->CanWrite()): ?>
	<div class="col-auto">
		<a href="<?php $Printer($Blog->Blog->GetWriteURL()) ?>" class="btn btn-primary">Write</a>
	</div>
	<?php endif; ?>
	<?php if($Blog->CanAdmin()): ?>
	<div class="col-auto">
		<a href="<?php $Printer($Blog->Blog->GetSettingsURL()) ?>" class="btn btn-primary">Settings</a>
	</div>
	<?php endif; ?>
</div>
<hr class="mt-0 mb-4" />
<?php endforeach; ?>

