<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Blog\Blog $Blog
 */

//Nether\Common\Dump::Var($Blog, TRUE);

$Surface
->Set('Page.Title', 'Blog Settings - Dashboard')
->Area('dashboard/nav', [ 'Trail' => [
	'Blog'                      => NULL,
	"Settings ({$Blog->Title})" => NULL
]]);

?>

<form id="BlogSettings" data-blog-id="<?php $Printer($Blog->ID) ?>">

	<div class="mb-4">
		<div class="mb-2">
			<?php $Surface->Area('blog/blog-header', [ 'Blog'=> $Blog, 'CacheBust'=> TRUE ]) ?>
		</div>
		<div class="row tight justify-content-center">
			<div class="col-12 col-md-auto mb-2 mb-md-0"><button id="BlogSettingsUploadIcon" type="button" class="btn btn-block btn-outline-light">Upload Icon</button></div>
			<div class="col-12 col-md-auto mb-0 mb-md-0"><button id="BlogSettingsUploadHeader" type="button" class="btn btn-block btn-outline-light">Upload Header</button></div>
		</div>
	</div>

	<div class="mb-4">
		<div class="fw-bold text-uppercase">Title</div>
		<div>
			<input name="Title" type="text" class="form-control" value="<?php $Printer($Blog->Title) ?>" />
		</div>
	</div>

	<div class="mb-4">
		<div class="fw-bold text-uppercase">Tagline</div>
		<div>
			<input name="Tagline" type="text" class="form-control" value="<?php $Printer($Blog->Tagline) ?>" />
		</div>
	</div>

	<div class="mb-4">
		<div class="fw-bold text-uppercase">About</div>
		<div>
			<textarea name="Details" class="form-control" rows="6"><?php $Printer($Blog->Details) ?></textarea>
		</div>
	</div>

	<div class="mb-4">
		<input type="hidden" name="ID" value="<?php $Printer($Blog->ID) ?>" />
		<button type="submit" class="btn btn-primary">
			<i class="mdi mdi-fw mdi-content-save"></i>
			Save
		</button>
	</div>
</form>

<script type="module">
import API from '/share/nui/api/json.js';
import FormUtil from '/share/nui/util/form.js';
import UploadButton from '/share/nui/modules/uploader/uploader.js';

jQuery(function() {

	let root = jQuery('#BlogSettings');
	let bid = root.attr('data-blog-id');

	new UploadButton('#BlogSettingsUploadHeader', {
		'url': '/api/blog/entity/header',
		'dataset': { 'ID': bid, 'Type': 'bloghead' },
		'onSuccess': ()=> location.reload()
	});

	new UploadButton('#BlogSettingsUploadIcon', {
		'url': '/api/blog/entity/icon',
		'dataset': { 'ID': bid, 'Type': 'blogicon' },
		'onSuccess': ()=> location.reload()
	});

	jQuery('#BlogSettings')
	.on('submit', function() {

		let form = new FormUtil(this);
		let api = new API.Request('PATCH', '/api/blog/entity');

		form.read();

		(api.send(form))
		.then(api.goto)
		.catch(api.catch);

		return false;
	});

	return;
});
</script>
