<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore $Blogs
 * @var Common\Datastore $SiteTags
 * @var Blog\Post $Post
 * @var string $Editor
 */

$Surface
->Set('Page.Title', 'Write Blog Post - Dashboard')
->Area('dashboard/nav', [ 'Trail' => [
	'Blog'   => '/dashboard/blog/list',
	'Editor' => '/dashboard/blog/write'
]])
->Area(
	sprintf('blog/dashboard/editor/%s', $Editor ?? 'index'),
	$__SCOPE
);
