<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Surface\Engine $Surface
 */

$Surface
->Set('Page.Title', 'Start New Blog - Dashboard')
->Area('dashboard/nav', [ 'Trail' => [
	'Blog'           => NULL,
	'Start New Blog' => NULL
]]);

?>

<form id="BlogNewForm" method="post">
	<div class="mb-4">
		<div class="fw-bold">Blog Title:</div>
		<input type="text" name="Title" class="form-control" />
	</div>
	<div class="mb-4">
		<div class="fw-bold">Blog URL Alias:</div>
		<input type="text" name="Alias" class="form-control" />
	</div>
	<div class="mb-4">
		<div class="fw-bold">Tagline:</div>
		<input type="text" name="Tagline" class="form-control" />
	</div>
	<div class="mb-4">
		<div class="fw-bold">Description:</div>
		<textarea name="Details" class="form-control"></textarea>
	</div>
	<div>
		<button type="submit" class="btn btn-primary fw-bold">
			<i class="mdi mdi-fw mdi-plus"></i>
			Create
		</button>
	</div>
</form>

<script type="module">
import API from '/share/nui/api/json.js';
import FormUtil from '/share/nui/util/form.js';

jQuery(function(){

	jQuery('#BlogNewForm')
	.on('submit', function() {

		let form = new FormUtil(this);
		let api = new API.Request('POST', '/api/blog/entity');

		form.read();

		(api.send(form))
		.then(api.goto)
		.catch(api.catch);

		return false;
	});

	return;
});
</script>

