<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Blog\Routes\PostEditorWeb $Route
 * @var Common\Datastore $Blogs
 * @var Common\Datastore $Trail
 */

$Surface->Area('dashboard/__header', [ 'Trail'=> $Trail ]);

?>

<div class="container mb-6">

	<hr class="mt-0 mb-4" />
	<?php foreach($Blogs as $Blog): /** @var Blog\Blog $Blog */ ?>
	<div class="row tight align-items-center">
		<div class="col-2 d-none d-md-block">
			<div class="ratiobox wallpapered widescreen rounded" style="background-image:url(<?php $Util->Print($Blog->GetHeaderURL()) ?>);">
				<a href="<?php $Util->Print($Blog->GetPageURL()) ?>" class="td-none pos-absolutely"></a>
			</div>
		</div>
		<div class="col">
			<a href="<?php $Util->Print($Blog->GetPageURL()) ?>"><?php $Util->Print($Blog->Title) ?></a>
		</div>
		<div class="col-auto">
			<?php

			echo Atlantis\UI\Dropdown::FromSurfaceWithMenu(
				$Surface,
				Atlantis\Struct\DropdownMenu::New(Icon: 'mdi mdi-cog')
				->ItemNew('View', 'mdi mdi-open-in-new', $Blog->GetPageURL())
				->ItemNew('-')
				->ItemNew('Write', 'mdi mdi-pencil', $Blog->GetWriteURL())
				->ItemNew('Settings', 'mdi mdi-cog', $Blog->GetSettingsURL())
				->ItemNew('Users', 'mdi mdi-account-group', $Blog->GetManageUsersURL())
			);

			?>
		</div>
	</div>
	<hr class="mt-4 mb-4" />
	<?php endforeach; ?>
</div>
