<?php

use Nether\Atlantis;
use Nether\Common;

/**
 * @var Routes\Docs $Route
 * @var Common\Datastore $Pages
 */

$Surface->Set([
	'Page.Section.Title' => 'CLI Reference',
	'Page.Title'         => 'Command Line Utilities'
]);

$Pages = Common\Datastore::FromArray([
	'dev.atl'     => '/docs/cli/dev',
	'gfx.atl'     => '/docs/cli/gfx',
	'ssl.atl'     => '/docs/cli/ssl',
	'project.atl' => '/docs/cli/project',
	'web.atl'     => '/docs/cli/web'
]);

?>

<div class="container pb-6">

	<div class="jumbotron rounded hr-hide-last">
		<?php foreach($Pages as $Title => $URL): ?>
		<div class="row align-items-center">
			<div class="col">
				<a href="<?php $Util->Print($URL) ?>"><?php $Util->Print($Title) ?></a>
			</div>
			<div class="col-auto">
				<a class="btn btn-primary" href="<?php $Util->Print($URL) ?>">
					View Docs
					<i class="mdi mdi-chevron-right mr-0"></i>
				</a>
			</div>
		</div>
		<hr class="opacity-20" />
		<?php endforeach; unset($Title, $URL); ?>
	</div>

</div>
