<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Routes\Docs $Route
 * ...
 */

$Heading = $Route->FetchHeading('Command Line Reference');

$Path = dirname($Surface->GetPathToArea('sensei/docs/cli/helps/index'));
$Indexer = Common\Filesystem\Indexer::FromPath($Path);

$Files = $Indexer->ToDatastore();
$Files->Remap(fn(string $Filename)=> preg_replace('/.*?\/helps\/(.*?)\.phtml$/', '\\1', $Filename));
$Files->Sort();

################################################################################
################################################################################

$GetCollapserFor = function(string $Filename) use($Surface): Surface\Element {

	$Content = $Surface->GetArea(sprintf(
		'sensei/docs/cli/helps/%s', $Filename
	));

	$Collapser = Atlantis\UI\Collapser::FromSurfaceWithContent(
		$Surface, $Filename, sprintf('<pre>%s</pre>', $Content)
	);

	return $Collapser;
};

################################################################################
############################################################################# ?>

<div class="cargobay">

	<section>
		<div class="container">
			<?php echo $Heading ?>
			<hr />
			Command line utilities available from the project root.
		</div>
	</section>

	<section>
		<div class="container">
			<h3>Quick Helps</h3>
			<hr />

			<?php foreach($Files as $Filename): ?>
			<div>
				<?php echo $GetCollapserFor($Filename); ?>
			</div>
			<?php endforeach; unset($Filename); ?>
		</div>
	</section>

</div>
