<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Common;

################################################################################
################################################################################

$Surface->Area('sensei/docs/__header', [
	'Title' => 'Command Line Utilities',
	'Trail' => [
		Atlantis\Struct\Item::New(Title: 'CLI')
	]
]);

$Pages = Common\Datastore::FromArray([
	Atlantis\Struct\Item::New(Title: 'project.atl', URL: '/docs/cli/project')
]);

?>

<div class="container pb-6">

	<div class="jumbotron rounded hr-hide-last">
		<?php foreach($Pages as $Page): /** @var Atlantis\Struct\Item $Page */ ?>
		<div class="row align-items-center">
			<div class="col">
				<a href="<?php $Util->Print($Page->GetURL()) ?>"><?php $Util->Print($Page->GetTitle()) ?></a>
			</div>
			<div class="col-auto">
				<a class="btn btn-primary" href="<?php $Util->Print($Page->GetURL()) ?>">
					View Docs
					<i class="mdi mdi-chevron-right mr-0"></i>
				</a>
			</div>
		</div>
		<hr class="opacity-20" />
		<?php endforeach; unset($Title, $URL); ?>
	</div>

</div>
