<?php

$Surface->Set('Page.Title', 'Atlantis From Scratch - Docs');

?>

<div class="container pt-6 pb-6">

	<?php
	$Surface->Area('sensei/breadcrumbs', [
		'Items'=> [
			'Guides'                => NULL,
			'Atlantis From Scratch' => NULL
		]
	])
	?>

	<h1 class="mb-0">Atlantis From Scratch.</h1>
	<div class="row">
		<div class="col-12 col-lg">
			<p class="mb-4">This guide will walk through the process of starting with an empty directory and ending with a working website with SSL. The following assumptions in this guide are just reasonable defaults not requirements. You may need to adjust commands based on your environment.</p>
			<div class="edged-left opacity-75 mb-4">
				<div class="fw-bold">Assumptions:</div>
				<ul>
					<li>Composer for PHP is installed system wide.</li>
					<li>User is setup to be able to use sudo.</li>
					<li>Server is Debian flavoured with Apache 2.4.</li>
					<li>AcmePHP is setup in <code>/opt/ssl</code>.</li>
				</ul>
			</div>
		</div>
		<div class="col-12 col-lg-4">
			<div class="PrettyModernBox">
				<h3>
					<hr />
					<span>Contents</span>
				</h3>
				<div>
					<ul class="list-unstyled">
						<li class="mb-2"><a class="underdot" href="#bootstrap">1) Bootstrap The Project</a></li>
						<li class="mb-2"><a class="underdot" href="#apache">2) Apache Web Server Config</a></li>
						<li class="mb-2"><a class="underdot" href="#acmephp">3) AcmePHP &amp; SSL Cert</a></li>
						<li class="mb-2"><a class="underdot" href="#env">4) Environment Config</a></li>

					</ul>
				</div>
			</div>
		</div>
	</div>

</div>

<!-- SUMMARY -->
<div id="bootstrap" class="bg-alt1">
	<div class="container pt-8 pb-8">
		<h2 class="fw-bold mb-4">Bootstrap The Project.</h2>
		<ul class="mb-0">
			<li class="mb-4">
				<p>Grab the Project template.</p>
				<blockquote class="edged-left">
					<div class="mb-0"><code class="cli">$ git clone netherphp/project</code></div>
					<div class="mb-0"><code class="cli">$ cd project</code></div>
					<div class="mb-0"><code class="cli">$ rm -rf .git</code></div>
				</blockquote>
			</li>
			<li class="mb-4">
				<p>Install Atlantis.</p>
				<blockquote class="edged-left">
					<div class="mb-0"><code class="cli">$ composer require netherphp/atlantis</code></div>
					<div class="mb-0"><code class="cli">$ atlantis init -y</code></div>
				</blockquote>
			</li>
			<li class="mb-0">
				<p>At this stage it is already &quot;working&quot; in that it will serve the app over basic HTTP, and can be tested with PHP's built-in web server.</p>
				<blockquote class="edged-left">
					<div class="mb-2"><code class="cli">$ php -S localhost:80 -t www</code></div>
				</blockquote>
			</li>
		</ul>
	</div>
</div>

<!-- WEB SERVER -->
<div id="apache" class="bg-alt2">
	<div class="container pt-8 pb-8">
		<h2 class="fw-bold mb-4">Apache Web Server Config.</h2>
		<ul class="mb-0">
			<li class="mb-4">
				<p>Edit <code class="file">conf/env/dev/apache24.conf</code> using the HTTP macro for now.</p>
				<blockquote class="edged-left">
					<div class="mb-0">You are looking for the line near the bottom of the file that start with <code>Use HTTP</code>, that is the example to edit.</div>
				</blockquote>
			</li>
			<li class="mb-4">
				<p>Link <code class="file">conf/env/dev/apache24.conf</code> into Apache's config file location:</p>
				<blockquote class="edged-left">
					<div class="mb-2"><code class="cli">$ atlantis webserver-link --sudo</code></div>
				</blockquote>
			</li>
			<li class="mb-2">
				<p>Have Apache rehash its config files.</p>
				<blockquote class="edged-left">
					<div class="mb-2"><code class="cli">$ atlantis webserver-rehash --sudo</code></div>
				</blockquote>
			</li>
			<li class="mb-0">
				<p>Apache should now be serving the project over basic HTTP.</p>
			</li>
		</ul>
	</div>
</div>

<!-- SSL CERT -->
<div id="acmephp" class="bg-alt0">
	<div class="container pt-8 pb-8">
		<h2 class="fw-bold mb-4">SSL Config.</h2>
		<div class="fw-bold mb-4">Configure and Fetch initial certificate.</div>

		<ul class="mb-8">
			<li class="mb-4">
				<p>Edit <code class="file">conf/env/dev/config.php</code> to fill in <code class="file">AcmePHP</code> values.</p>
			</li>
			<li class="mb-4">
				<p>Generate a <code class="file">conf/env/dev/acmephp.yml</code> file using the <code>config.php</code> values.</p>
				<blockquote class="edged-left">
					<div class="mb-2"><code class="cli">$ atlantis acmephp-config</code></div>
				</blockquote>
			</li>
			<li class="mb-4">
				<p>Have AcmePHP get your SSL cert:</p>
				<blockquote class="edged-left">
					<div class="mb-2"><code class="cli">$ atlantis acmephp-run --sudo</code></div>
				</blockquote>
			</li>
			<li class="mb-4">
				<p>Edit <code class="file">conf/env/dev/apache24.conf</code> to use the HTTPS macro instead. Literally change it from <code>HTTP</code> to <code>HTTPS</code> and rehash the configuration.</p>
				<blockquote class="edged-left">
					<div class="mb-2"><code class="cli">$ atlantis webserver-rehash --sudo</code></div>
				</blockquote>
			</li>
			<li class="mb-0">Apache should now be serving the project over both HTTP and HTTPS.</li>
		</ul>

		<div class="fw-bold mb-4">Auto-renew the certificate.</div>
		<ul class="mb-0">
			<li class="mb-0">
				<p>Add an item to cron. This example checks every Monday morning at 4:20am.</p>
				<blockquote class="edged-left">
					<div class="mb-2"><code class="cli">$ crontab -e</code></div>
					<div class="mb-0"><code class="file">20 4 * * 1 /path/to/project/vendor/bin/atlantis acmephp-run --sudo --rehash</code></div>
				</blockquote>
			</li>
		</ul>
	</div>
</div>

<!-- ENV CONF -->
<div id="env" class="bg-alt1">
	<div class="container pt-6 pb-6">
		<h2 class="fw-bold mb-4">Environment Config.</h2>
		<ul class="mb-0">
			<li class="mb-0">
				<p>
					The default environment is called <code>dev</code> with the matching <code class="file">conf/env/dev</code> config directory.
					Choosing an env is done with the contents of the <code class="file">env.lock</code> file in the project root.
					This example will put it in production mode looking for config files in <code class="file">conf/env/prod</code>.
				</p>
				<blockquote class="edged-left">
					<div class="mb-2"><code class="cli">$ atlantis env --set=prod</code></div>
				</blockquote>
			</li>
		</ul>
	</div>
</div>
