
<div class="container pt-6 pb-6">

	<h1>Project Management</h1>

	<p>The <code>project.atl</code> tool helps manage the project manage and check the physical structure as defined by the <code>atlantis.json</code> files of the application.</p>


	<ul>
		<li class="mb-4">
			<div class="fs-larger fw-bold"><code>init</code></div>
			Bootstrap the project with the Atlantis template.
			This is typically only going to be used once and will try to convince you of that upon re-running.
		</li>
		<li class="mb-4">
			<div class="fs-larger fw-bold"><code>setup</code></div>
			Setup, Check, or Fix the project structure.
			This is safe to re-run at any time to check that the project is as it should be. It also should be re-run after making any changes to the project configuration.
		</li>
		<li class="mb-4">
			<div class="fs-larger fw-bold"><code>dirs</code></div>
			Lists and manages directories that Must Exist within the project.
		</li>
		<li class="mb-0">
			<div class="fs-larger fw-bold"><code>symlinks</code></div>
			Lists and manages symlinks that Must Exist within the project.
		</li>
	</ul>

</div>
