<?php

use Nether\Atlantis;
use Nether\Common;

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

$Pages = [
	'Article'     => '/docs/ui/article',
	'Pager'       => '/docs/ui/pager',
	'Promo Video' => '/docs/ui/promo-video',
	'Slider'      => '/docs/ui/slider',
	'Site Menu'   => '/docs/ui/sitemenu'
];

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

?>

<div class="container pt-6 pb-6">

	<div class="jumbotron rounded">
		<div>
			<h3>UI Elements</h3>
		</div>
		<?php foreach($Pages as $Title => $URL): ?>
		<hr class="opacity-20" />
		<div class="row align-items-center">
			<div class="col">
				<a href="<?php $Util->Print($URL) ?>"><?php $Util->Print($Title) ?></a>
			</div>
			<div class="col-auto">
				<a class="btn btn-primary" href="<?php $Util->Print($URL) ?>">
					View Docs
					<i class="mdi mdi-chevron-right mr-0"></i>
				</a>
			</div>
		</div>
		<?php endforeach; unset($Title, $URL); ?>
	</div>

</div>
