<?php

use Nether\Atlantis;
use Nether\Common;

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

$Pages = [
	'AceEditor'   => '/docs/ui/ace-editor',
	'Article'     => '/docs/ui/article',
	'Pager'       => '/docs/ui/pager',
	'Pathbar'     => '/docs/ui/pathbar',
	'Pillbox'     => '/docs/ui/pillbox',
	'Promo Video' => '/docs/ui/promo-video',
	'Slider'      => '/docs/ui/slider',
	'Site Menu'   => '/docs/ui/sitemenu'
];

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

$Surface->Area('sensei/pages/ui/__intro', [
	'Title'   => 'UI Elements'
]);

?>

<div class="container pt-2 pb-6">

	<div class="jumbotron rounded hr-hide-last">
		<?php foreach($Pages as $Title => $URL): ?>
		<div class="row align-items-center">
			<div class="col">
				<a href="<?php $Util->Print($URL) ?>"><?php $Util->Print($Title) ?></a>
			</div>
			<div class="col-auto">
				<a class="btn btn-primary" href="<?php $Util->Print($URL) ?>">
					View Docs
					<i class="mdi mdi-chevron-right mr-0"></i>
				</a>
			</div>
		</div>
		<hr class="opacity-20" />
		<?php endforeach; unset($Title, $URL); ?>
	</div>

</div>
