<div class="jumbotron rounded mb-4">
	<div class="fw-bold text-uppercase">
		Account
	</div>
	<hr class="mt-0 mb-2" />

	<div class="row justify-content-center justify-content-md-start">
		<div class="col-4 col-md-2 mb-4 mb-md-0">
			<div class="ratiobox square wallpapered rounded" style="background-image:url(/share/atlantis/gfx/misc/no-image.png);"></div>
		</div>
		<div class="col-12 col-md mb-4 mb-md-0">
			<div class="mb-2">
				<a href="/dashboard/settings/email" class="btn btn-dark btn-block text-align-left">
					<i class="mdi mdi-email"></i>
					Change Email
				</a>
			</div>
			<div class="mb-2">
				<a href="/dashboard/settings/password" class="btn btn-dark btn-block text-align-left">
					<i class="mdi mdi-key"></i>
					Change Password
				</a>
			</div>
			<?php if(Nether\User\Library::HasAnyThirdPartyAuth()): ?>
			<div class="mb-2">
				<a href="/dashboard/settings/auth" class="btn btn-dark btn-block text-align-left">
					<i class="mdi mdi-account-settings"></i>
					Manage Login Methods
				</a>
			</div>
			<?php endif; ?>
			<div class="mb-0">
				<a href="/logout" class="btn btn-dark btn-block text-align-left">
					<i class="mdi mdi-account-off-outline"></i>
					Log Out
				</a>
			</div>
		</div>
	</div>
</div>