<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Route->Title = 'Article & Content Element';
$Route->Info = 'Provide a Next/Prev pagination widget.';

$Route->Pathbar->Items->Push(Atlantis\Struct\Item::New(
	Title: 'Pager',
	URL: '/docs/ui/pager'
));

$Surface->Area('sensei/docs/__example-via-area', [
	'Areas' => [
		'Manual Setup'
		=> 'sensei/docs/ui/pager/example-basic',

		'Setup via Data Collection'
		=> 'sensei/docs/ui/pager/example-resultset'
	]
]);
