<?php

use Nether\Atlantis;
use Nether\Common;
use Nether\Database;

/**
 * @var Database\ResultSet $Items
 */

$Trail = [
	Atlantis\Struct\Item::New(UUID: 'contact', Title: 'Contact Log', URL: '/dashboard/contact/list')
];

$Surface->Area('dashboard/__header', [ 'Trail'=> $Trail ]);

?>


<div class="container pb-6">
	<?php foreach($Items as $Item): /** @var Atlantis\Struct\ContactEntry $Item */ ?>
	<div class="row align-items-center">
		<div class="col-12 col-md mb-2 mb-md-0">
			<div class="font-size-smallerer mb-1"><a href="<?php $Printer($Item->GetAdminURL()) ?>" class="border-0"><?php $Printer($Item->DateSent->Get(Common\Values::DateFormatFancyDateTime)) ?></a></div>
			<div class="fw-bold"><a href="<?php $Printer($Item->GetAdminURL()) ?>"><?php $Printer($Item->Subject) ?></a></div>
			<div class="fst-italic text-muted"><?php $Printer($Item->GetFromString()) ?></div>
		</div>
		<div class="col-12 col-md-auto mb-2 mb-md-0">
			<a href="<?php $Printer($Item->GetAdminURL()) ?>" class="btn btn-primary btn-block">View Message</a>
		</div>
	</div>
	<hr />
	<?php endforeach; ?>

	<?php if(!$Items || !$Items->Count()): ?>
	<div class="jumbotron rounded p-4 fst-italic">
		No items here yet.
	</div>
	<?php endif; ?>
</div>


