<?php

use Nether\Atlantis;
use Nether\Common;
use Nether\Database;

/**
 * @var Database\Struct\PrototypeFindResult $Items
 */

$Surface
->Set('Page.Title', "Contact Us Message Log")
->Area('dashboard/nav', [ 'Trail' => [
	'Contact Us'
	=> '/dashboard/contact/list'
]]);

?>

<?php foreach($Items as $Item): /** @var Atlantis\Struct\ContactEntry $Item */ ?>
<div class="row align-items-center">
	<div class="col-12 col-md mb-2 mb-md-0">
		<div class="font-size-smallerer mb-1"><a href="/dashboard/contact/view/<?php $Printer($Item->ID) ?>" class="border-0"><?php $Printer($Item->DateSent->Get(Common\Values::DateFormatFancyDateTime)) ?></a></div>
		<div class="fw-bold"><a href="/dashboard/contact/view/<?php $Printer($Item->ID) ?>"><?php $Printer($Item->Subject) ?></a></div>
		<div class="fst-italic text-muted"><?php $Printer($Item->Name) ?> &lt;<?php $Printer($Item->Email) ?>&gt;</div>
	</div>
	<div class="col-12 col-md-auto mb-2 mb-md-0">
		<a href="/dashboard/contact/view/<?php $Printer($Item->ID) ?>" class="btn btn-primary btn-block">View Message</a>
	</div>
</div>
<hr />
<?php endforeach; ?>

