<?php

/**
 * @var Nether\User\Entity $User
 * @var Nether\Atlantis\Page\Entity $Page
 */

?>

<?php echo $Page->GetContent() ?>

<?php if($User && $User->HasAccessTypeOrAdmin( Nether\Atlantis\Key::AccessPageManage )): ?>
<script type="module">
import Page from '/share/atlantis/page.js?v=<?php $Printer($CacheBuster) ?>';
jQuery(function() {
	Page.BindEditCommands();
	return;
});
</script>
<?php endif; ?>
