<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Blog\Post $Post
 */


$Stack = Common\Struct\EditorJS\Content::FromString($Post->Content);

foreach($Stack->Blocks as $Block) {
	/** @var Common\Struct\EditorJS\Block $Block */
	echo $Block;
}
