<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Blog\BlogUser $BlogUser
 * @var Blog\Blog $Blog
 * @var Blog\Post $Post
 */

$GetPreTags = function(Blog\Post $Post): Common\Datastore {

	$Output = new Common\Datastore;

	if(!$Post->Enabled)
	$Output->Push(Atlantis\Tag\Entity::New(
		Name: 'DRAFT',
		Type: 'btn-warning'
	));

	return $Output;
};

$Full ??= TRUE;
$BlogUser ??= NULL;
$ShowTags ??= TRUE;

?>

<!-- POST HEADING -->
<div class="d-none mb-4">
	<div class="atl-blog-dateline">
		<?php $Util->Print(Common\Date::FromDateString($Post->DateCreated)->Get(Common\Values::DateFormatFancyDate)) ?>
	</div>
	<div class="atl-blog-title">
		<h3><a href="<?php $Printer($App->RewriteURL($Post->GetURL(), $Post->GetTags())) ?>" class="border-0"><?php $Printer($Post->Title) ?></a></h3>
	</div>
	<div class="atl-blog-tags">
		<?php $Surface->Area('widgets/tag-buttons', [ 'Pre'=> $GetPreTags($Post), 'Tags'=> $Post->GetTags() ]) ?>
	</div>

	<?php $Surface->Area('blog/widgets/view-heading-extend', [ 'BlogUser'=> $BlogUser, 'Post'=> $Post ]) ?>

</div>

<!-- POST IMAGE -->
<?php if($Full && $Post->CoverImageID): ?>
<div class="d-none position-relative bg-light rounded mb-4">
	<div class="ratiobox widescreen bg-light rounded" style="overflow:hidden;">
		<div class="position-absolutely wallpapered covered opacity-50" style="background-color:#c0c0c0;background-image:url(<?php $Util->Print($Post->GetCoverImageURL('lg')) ?>); filter: blur(10px); transform: scale(1.1);">
		</div>
		<div class="position-absolutely wallpapered contained" style="background-color:transparent;background-image:url(<?php $Util->Print($Post->GetCoverImageURL('lg')) ?>);">
		</div>
	</div>
</div>
<?php endif; ?>

<!-- POST CONTENT -->
<div class="EditorContent mb-4">
	<?php echo $Full ? $Post->Content : $Post->GetExcerpt() ?>
</div>

<?php if($Full): ?>
<?php $Surface->Area('blog/widgets/view-post-extend', [ 'BlogUser'=> $BlogUser, 'Post'=> $Post ]) ?>
<?php endif; ?>
