<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Blog\BlogUser $BlogUser
 * @var Blog\Blog $Blog
 * @var Blog\Post $Post
 */

$Full ??= TRUE;

$Link = Blog\Struct\EditorLink::FromJSON($Post->Content);
$OutboundURL = $Full ? $Link->URL : $Post->GetURL();
$OutboundTab = $Full ? 'target="_blank"' : '';
$Domain = Atlantis\Util::DomainFromURL($Link->URL);

?>

<div class="<?php $Util->Print($Full ? 'jumbotron jumbotron-outline rounded mb-4' : '') ?>">
	<div class="mb-1">
		<span class="fw-bold text-uppercase">Source:</span>
		<a href="<?php $Util->Print($OutboundURL) ?>" <?php $Util->Print($OutboundTab) ?>><?php $Util->Print($Domain) ?></a>
	</div>
	<div class="mb-3">
		<span class="fw-bold text-uppercase">Date:</span>
		<?php $Util->Print(Common\Date::FromDateString($Link->Date)->Get(Common\Values::DateFormatFancyDate)) ?>
	</div>
	<div class="EditorContent">
		<?php echo $Link->Excerpt ?>
	</div>

	<?php if($Full): ?>
	<div class="text-align-center pt-4 font-size-large fw-bold">
		<a class="btn btn-primary" href="<?php $Util->Print($OutboundURL) ?>" <?php $Util->Print($OutboundTab) ?>>
			<i class="mdi mdi-open-in-new"></i>
			Read on <?php $Util->Print($Domain) ?>
		</a>
	</div>
	<?php endif; ?>
</div>

<?php if($Full): ?>
<div class="EditorContent">
	<?php echo $Link->Content ?>
</div>
<?php endif; ?>
