<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Blog\BlogUser $BlogUser
 * @var Blog\Blog $Blog
 * @var Blog\Post $Post
 */

$GetPreTags = function(Blog\Post $Post): Common\Datastore {

	$Output = new Common\Datastore;

	if(!$Post->Enabled)
	$Output->Push(Atlantis\Tag\Entity::New(
		Name: 'DRAFT',
		Type: 'btn-primary'
	));

	return $Output;
};

$Full ??= TRUE;
$BlogUser ??= NULL;
$Excerpt ??= TRUE;
$ShowTags ??= TRUE;

$Link = Blog\Struct\EditorLink::FromJSON($Post->Content);
$OutboundURL = $Full ? $Link->URL : $Post->GetURL();
$OutboundTab = $Full ? 'target="_blank"' : '';
$OutboundDomain = Atlantis\Util::DomainFromURL($Link->URL);

?>

<!-- POST HEADING -->
<div class="<?php $Util->Print($Full ? 'mb-4' : '') ?>">

	<!-- POST IMAGE -->
	<?php if($Full && $Post->CoverImageID): ?>
	<div class="position-relative bg-light rounded mb-4">
		<div class="ratiobox widescreen bg-light rounded" style="overflow:hidden;">
			<div class="position-absolutely wallpapered covered opacity-50" style="background-color:#c0c0c0;background-image:url(<?php $Util->Print($Post->GetCoverImageURL('lg')) ?>); filter: blur(10px); transform: scale(1.1);">
			</div>
			<div class="position-absolutely wallpapered contained" style="background-color:transparent;background-image:url(<?php $Util->Print($Post->GetCoverImageURL('lg')) ?>);">
			</div>
		</div>
	</div>
	<?php endif; ?>

	<h3 class="mb-3">
		<a href="<?php $Printer($Post->GetURL()) ?>"><?php $Printer($Post->Title) ?></a>
	</h3>

	<div class="mb-0">
		<span class="fw-bold text-uppercase">Date Shared:</span>
		<?php $Util->Print(Common\Date::FromDateString($Post->DateCreated)->Get(Common\Values::DateFormatFancyDate)) ?>
	</div>
	<div class="mb-0">
		<span class="fw-bold text-uppercase">Date Released:</span>
		<?php $Util->Print(Common\Date::FromDateString($Link->Date)->Get(Common\Values::DateFormatFancyDate)) ?>
	</div>
	<div class="mb-3">
		<span class="fw-bold text-uppercase">Source:</span>
		<a href="<?php $Util->Print($OutboundURL) ?>" <?php $Util->Print($OutboundTab) ?>><?php $Util->Print($OutboundDomain) ?></a>
	</div>

	<?php if($ShowTags): ?>
	<div class="mb-1">
		<?php $Surface->Area('widgets/tag-buttons', [ 'Pre'=> $GetPreTags($Post), 'Tags'=> $Post->GetTags() ]) ?>
	</div>
	<?php endif; ?>

	<?php $Surface->Area('blog/widgets/view-heading-extend', [ 'BlogUser'=> $BlogUser, 'Post'=> $Post ]) ?>

</div>

<!-- POST CONTENT: Link Preview -->
<div class="<?php $Util->Print($Full ? 'mb-8' : '') ?>">
	<div class="EditorContent">
		<div class="">
			<?php if($Full): ?>
			<h4 class="text-uppercase mb-0">
				Excerpt
			</h4>
			<hr class="mt-1 mb-3" />
			<?php endif; ?>

			<div class="fst-italic">
				<?php

				while(str_ends_with($Link->Excerpt, '<div><br></div>'))
				$Link->Excerpt = preg_replace('/<div><br ?\/?><\/div>$/', '', $Link->Excerpt);

				if(!$Full) {
					if($Excerpt)
					echo $Link->GetExcerpt();
				}

				else {
					if($Excerpt)
					echo $Link->Excerpt;
				}

				?>
			</div>

			<?php if($Full): ?>
			<div class="text-align-center pt-4 fw-bold">
				<div class="font-size-large mb-1">
					<a class="btn btn-primary btn-lg font-size-large" href="<?php $Util->Print($OutboundURL) ?>" <?php $Util->Print($OutboundTab) ?>>
						<i class="mdi mdi-open-in-new"></i>
						View Full Article...
					</a>
				</div>
				<div class="font-size-small fw-normal text-muted">
					<?php $Util->Print($OutboundDomain) ?>
				</div>
			</div>
			<?php endif; ?>

		</div>
	</div>
</div>

<?php if($Full && $Link->Content): ?>
<!-- POST CONTENT: Additional Content -->
<div class="mb-6">
	<h3 class="text-uppercase font-size-larger mb-0">
		More Information
	</h3>
	<hr class="mt-1 mb-3" />
	<div class="EditorContent">
		<?php echo $Link->Content ?>
	</div>
</div>
<?php endif; ?>

<?php if($Full): ?>
<!-- POST CONTENT: Theme Extension -->
<?php $Surface->Area('blog/widgets/view-post-extend', [ 'BlogUser'=> $BlogUser, 'Post'=> $Post ]) ?>
<?php endif; ?>
