<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Common\Datastore<Atlantis\Tag\Entity> $Tags
 * @var Common\Datastore<Atlantis\Profile\Entity> $Profiles
 */

################################################################################
################################################################################

$Breadcrumbs = (
	fn()=> $Surface->Area('admin/breadcrumbs', [ 'Trail' => [
		'Profiles' => '/ops/profiles'
	]])
);

$PublishStatusWord = (
	fn(Atlantis\Profile\Entity $P)
	=> match(TRUE) {
		($P->IsEnabled())
		=> 'PUBLISHED',

		default
		=> 'DRAFT'
	}
);

$TagFieldData = function(Common\Datastore $Tags) {

	$Output = new Common\Datastore;

	$Tags->Each(
		fn(Atlantis\Tag\Entity $T)
		=> $Output->Push([ 'ID'=> $T->ID, 'Name'=> $T->Name ])
	);

	return json_encode($Output->Export());
};

$TagFieldValue = function(Common\Datastore $Tags) {

	$Output = $Tags->Map(fn(Atlantis\Tag\Entity $T)=> $T->ID);

	return $Output->Join('-');
};

$Pager = (
	fn()=> print(Atlantis\UI\Pager::FromSurfaceWithResultSet($Surface, $Profiles))
);

$Searched = TRUE;

################################################################################
############################################################################# ?>

<div class="container">

	<?php $Breadcrumbs() ?>

	<div id="ProfileSearchForm" class="glassbox rounded p-3 mb-4">
		<form method="get">
		<div class="row align-items-center g-2">
			<div class="col-12 pos-relative">
				<div class="input-group">
					<div class="form-floating">
						<input type="text" name="q" class="form-control" placeholder="..." value="<?php $Util->Print($Query) ?>" />
						<label>Profile Search...</label>
					</div>
				</div>
			</div>
			<div class="col-12 pos-relative">
				<div class="input-group">
					<div class="form-floating">
						<input type="text" class="form-control" placeholder="..." data-form-field-tag-search />
						<label>Tags...</label>
						<input type="hidden" name="tags" value="" />
					</div>
				</div>
			</div>

			<div class="col-12">
				<hr class="bc-grey-dk my-2" />
			</div>
			<div class="col"></div>
			<div class="col-auto">
				<button type="button" class="btn btn-outline-light btn-lg fs-large" data-profile-new>
					<i class="mdi mdi-plus-thick"></i>
					New
				</button>
			</div>
			<div class="col-auto o-25">|</div>
			<div class="col-auto">
				<button type="submit" class="btn btn-light btn-lg fs-large">Search</button>
			</div>
		</div>
		</form>
	</div>

	<div id="ProfileSearchResults" class="glassbox rounded p-3">
		<div class="fs-large fw-bold tt-upper mb-0">
			<?php $Util->Print($Profiles->Count()) ?> Found

			<?php if($Route->Data->Get('UUID')): ?>
			[ UUID: <?php $Util->Print($Route->Data->Get('UUID')) ?> ]
			<?php endif; ?>
		</div>
		<hr class="mt-2 mb-3 bc-grey-dk" />
		<div class="row">

			<?php foreach($Profiles as $P): /** @var Atlantis\Profile\Entity $P */ ?>
			<div class="col-12">
				<div class="row align-items-center g-2">
					<div class="col-auto">
						<div class="ratiobox square wallpapered rounded-less border border-2 bc-grey-dk" style="width:50px;">
							<div class="pos-absolute pos-v-center pos-h-center tc-white">
								<i class="mdi mdi-note-outline"></i>
							</div>
						</div>
					</div>
					<div class="col">
						<div class="fs-large fw-bold">
							<a href="<?php $Util->Print($P->GetPageURL()) ?>" target="_blank"><?php $Util->Print($P->GetTitle()) ?></a>
						</div>
						<div class="row align-items-center g-2 fs-small o-50">
							<div class="col-auto">
								<?php $Util->Print($P->Alias) ?>
							</div>
							<div class="col-auto fs-smallerer o-50">//</div>
							<div class="col-auto">
								<?php $Util->Print($PublishStatusWord($P)) ?>
							</div>
							<?php if($P->ParentUUID): ?>
							<div class="col-auto fs-smallerer o-50">//</div>
							<div class="col-auto">
								<i class="mdi mdi-paperclip"></i>
							</div>
							<?php endif; ?>
						</div>
					</div>
					<div class="col-auto">
						<a href="<?php $Util->Print($P->GetPageURL()) ?>" target="_blank" class="btn btn-outline-white rounded-less">Open</a>
					</div>
					<div class="col-auto">
						<div class="dropdown">
							<button class="btn btn-outline-light rounded-less dropdown-toggle" type="button" data-bs-toggle="dropdown">
								<i class="mdi mdi-cog"></i>
								Options
							</button>
							<ul class="dropdown-menu dropdown-menu-end dropdown-menu-fancy rounded-less">
								<?php if($P->Enabled !== 1): ?>
								<button class="btn btn-block btn-light rounded-less ta-left" <?php echo $P->GetDataAttrForHTML() ?> data-profile-set-published>
									<i class="mdi mdi-check"></i> Set To Published
								</button>
								<?php endif; ?>
								<?php if($P->Enabled !== 0): ?>
								<button class="btn btn-block btn-light rounded-less ta-left" <?php echo $P->GetDataAttrForHTML() ?> data-profile-set-draft>
									<i class="mdi mdi-eye-off"></i> Set To Draft Mode
								</button>
								<?php endif; ?>
								<hr class="my-2" />
								<button class="btn btn-block btn-light rounded-less ta-left" <?php echo $P->GetDataAttrForHTML() ?> data-profile-delete>
									<i class="mdi mdi-trash-can"></i> Delete
								</button>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="col-12">
				<hr class="my-3 bc-grey-dk" />
			</div>
			<?php endforeach; ?>

		</div>

		<?php $Pager() ?>
	</div>

	<div class="mb-6">
	</div>

</div>

<script type="module">
import NUIUtil from '/share/nui/util.js';
import FieldTagSearch from '/share/atlantis/js/field-tag-search.js';
import ProfileEntityUtil from '/share/atlantis/js/util-profile-entity.js';

jQuery(function() {

	ProfileEntityUtil.WhenDocumentReady();

	////////

	jQuery('[data-form-field-clear-local]')
	.on('click', (jEv)=> NUIUtil.ClearLocalFormFields(jEv.currentTarget));

	jQuery('[data-form-field-tag-search]')
	.each(function(jEv) {

		let tags = new FieldTagSearch(this);
		let selection = <?php echo $TagFieldData($Tags) ?>;

		////////

		tags.allowNewTags = false;
		tags.onSelectionChange = function(btn) {

			(tags.element.parent())
			.find('input[type=hidden]')
			.each((idx, field)=> (field.value = tags.getSelectedTags().join('-')));

			return;
		};

		////////

		selection.forEach((selected)=> tags.onSelectItemsPrefillTag(selected));

		return;
	});

	return;
});
</script>
