<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Routes\Docs $Route
 * ...
 */

$Heading = $Route->FetchHeading('Subsystem Reference');

################################################################################
############################################################################# ?>

<div class="cargobay">
	<section>
		<div class="container">
			<?php echo $Heading ?>
			<hr />

			<div class="row g-4">
				<div class="col-12">
					<h3><a href="/docs/systems/password-tester">PasswordTester</a></h3>
					Check if a password fits the configured rule requirements for password complexity.
				</div>
				<div class="col-12">
					<h3><a href="/docs/systems/rate-limiter">RateLimiter</a></h3>
					Check if a client has been requesting things too frequently.
				</div>
			</ul>
		</div>
	</section>
</div>
