<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

use Nether\Atlantis\UI\SlideDeck;
use Nether\Atlantis\UI\SlideConfig;
use Nether\Atlantis\UI\SlideItem;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\UI\SlideDeck $Deck
 */

$Trail = [ 'Slide Decks' => '/ops/deckmgr', $Deck->GetName()=> '' ];

$Breadcrumbs = (fn()
	=> $Surface->GetArea('admin/breadcrumbs', [ 'Trail' => $Trail ])
);

################################################################################
############################################################################# ?>

<div class="container">

	<?php echo $Breadcrumbs(); ?>

	<div class="glassbox rounded p-3 mb-6">
		<div class="row g-4">
			<div class="col-12">
				<div class="form-floating">
					<input class="form-control" type="text" name="Name" title="Alias" placeholder="..." value="<?php $Util->Print($Deck->GetName()) ?>" />
					<label>Deck Name...</label>
				</div>
			</div>
			<div class="col-12">
				<div class="form-floating">
					<input class="form-control" type="text" name="Name" title="Alias" placeholder="..." value="<?php $Util->Print($Deck->GetAlias()) ?>" />
					<label>Alias / Filename...</label>
				</div>
			</div>
		</div>
	</div>

	<div class="glassbox rounded p-3 mb-6 hr-hide-last">
		<div class="row">
			<div class="col"></div>
			<div class="col-auto">
				<button class="btn btn-outline-light btn-lg fs-large" data-deck-editor-row-add>
					<i class="mdi mdi-plus-thick"></i>
					New Item
				</button>
			</div>
			<div class="col-auto">
				<button class="btn btn-outline-light btn-lg fs-large" data-deck-editor-save>
					<i class="mdi mdi-content-save"></i>
					Save
				</button>
			</div>
		</div>

		<hr />

		<?php foreach($Deck->GetItems() as $Item): /** @var SlideDeckItem $Item */ ?>
		<div id="row-<?php $Util->Print($Item->UUID) ?>" class="row align-items-center g-2" data-deck-editor-row>
			<div class="col-auto">
				<i class="mdi mdi-menu mr-0"></i>
			</div>
			<div class="col">
				<div class="form-floating mb-2">
					<input class="form-control" type="text" name="ImageURL" placeholder="..." value="<?php $Util->Print($Item->ImageURL) ?>" />
					<label>Image URL</label>
				</div>
				<div class="form-floating">
					<input class="form-control" type="text" name="ClickURL" placeholder="..." value="<?php $Util->Print($Item->ClickURL) ?>" />
					<label>Click URL</label>
				</div>
			</div>
			<div class="col-auto">
				<button class="btn btn-outline-danger btn-sm py-1" data-deck-editor-row-delete="<?php $Util->Print($Item->UUID) ?>">
					<i class="mdi mdi-delete mr-0"></i>
				</button>
			</div>
		</div>
		<hr id="hr-<?php $Util->Print($Item->UUID) ?>" />
		<?php endforeach; ?>
	</div>

	<div class="ta-center mb-6">
		<button class="btn btn-outline-light btn-lg fs-large" data-deck-editor-save>
			<i class="mdi mdi-content-save"></i>
			Save Changes
		</button>
	</div>

</div>

<script type="module">
import DeckMgr from '/share/atlantis/admin/deckmgr.js';
jQuery(DeckMgr.WhenDocumentReady);
</script>
