<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

use Nether\Atlantis\UI\SlideDeck;
use Nether\Atlantis\UI\SlideConfig;
use Nether\Atlantis\UI\SlideItem;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\UI\SlideDeck $Deck
 */

$Trail = [ 'Slide Decks' => '/ops/deckmgr', $Deck->GetName()=> '' ];

$Breadcrumbs = (fn()
	=> $Surface->GetArea('admin/breadcrumbs', [ 'Trail' => $Trail ])
);

################################################################################
############################################################################# ?>

<style type="text/css">
.squish { transform-origin: 0 50%; transform: translateX(0%); transition: transform 250ms ease; }
.squash { transform-origin: 0 50%; transform: translateX(100%); transition: transform 250ms ease; }
</style>

<div class="container">

	<?php echo $Breadcrumbs(); ?>

	<div class="glassbox rounded p-3 mb-6">
		<div class="row g-4">
			<div class="col-12">
				<div class="form-floating">
					<input class="form-control" type="text" name="Name" placeholder="..." value="<?php $Util->Print($Deck->GetName()) ?>" data-deck-name />
					<label>Deck Name...</label>
				</div>
			</div>
			<div class="col-12">
				<div class="form-floating">
					<input class="form-control" type="text" name="Alias" placeholder="..." value="<?php $Util->Print($Deck->GetAlias()) ?>" data-deck-alias />
					<label>Alias / Filename...</label>
				</div>
			</div>
		</div>
	</div>

	<div class="glassbox rounded p-3 mb-6">
		<div class="row">
			<div class="col"></div>
			<div class="col-auto">
				<button class="btn btn-outline-light btn-lg fs-large" data-deck-editor-row-add>
					<i class="mdi mdi-plus-thick"></i>
					New Item
				</button>
			</div>
			<div class="col-auto">
				<button class="btn btn-outline-light btn-lg fs-large" data-deck-editor-save>
					<i class="mdi mdi-content-save"></i>
					Save
				</button>
			</div>
		</div>

		<hr />

		<div class="hr-hide-last" style="overflow:hidden;" data-deck-editor>
			<?php

			foreach($Deck->GetItems() as $Item)
			$Surface->Area('admin/slidedecks/edit-row', [
				'Deck' => $Deck,
				'Item' => $Item
			]);

			?>

		</div>

		<div class="d-none" data-deck-editor-template>
			<?php

			$Surface->Area('admin/slidedecks/edit-row', [
				'Deck' => $Deck,
				'Item' => new Atlantis\UI\SlideDeckItem([ 'UUID'=> 'template' ])
			]);

			?>
		</div>

	</div>

	<div class="ta-center mb-6">
		<button class="btn btn-outline-light btn-lg fs-large" data-deck-editor-save>
			<i class="mdi mdi-content-save"></i>
			Save Changes
		</button>
	</div>

</div>

<script type="module">
import DeckMgr from '/share/atlantis/admin/deckmgr.js';
jQuery(()=> DeckMgr.WhenDocumentReady());
</script>
