<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Database\ResultSet $Videos
 */

$ParentUUID ??= NULL;

?>

<div class="atl-video-list hr-hide-last">
	<?php foreach($Videos as $VK=> $Video): /** @var Atlantis\Media\VideoThirdParty $Video */ ?>
	<div class="row">
		<div class="col-12 col-md-3">
			<div class="ratiobox widescreen wallpapered covered rounded bg-dark" style="background-image:url(<?php $Util->Print($Video->GetCoverImageURL()) ?>);">
				<a class="position-absolutely" href="<?php $Util->Print($Video->GetPageURL(TRUE)) ?>"></a>
				<div class="position-absolute position-bottom position-right p-1">
					<?php if($Route->IsUserAdmin()): ?>
					<button class="btn btn-light" data-videotp-cmd="edit" <?php echo $Video->GetDataAttrForHTML() ?>><i class="mdi mdi-pencil mr-0"></i></button>
					<button class="btn btn-danger" data-videotp-cmd="delete" data-parent-uuid="<?php $Util->Print($ParentUUID) ?>" <?php echo $Video->GetDataAttrForHTML() ?>><i class="mdi mdi-trash-can mr-0"></i></button>
					<?php endif; ?>
				</div>
			</div>
		</div>
		<div class="col-12 col-md mb-4">
			<h3><a href="<?php $Util->Print($Video->GetPageURL(TRUE)) ?>"><?php $Util->Print($Video->Title) ?></a></h3>
			<div>
				<b>Date Shared:</b>
				<?php $Util->Print($Video->DateCreated->Get(Common\Values::DateFormatFancyDate)) ?>
			</div>
			<div>
				<b>Date Released:</b>
				<?php $Util->Print($Video->DatePosted->Get(Common\Values::DateFormatFancyDate)) ?>
			</div>
			<div>
				<?php $Surface->Area('widgets/tag-buttons', [ 'Tags'=> $Video->GetTags() ]) ?>
			</div>
			<div class="mt-2">
				<a class="btn btn-primary" href="<?php $Util->Print($Video->GetPageURL(TRUE)) ?>">View Video</a>
			</div>
		</div>
	</div>
	<hr />
	<?php endforeach; unset($Video); ?>
</div>

<?php if(!$Videos->Count()): ?>
<div class="fst-italic">
	No videos have been added yet.
</div>
<?php endif; ?>



<script type="module">
import API from '/share/nui/api/json.js';
import DialogUtil from '/share/nui/util/dialog.js';
//import VideoTP from '/share/atlantis/video-tp.js';

jQuery(function() {

	jQuery('.zCmdVideoDelete')
	.on('click', function(){

		let vid = this.dataset.videoId;

		let diag = new DialogUtil.Window({
			title: 'Delete Video',
			labelAccept: 'Yes',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, vid)
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('DELETE', '/api/media/video-tp', data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.fillByRequest(
			'GET', '/api/media/video-tp',
			{ ID: vid },
			true,
			function(d, result) {
				d.body.prepend(`Delete <em>${result.payload.Title}</em>?`);
				return;
			}
		);

		return false;
	});

	jQuery('.zCmdVideoEdit')
	.on('click', function(){

		let vid = this.dataset.videoId;

		let diag = new DialogUtil.Window({
			title: 'Edit Video',
			labelAccept: 'Save',
			fields: [
				new DialogUtil.Field('hidden', 'ID', null, vid),
				new DialogUtil.Field('text', 'URL', null),
				new DialogUtil.Field('text', 'Title', null),
				new DialogUtil.Field('date', 'DatePosted', 'Date')
			],
			onAccept: function() {

				let data = this.getFieldData();
				let api = new API.Request('PATCH', '/api/media/video-tp', data);

				(api.send())
				.then(api.reload)
				.catch(api.catch);

				return;
			}
		});

		diag.fillByRequest(
			'GET', '/api/media/video-tp',
			{ ID: vid },
			true,
			function(d, result) {

				return;
			}
		);

		return false;
	});

	return;
});
</script>
