<?php

use Nether\Atlantis;

$PromoVideo = (fn()=> Atlantis\UI\PromoVideo::FromSurfaceWith($Surface, [
	'VideoURL' => '/themes/default/gfx/splishsplash.mp4',
	'Overlay'  => 'grad-focus-dark',
	'Title'    => 'Hi.',
	'Subline'  => 'I\'m a Website.',
	'Typeify'  => TRUE
]));

$Example = (fn()=> Atlantis\UI\Example::FromSurfaceWith($Surface, [
	'Title' => 'Hello World'
]));

?>

<div>
	<?php echo $PromoVideo() ?>
</div>

<div class="bg-alt-rows">
	<section>
		<div class="container pt-6 pb-6">
			<div class="mb-4">
				<?php echo $Example() ?>
			</div>
		</div>
	</section>
	<section>
		<div class="container pt-6 pb-6">
			<div class="ArticlePrelabel">Required Reading</div>
			<h1 class="fw-bold text-uppercase">Lorem Ipsum</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Neque volutpat ac tincidunt vitae semper quis. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Elit eget gravida cum sociis. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Dui id ornare arcu odio ut sem nulla pharetra diam. Lacinia quis vel eros donec ac. Ut consequat semper viverra nam libero. Massa tincidunt nunc pulvinar sapien et. Sagittis purus sit amet volutpat. Lacus vestibulum sed arcu non. Sed id semper risus in hendrerit gravida. Posuere urna nec tincidunt praesent semper feugiat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Non pulvinar neque laoreet suspendisse.</p>
			<p>Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. Arcu ac tortor dignissim convallis aenean et tortor. Morbi quis commodo odio aenean sed adipiscing diam donec. Vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra. Lacus sed viverra tellus in hac. Elit eget gravida cum sociis natoque. Suspendisse sed nisi lacus sed viverra. Odio ut sem nulla pharetra diam. Cras pulvinar mattis nunc sed blandit libero volutpat sed. Ac auctor augue mauris augue neque gravida.</p>
			<p>Felis eget nunc lobortis mattis aliquam. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Quis risus sed vulputate odio ut enim blandit volutpat. Nibh cras pulvinar mattis nunc sed blandit libero volutpat sed. Neque egestas congue quisque egestas. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Libero volutpat sed cras ornare arcu dui vivamus. Habitant morbi tristique senectus et netus et malesuada fames ac. Massa tincidunt dui ut ornare lectus sit amet est placerat. Amet massa vitae tortor condimentum lacinia quis vel eros. Ornare lectus sit amet est. Ipsum suspendisse ultrices gravida dictum fusce ut. Fermentum odio eu feugiat pretium nibh ipsum. Ac turpis egestas sed tempus urna et pharetra pharetra massa.</p>
		</div>
	</section>
	<section>
		<div class="container pt-6 pb-6">
			<div class="row">
				<div class="col-12 col-lg-6 mb-4 mb-lg-0">
					<div class="ratiobox widescreen wallpapered rounded-extra" style="background-image:url(/themes/default/gfx/bob.jpg);">
						<div class="position-absolutely opacity-70 bg-black"></div>
						<div class="position-absolutely">
							<div class="row h-100 align-items-center justify-content-center">
								<div class="col-auto text-center line-height-normal font-size-most-large font-family-monodtype  letter-space-literally-space text-uppercase">
									<div class="fw-bold mr-6">Herp</div>
									<div class="fw-light ml-6">Derp</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-12 col-lg-6 mb-4 mb-lg-0">
					<div class="ArticlePrelabel text-align-right">OMG WTF BBQ</div>
					<h1 class="fw-bold text-uppercase text-align-right">Egestas Diam In Arcu</h1>
					<p>Egestas diam in arcu cursus euismod quis viverra nibh cras. Urna cursus eget nunc scelerisque viverra mauris in aliquam sem. Dignissim cras tincidunt lobortis feugiat vivamus at. Imperdiet massa tincidunt nunc pulvinar sapien. At varius vel pharetra vel turpis nunc. Turpis in eu mi bibendum neque egestas congue quisque. Fermentum iaculis eu non diam phasellus vestibulum. Nisi vitae suscipit tellus mauris a. Amet purus gravida quis blandit turpis cursus in hac habitasse. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Condimentum vitae sapien pellentesque habitant morbi. Vitae nunc sed velit dignissim. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Nisi scelerisque eu ultrices vitae.</p>
				</div>
			</div>
		</div>
	</section>
</div>
