<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> web.atl <command> <args>

<span style="font-weight: bold; color: #9eb2d7;">•</span> <span style="font-weight: bold; color: #9eb2d7;">help <command>:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9eb2d7;">•</span> <span style="font-weight: bold; color: #9eb2d7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7b9bd5;">config</span> --dry
<span style="color: #676767;">Prepare web server configuration files.</span>

<span style="font-weight: bold; color: #7b9bd5;">setup</span>
<span style="color: #676767;">Push and confirm web server configuration setup.</span>

<span style="font-weight: bold; color: #7b9bd5;">reload</span>
<span style="color: #676767;">Kick web server to reload configuration.</span>

