<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Route->Title = 'Ace Editor & Code Viewer';
$Route->Info = 'Provides for wrapping content into an editable source code editor, provided by Ace not the hardware place.';

$Route->Pathbar->Items->Push(Atlantis\Struct\Item::New(
	Title: 'AceEditor',
	URL: '/docs/ui/ace-editor'
));

$Surface->Area('sensei/docs/__example-via-area', [
	'Areas' => [
		'Read-Only Code Viewer'
		=> 'sensei/docs/ui/ace-editor/example-basic'
	]
]);
