<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> dev.atl cachebust <command> <args>

<span style="font-weight: bold; color: #7b9bd5;">cachebust</span> --delete --update
<span style="color: #676767;">Manage the cache.bust file the theme engine uses.</span>

	--delete
	<span style="color: #676767;">Delete the cache.bust file.</span>

	--update
	<span style="color: #676767;">Update the cache.bust file.</span>

