<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> dev.atl loc <command> <args>

<span style="font-weight: bold; color: #7b9bd5;">loc</span> <directory> <...> --nether --ext=…
<span style="color: #676767;">Count lines of code in the specified directories.</span>

	--nether
	<span style="color: #676767;">Include installed NetherPHP libraries.</span>

	--ext=…
	<span style="color: #676767;">Comma delimited list of file extensions to include.</span>

