<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> dev.atl jsondbg <command> <args>

<span style="font-weight: bold; color: #7b9bd5;">jsondbg</span> --struct --json --touch --rewrite
<span style="color: #676767;">Debug tool for atlantis.json</span>

	--struct
	<span style="color: #676767;">Print the parsed structure.</span>

	--json
	<span style="color: #676767;">Print the JSON structure.</span>

	--touch
	<span style="color: #676767;">Touch the selected JSON file.</span>

	--rewrite
	<span style="color: #676767;">Rewrite the selected JSON file.</span>

