<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> dev.atl <command> <args>

<span style="font-weight: bold; color: #9eb2d7;">•</span> <span style="font-weight: bold; color: #9eb2d7;">help <command>:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9eb2d7;">•</span> <span style="font-weight: bold; color: #9eb2d7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7b9bd5;">cachebust</span> --delete --update
<span style="color: #676767;">Manage the cache.bust file the theme engine uses.</span>

<span style="font-weight: bold; color: #7b9bd5;">gen-cli-html</span>
<span style="color: #676767;">Generate the theme PHTML files for the CLI commmand helps.</span>

<span style="font-weight: bold; color: #7b9bd5;">jsondbg</span> --struct --json --touch --rewrite
<span style="color: #676767;">Debug tool for atlantis.json</span>

<span style="font-weight: bold; color: #7b9bd5;">loc</span> <directory> <...> --nether --ext=…
<span style="color: #676767;">Count lines of code in the specified directories.</span>

<span style="font-weight: bold; color: #7b9bd5;">run</span> <cmdname> --dry --cmd --hush
<span style="color: #676767;">Run one of the pre-defined command sequences from the project config.</span>

