<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> dev.atl run <command> <args>

<span style="font-weight: bold; color: #7b9bd5;">run</span> <cmdname> --dry --cmd --hush
<span style="color: #676767;">Run one of the pre-defined command sequences from the project config.</span>

	--dry
	<span style="color: #676767;">Only make believe.</span>

	--cmd
	<span style="color: #676767;">Show the command that it executes.</span>

	--hush
	<span style="color: #676767;">Do not show the output of commands unless error.</span>

