<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 */

################################################################################
################################################################################

?>

<div class="jumbotron rounded p-3">
	<div class="tt-upper fs-small fw-bold">
		Ops
		<hr class="mt-1 mb-3" />
	</div>
	<div class="row g-3">

		<div class="col-12 col-md-6">
			<a href="/ops/users/list" class="btn btn-dark btn-block ta-left">
				<i class="mdi mdi-account-group"></i>
				Manage Users
			</a>
		</div>

		<div class="col-12 pt-3">
			<span class="fw-bold fs-smaller tt-uppercase o-50">System Tools</span>
		</div>

		<div class="col-12 col-md-6">
			<a href="/ops/api" class="btn btn-dark btn-block ta-left">
				<i class="mdi mdi-compass"></i>
				API Tool
			</a>
		</div>

		<div class="col-12 col-md-6">
			<a href="/ops/email/test" class="btn btn-dark btn-block ta-left">
				<i class="mdi mdi-email-fast"></i>
				Email Send Test
			</a>
		</div>

	</div>
</div>
