<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Database;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Database\Struct\PrototypeFindResult $Rows
 * @var Database\Struct\PrototypeFindResult $Sources
 * @var Common\Date $Today
 * @var int $Hits
 * @var int $Visitors
 * @var int $Pages
 * @var string $Title
 * @var string $Path
 */

$Surface
->Area('dashboard/nav', [ 'Trail' => [
	'Traffic'        => '/dashboard/traffic/view?when=24hr',
	$Title           => NULL
]]);

$GetDateFor = function(string $When) {

	$Date = Common\Date::FromDateString($When);

	return $Date->Get(Common\Values::DateFormatYMD);
};

//Common\Dump::Var($Prev->Get(Common\Values::DateFormatYMDT12VO), TRUE);
//Common\Dump::Var($Today->Get(Common\Values::DateFormatYMDT12VO), TRUE);
//Common\Dump::Var($Next->Get(Common\Values::DateFormatYMDT12VO), TRUE);

?>

<!-- TRAFFIC HEADING -->
<div class="mb-4">
	<div class="row justify-content-between align-items-center">
		<?php if($Prev instanceof Common\Date): ?>
		<div class="col-auto">
			<a href="<?php $Util->Print($Route->QueryCooker([ 'when'=> $Prev ])) ?>" class="btn btn-dark">
				<i class="mdi mdi-chevron-left mr-0"></i>
				<span class="d-none d-md-inline"><?php $Util->Print($Prev->Get()) ?></span>
			</a>
		</div>
		<?php endif; ?>

		<div class="col-auto">
			<div class="fw-bold white-space-nowrap text-center font-size-large mb-0">
				<?php echo (str_replace(' of ', ' of<br class="d-md-none" /> ', $Title)) ?>
			</div>
		</div>

		<?php if($Next instanceof Common\Date): ?>
		<div class="col-auto">
			<?php if($Next->IsAfter($Now)): ?>
			<a href="<?php $Util->Print($Route->QueryCooker([ 'when'=> $Next ])) ?>" class="btn btn-dark">
				<span class="d-none d-md-inline"><?php $Util->Print($Next->Get()) ?></span>
				<i class="mdi mdi-chevron-right mr-0"></i>
			</a>
			<?php else: ?>
			<a href="#" class="btn btn-secondary disabled" disabled>
				<span class="d-none d-md-inline"><?php $Util->Print($Next->Get()) ?></span>
				<i class="mdi mdi-chevron-right mr-0"></i>
			</a>
			<?php endif; ?>
		</div>
		<?php endif; ?>
	</div>

	<?php if($Path): ?>
	<div class="mt-1">
		<b>Paths Starting With:</b>
		<?php $Util->Print($Path) ?>
	</div>
	<?php endif; ?>

	<hr class="mt-1 mb-0" />
</div>

<!-- TRAFFIC SUMMARY -->
<div class="jumbotron jumbotron-outline p-2 rounded mb-4">
	<div class="row">
		<div class="col-12 col-md-auto mb-2 mb-md-0">
			<div>
				<div class="font-size-most-large fw-bold"><?php $Util->Print($Hits) ?></div>
				<div class="font-size-smallest text-uppercase text-muted">Hits</div>
			</div>
		</div>
		<div class="col-12 col-md-auto mb-2 mb-md-0">
			<div>
				<div class="font-size-most-large fw-bold"><?php $Util->Print($Visitors) ?></div>
				<div class="font-size-smallest text-uppercase text-muted">Visitors</div>
			</div>
		</div>
		<div class="col-12 col-md-auto mb-2 mb-md-0">
			<div>
				<div class="font-size-most-large fw-bold"><?php $Util->Print($Pages) ?></div>
				<div class="font-size-smallest text-uppercase text-muted">Pages</div>
			</div>
		</div>

		<div class="col">
			<div class="row tight justify-content-md-end mb-1">
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-dark btn-sm pt-1 pb-1" href="<?php $Util->Print($Route->QueryCooker([ 'when'=> '24hr' ])) ?>">Past 24hr</a>
				</div>
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-dark btn-sm pt-1 pb-1" href="<?php $Util->Print($Route->QueryCooker([ 'when'=> '48hr' ])) ?>">48hr</a>
				</div>
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-dark btn-sm pt-1 pb-1" href="<?php $Util->Print($Route->QueryCooker([ 'when'=> '1wk' ])) ?>">Week</a>
				</div>
				<div class="col-auto mb-2">
					<a class="btn btn-block btn-dark btn-sm pt-1 pb-1" href="<?php $Util->Print($Route->QueryCooker([ 'when'=> '1mo' ])) ?>">Month</a>
				</div>
			</div>
			<div class="row tight justify-content-md-end mb-0">
				<div class="col-auto mb-0">
					<a class="btn btn-block btn-secondary btn-sm pt-1 pb-1" href="<?php $Util->Print($Route->QueryCooker([ 'when'=> $GetDateFor('today') ])) ?>">Today</a>
				</div>
				<div class="col-auto mb-0">
					<a class="btn btn-block btn-secondary btn-sm pt-1 pb-1" href="<?php $Util->Print($Route->QueryCooker([ 'when'=> $GetDateFor('yesterday') ])) ?>">Yesterday</a>
				</div>
				<div class="col-auto mb-0">
					<a class="btn btn-block btn-secondary btn-sm pt-1 pb-1" href="<?php $Util->Print($Route->QueryCooker([ 'when'=> sprintf('%s-%s', date('Y'), date('m')) ])) ?>">MTD</a>
				</div>
				<div class="col-auto mb-0">
					<a class="btn btn-block btn-secondary btn-sm pt-1 pb-1" href="<?php $Util->Print($Route->QueryCooker([ 'when'=> date('Y') ])) ?>">YTD</a>
				</div>
				<div class="col-auto mb-0">
					<a class="btn btn-block btn-secondary btn-sm pt-1 pb-1" data-traffic-cmd="date" href="#">Date...</a>
				</div>
			</div>
		</div>

	</div>
</div>

<!-- TRAFFIC DATA -->
<table class="table table-striped">
	<thead>
		<tr>
			<th>
				URL
			</th>
			<th class="th-shrink">
				Count
			</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($Rows as $Row): /** @var Atlantis\Struct\TrafficRow $Row */ ?>
		<tr>
			<td>
				<a href="<?php $Util->Print($Row->URL) ?>"><?php $Util->Print($Row->Path) ?></a>
			</td>
			<td class="text-align-center">
				<?php $Util->Print($Row->GetGroupCount()) ?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<table class="table table-striped">
	<thead>
		<tr>
			<th>
				Source
			</th>
			<th class="th-shrink">
				Count
			</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($Sources as $Domain => $Count): ?>
		<tr>
			<td><?php $Util->Print(Atlantis\Util::DomainToBrandName($Domain)) ?></td>
			<td class="text-center"><?php $Util->Print($Count) ?></td>
		</tr>
	<?php endforeach; unset($Domain, $Count); ?>
	</tbody>
</table>

<script type="module">
import DialogUtil from '/share/nui/util/dialog.js';

jQuery(function() {

	jQuery('[data-traffic-cmd=date]')
	.on('click', function() {
		let diag = new DialogUtil.Window({
			title: 'View Traffic By Date...',
			labelAccept: 'Go',
			fields: [
				new DialogUtil.Field('date', 'When', 'Date'),
			],
			onAccept: function() {

				let data = this.getFieldData();
				let url = new URL(location.href);

				url.searchParams.set('when', data.When);
				location.href = url;
				return;
			}
		});

		diag.show();
		return false;
	});

	return;
});
</script>
