<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Surface\Engine $Surface
 * @var bool $ConfirmReq - if email confirmation is required.
 * @var int $Updated - 1 = email updated, 2 = account activated
 * @var bool $Sent - if an email confirmation was sent.
 */

$Surface->Area('user/dashboard/nav', [ 'Trail' => [
	'Update Email Address' => NULL
]]);

?>

<div class="row justify-content-center">
	<div class="col-12 col-md-6">
		<?php if($Sent): ?>
		<div class="alert alert-info text-center mb-4">
			A confirmation link has been sent to your new Email address.
		</div>
		<?php endif; ?>

		<?php if($Updated === 1): ?>
		<div class="alert alert-success text-center mb-4">
			Your Email has been updated.
		</div>
		<?php elseif($Updated === 2): ?>
		<div class="alert alert-success text-center mb-4">
			Your account has been activated.
		</div>
		<?php endif; ?>

		<div class="mb-2">
			<strong>Current:</strong>
			<?php $Printer($User->Email) ?>
		</div>
		<form id="EmailChangeForm" method="post">
			<div class="mb-2">
				<input type="text" name="Email" class="form-control" placeholder="Email Address..." />
			</div>
			<div>
				<button type="submit" class="btn btn-primary btn-block fw-bold">Update Email</button>
			</div>
		</form>

	</div>
</div>

<script type="module">
import NUI from '/share/nui/nui.js?v=<?php $Printer($CacheBuster) ?>';

jQuery(function(){

	jQuery('#EmailChangeForm')
	.on('submit', function(){

		let form = new NUI.Form(this);
		let req = new NUI.Request('POST', '/api/dashboard/email');

		(req.send(form.getData()))
		.then(req.goto)
		.catch(req.catch);

		return false;
	});

	return;
});
</script>
