<?php

use Nether\Atlantis\Dashboard\SidebarGroup;
use Nether\Atlantis\Dashboard\SidebarGroupItem;

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Object\Datastore $SidebarItems
 */

$Surface->Area('user/dashboard/nav');

$StorageLocations = $App->Storage;

?>

<div class="row">
	<div class="col-12 col-md-4">

		<?php foreach($SidebarItems as $Group): /** @var SidebarGroup $Group */ ?>
		<dl class="PrettyModernBox">
			<dt>
				<span><?php $Printer($Group->Title) ?></span>
				<hr />
			</dt>
			<?php foreach($Group->Items as $Key => $Item): /** @var SidebarGroupItem $Item */ ?>
			<dd class="<?php $Printer($Group->Items->IsLastKey($Key) ? 'mb-0' : 'mb-2') ?>">
				<a href="<?php $Printer($Item->URL) ?>" class="btn btn-dark btn-left text-ellipsis">
					<i class="mdi mdi-fw <?php $Printer($Item->Icon ?? 'mdi-blank') ?>"></i>
					<?php $Printer($Item->Title) ?>
				</a>
			</dd>
			<?php endforeach; ?>
		</dl>
		<?php endforeach; unset($Key, $Item, $Group); ?>

	</div>
	<div class="col">

		<?php Nether\Common\Dump::Var($StorageLocations, TRUE) ?>

		<div id="Editor" class="Editor"></div>
		<script type="module">
		import Editor from '/share/nui/modules/editor/editor.js?v=<?php $Printer($CacheBuster) ?>';
		jQuery(function(){
			let editor = new Editor('#Editor');
			return;
		});
		</script>

	</div>
</div>
