<?php

$Surface->Area('user/dashboard/nav');

?>

<div class="row">
	<div class="col-12 col-md-4">
		<dl class="PrettyModernBox">
			<dt>
				<span>Account</span>
				<hr />
			</dt>
			<dd class="mb-2">
				<a href="/dashboard/settings/email" class="btn btn-dark btn-left text-ellipsis">
					<i class="mdi mdi-fw mdi-cog"></i>
					Change Email
				</a>
			</dd>
			<dd class="mb-2">
				<a href="/dashboard/settings/password" class="btn btn-dark btn-left text-ellipsis">
					<i class="mdi mdi-fw mdi-cog"></i>
					Change Password
				</a>
			</dd>
			<dd class="mb-0">
				<a href="/dashboard/settings/auth" class="btn btn-dark btn-left text-ellipsis">
					<i class="mdi mdi-fw mdi-cog"></i>
					Manage Connections
				</a>
			</dd>
		</dl>
	</div>
	<div class="col">

	</div>
</div>
