<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Surface\Engine $Surface
 * @var bool $HasNoPassword - if the current user has no password.
 * @var bool $Updated - if the password was updated.
 */

$Surface->Area('user/dashboard/nav', [ 'Trail' => [
	'Change Password' => NULL
]]);

?>

<div class="row justify-content-center">
	<div class="col-12 col-md-6">
		<form id="PasswordChangeForm" method="post">

			<?php if($Updated): ?>
			<div class="alert alert-success text-center mb-4">
				Your Password has been updated.
			</div>
			<?php endif; ?>

			<?php if($HasNoPassword): ?>
			<div class="mb-4">
				<p>
					Your account currently has no password and can only be logged into using the <a href="/dashboard/settings/auth">linked third-party accounts</a> originally used.
					Setting a password will allow you to still log in here if any unsavoury capitalism happenstances upon your linked accounts.
				</p>
			</div>
			<?php else: ?>
			<div class="mb-2">
				<input type="password" name="Password0" class="form-control" placeholder="Old Password..." />
			</div>
			<?php endif; ?>

			<div class="mb-2">
				<input type="password" name="Password1" class="form-control" placeholder="New Password..." />
			</div>
			<div class="mb-2">
				<input type="password" name="Password2" class="form-control" placeholder="Confirm New Password..." />
			</div>
			<div>
				<button type="submit" class="btn btn-primary btn-block fw-bold">Change Password</button>
			</div>

		</form>
	</div>
</div>

<script type="module">
import NUI from '/share/nui/nui.js?v=<?php $Printer($CacheBuster) ?>';

jQuery(function(){

	jQuery('#PasswordChangeForm')
	.on('submit', function(){

		let form = new NUI.Form(this);
		let req = new NUI.Request('POST', '/api/dashboard/password');

		(req.send(form.getData()))
		.then(req.goto)
		.catch(req.catch);

		return false;
	});

	return;
});
</script>
