<?php

/**
 * @var Nether\Atlantis\Engine $App
 * @var Nether\Atlantis\User $User
 * @var Nether\Avenue\Router $Router
 * @var Nether\Avenue\Route $Route
 * @var Nether\Surface\Engine $Surface
 * @var void   $Printer(string in)
 * @var void   $ThemeURL(string path, string theme)
 * @var string $Encoder(string in)
 * @var string $Selected(bool if)
 * @var string $Checked(bool if)
 * @var string $GetThemeURL(string path, string theme)
 * @var string $CacheBuster
 */

$ThemeURL = (fn(string $P, ?string $T='default')=> $ThemeURL($P, $T));

$Surface
->Set('Theme.Page.ThemeMode', (array_key_exists('theme', $_COOKIE) ? $_COOKIE['theme'] : 'dark' ))
->Set('Theme.Page.MainCSS', ($App->IsDev() ? 'css/styles.php' : 'css/styles.css'));

?>
<!DOCTYPE html>
<html lang="en" data-bs-theme="<?php $Surface->Show('Theme.Page.ThemeMode') ?>">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="shortcut icon" href="<?php $ThemeURL('gfx/favicon.ico') ?>" type="image/x-icon" />
	<title><?php $Surface->Show('Page.Title') ?></title>

	<script type="text/javascript" src="<?php $ThemeURL('lib/js/jquery.min.js') ?>"></script>
	<script type="text/javascript" src="<?php $ThemeURL('lib/js/bootstrap.bundle.min.js') ?>"></script>
	<script type="module">import Main from '/share/atlantis/main.js';</script>
	<script type="module">import Main from '<?php $ThemeURL('js/main.js') ?>';</script>

	<link rel="stylesheet" type="text/css" href="<?php $ThemeURL("lib/css/bootstrap.min.css?v={$CacheBuster}") ?>" />
	<link rel="stylesheet" type="text/css" href="<?php $ThemeURL("lib/css/materialdesignicons.min.css?v={$CacheBuster}") ?>" />
	<link rel="stylesheet" type="text/css" href="<?php $ThemeURL("lib/css/simple-icons.min.css?v={$CacheBuster}") ?>" />
	<link rel="stylesheet" type="text/css" href="<?php $ThemeURL("{$Surface->Get('Theme.Page.MainCSS')}?v={$CacheBuster}") ?>" />

	<meta property="og:type" content="article" />
	<meta property="og:url" content="<?php $Util->Print($Router->Request->GetURL()) ?>" />
	<meta property="og:title" content="<?php $Surface->Show('Page.Title') ?>" />
	<meta property="og:image" content="<?php $Surface->Show('Page.ImageURL') ?>" />
	<meta property="og:description" content="" />

	<meta name="twitter:card" content="summary" />
	<meta name="twitter:domain" content="<?php $Util->Print($Router->Request->Domain) ?>" />
	<meta name="twitter:title" content="<?php $Surface->Show('Page.Title') ?>" />
	<meta name="twitter:image" content="<?php $Surface->Show('Page.ImageURL') ?>" />
	<meta name="twitter:creator" content="" />

	<!-- Additional Styles -->
	<?php foreach($Surface->Get('Theme.Page.Styles') as $StyleURL): ?><link rel="stylesheet" type="text/css" href="<?php $Printer($StyleURL) ?>" />
	<?php endforeach; unset($StyleURL); ?>

	<!-- Additional Scripts -->
	<?php foreach($Surface->Get('Theme.Page.Scripts') as $ScriptURL): ?><script type="text/javascript" src="<?php $Printer($ScriptURL) ?>"></script>
	<?php endforeach; unset($ScriptURL); ?>

</head>
<body>

<?php $Surface->Area('design/header') ?>

<?php $Surface->Area('design/main', [ 'Output'=> $Output ]) ?>

<?php $Surface->Area('design/footer') ?>

<script type="module">
jQuery(function(){

	jQuery('[data-bs-toggle="tooltip"]')
	.each((k, el)=> new bootstrap.Tooltip(el));

	return;
});
</script>

</body>
</html>