<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Surface;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\User $User
 * @var Avenue\Router $Router
 * @var Avenue\Route $Route
 * @var Surface\Engine $Surface
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var string $CacheBuster
 */

################################################################################
################################################################################

$PageThemeMode = $Surface->Get('Page.Theme.Mode');
$PageFavIconURL = $Surface->Get('Page.Theme.FavIconURL') ?? $Surface->Get('Page.FavIconURL');
$PageBodyClasses = $Surface->Get('Page.Body.Classes');
$PageSubheader = $Surface->Get(Surface\Theme::KeyThemeSubheader);
$PageThemeMainCSS = $Surface->Get('Theme.Page.MainCSS');
$PageTitle = $Surface->Get('Page.Title');
$PageImageURL = $Surface->Get('Page.ImageURL');
$PageURL = $Router->Request->GetURL();
$PageDomain = $Router->Request->Domain;

////////

$ShowPageHeader = !($Surface->Get('Page.SkipHeader') ?? FALSE);
$ShowPageSubheader = ($PageSubheader !== NULL);
$ShowPageContent = !($Surface->Get('Page.SkipContent') ?? FALSE);
$ShowPageFooter = !($Surface->Get('Page.SkipFooter') ?? FALSE);
$ShowPageShutdown = !($Surface->Get('Page.SkipShutdown') ?? FALSE);

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

?>
<!DOCTYPE html>
<html lang="en" data-bs-theme="<?php $Util->Print($PageThemeMode) ?>">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title><?php $Util->Print($PageTitle) ?></title>
	<link rel="shortcut icon" href="<?php $Util->Print($PageFavIconURL) ?>" type="image/x-icon" />

	<script type="text/javascript" src="<?php $Util->ThemeURL('lib/js/jquery.min.js', 'default') ?>"></script>
	<script type="text/javascript" src="<?php $Util->ThemeURL('lib/js/bootstrap.bundle.min.js', 'default') ?>"></script>
	<script type="module">import Main from '/share/atlantis/main.js';</script>
	<script type="module">import Main from '<?php $Util->ThemeURL('js/main.js', 'default') ?>';</script>

	<link rel="stylesheet" type="text/css" href="<?php $Util->ThemeURL("lib/css/bootstrap.min.css?v={$CacheBuster}", 'default') ?>" />
	<link rel="stylesheet" type="text/css" href="<?php $Util->ThemeURL("lib/css/materialdesignicons.min.css?v={$CacheBuster}", 'default') ?>" />
	<link rel="stylesheet" type="text/css" href="<?php $Util->ThemeURL("lib/css/simple-icons.min.css?v={$CacheBuster}", 'default') ?>" />
	<link rel="stylesheet" type="text/css" href="<?php $Util->ThemeURL("{$PageThemeMainCSS}?v={$CacheBuster}", 'default') ?>" />

	<meta property="og:type" content="article" />
	<meta property="og:url" content="<?php $Util->Print($PageURL) ?>" />
	<meta property="og:title" content="<?php $Util->Print($PageTitle) ?>" />
	<meta property="og:image" content="<?php $Util->Print($PageImageURL) ?>" />
	<meta property="og:description" content="" />

	<meta name="twitter:card" content="summary" />
	<meta name="twitter:domain" content="<?php $Util->Print($PageDomain) ?>" />
	<meta name="twitter:title" content="<?php $Util->Print($PageTitle) ?>" />
	<meta name="twitter:image" content="<?php $Util->Print($PageImageURL) ?>" />
	<meta name="twitter:creator" content="" />

	<!-- Additional Styles -->
	<?php foreach($Surface->Get('Theme.Page.Styles') as $StyleURL): ?><link rel="stylesheet" type="text/css" href="<?php $Printer($StyleURL) ?>" />
	<?php endforeach; unset($StyleURL); ?>

	<!-- Additional Scripts -->
	<?php foreach($Surface->Get('Theme.Page.Scripts') as $ScriptURL): ?><script type="text/javascript" src="<?php $Printer($ScriptURL) ?>"></script>
	<?php endforeach; unset($ScriptURL); ?>

	<!-- Additional Script Modules -->
	<?php foreach($Surface->Get('Theme.Page.Modules') as $ScriptURL): ?><script type="module" src="<?php $Printer($ScriptURL) ?>"></script>
	<?php endforeach; unset($ScriptURL); ?>

</head>
<body class="<?php $Util->Print($PageBodyClasses->Join(' ')) ?>">

<?php

if($ShowPageHeader)
$Surface->Area('design/header');

if($ShowPageHeader && $ShowPageSubheader)
$Surface->Area($PageSubheader, $__SCOPE);

if($ShowPageContent)
$Surface->Area('design/main', [ 'Output'=> $Output ]);

if($ShowPageFooter)
$Surface->Area('design/footer');

if($ShowPageShutdown)
$Surface->Area('design/shutdown');

?>

<script type="module">
jQuery(function(){

	jQuery('[data-bs-toggle="tooltip"]')
	.each((k, el)=> new bootstrap.Tooltip(el));

	return;
});
</script>

</body>
</html>