<?php

/**
 * @var Nether\Surface\Engine $Surface
 */

$CacheBuster = microtime(TRUE);

?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="shortcut icon" href="/themes/default/gfx/favicon.ico" type="image/x-icon" />
	<title><?php $Surface->Show('Page.Title') ?></title>

	<link rel="stylesheet" type="text/css" href="/themes/default/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="/themes/default/css/iconmonstr.min.css" />
	<link rel="stylesheet" type="text/css" href="/themes/default/css/materialdesignicons.min.css" />
	<link rel="stylesheet" type="text/css" href="/themes/default/css/nether-bootstrap-ext.css?v=<?php $Printer($CacheBuster) ?>" />
	<link rel="stylesheet" type="text/css" href="/themes/default/css/nether-sensei.css?v=<?php $Printer($CacheBuster) ?>" />
	<link rel="stylesheet" type="text/css" href="/themes/default/css/main.css?v=<?php $Printer($CacheBuster) ?>" />
	<script type="text/javascript" src="/themes/default/js/jquery.min.js"></script>
</head>
<body>

<?php $Surface->Area('design/header') ?>

<?php $Surface->Area('design/main', [ 'Output'=> $Output ]) ?>

<?php $Surface->Area('design/footer') ?>

</body>
</html>