<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\UI\SiteMenuPage $Element
 * ...
 */

// data-bs-scroll="true" no bootstrap auto managed body props/classes.
// data-bs-backdrop="false" no bootstrap auto managed overlay backdrops.

$ID ??= $Element->GetID();
$Title ??= $Element->Title;
$Content ??= $Element->Content;

$Content = match(TRUE) {
	($Content instanceof Surface\Element)
	=> $Content->Render(),

	(is_callable($Content))
	=> ($Content)($__SCOPE),

	default
	=> match(TRUE) {
		(str_starts_with($Content, 'area:'))
		=> $Surface->GetArea(substr($Content, 4), $__SCOPE),

		default
		=> $Content
	}
};

?>

<div id="<?php $Util->Print($ID) ?>" class="offcanvas offcanvas-end offcanvas-glass z-index-high" data-bs-scroll="true" data-bs-backdrop="false">
	<div class="offcanvas-header">
		<h5 class="offcanvas-title"><?php $Util->Print($Title) ?></h5>
		<button type="button" data-sitemenu-close="parent" class="btn-close">
		</button>
	</div>
	<div class="offcanvas-body">

<?php echo $Content ?>

	</div>
</div>
