<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Atlantis\UI\SiteMenu $Menu
 * @var Atlantis\UI\SiteMenuPage $Element
 * ...
 */

// data-bs-scroll="true" no bootstrap auto managed body props/classes.
// data-bs-backdrop="false" no bootstrap auto managed overlay backdrops.

$Content = match(TRUE) {
	($Element->Content instanceof Surface\Element)
	=> $Element->Content->Render(),

	(is_callable($Element->Content))
	=> ($Element->Content)($__SCOPE),

	default
	=> match(TRUE) {
		(str_starts_with($Element->Content, 'area:'))
		=> $Surface->GetArea(substr($Element->Content, 4), $__SCOPE),

		default
		=> $Element->Content
	}
};

?>

<div id="<?php $Util->Print($Element->GetID()) ?>" class="offcanvas offcanvas-end offcanvas-glass z-index-high" data-bs-scroll="true" data-bs-backdrop="false">
	<div class="offcanvas-header">
		<h5 class="offcanvas-title"><?php $Util->Print($Element->Title) ?></h5>
		<button type="button" data-<?php $Util->Print($Element->GetDataKey()) ?>-close="parent" class="btn-close">
		</button>
	</div>
	<div class="offcanvas-body">

<?php echo $Content ?>

	</div>
</div>
