<div class="jumbotron rounded mb-4">
	<div class="fw-bold text-uppercase">
		Admin: Upload Manager
	</div>
	<hr class="mt-0 mb-2" />

	<div class="mb-2">
		<a href="/dashboard/blog/new" class="btn btn-secondary btn-block text-align-left">
			<i class="mdi mdi-view-grid"></i>
			Browse Uploaded Files
		</a>
	</div>
	<div class="mb-0">
		<a href="/dashboard/blog/list" class="btn btn-secondary btn-block text-align-left">
			<i class="mdi mdi-upload"></i>
			Upload
		</a>
	</div>
</div>