<?php

use Nether\User;

/**
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Avenue\Route $Route
 * @var string $Action
 */

$HasApple = User\Library::IsAppleEnabled();
$HasGitHub = User\Library::IsGitHubEnabled();
$HasGoogle = User\Library::IsGoogleEnabled();
$HasDiscord = User\Library::IsDiscordEnabled();

$GetLinkWithGoto = function(string $URL) use($Route) {

	if($Route->Request->Query->Goto)
	$URL = (
		str_contains($URL, '?')
		? "{$URL}&goto={$Route->Request->Query->Goto}"
		: "{$URL}?goto={$Route->Request->Query->Goto}"
	);

	return $URL;
};

?>

<div class="PrettyModernBox hr-hide-last">

	<?php if($HasApple): ?>
	<div>
		<?php
		$Surface->Area('user/login-auth-button', [
			'Action' => $Action,
			'Name'   => 'Apple',
			'Icon'   => 'si si-apple',
			'URL'    => $GetLinkWithGoto('/auth/apple')
		]);
		?>
	</div>
	<hr class="opacity-10 mt-2 mb-2" />
	<?php endif; ?>

	<?php if($HasDiscord): ?>
	<div>
		<?php
		$Surface->Area('user/login-auth-button', [
			'Action' => $Action,
			'Name'   => 'Discord',
			'Icon'   => 'si si-discord',
			'URL'    => $GetLinkWithGoto('/auth/discord')
		]);
		?>
	</div>
	<hr class="opacity-10 mt-2 mb-2" />
	<?php endif; ?>

	<?php if($HasGitHub): ?>
	<div>
		<?php
		$Surface->Area('user/login-auth-button', [
			'Action' => $Action,
			'Name'   => 'GitHub',
			'Icon'   => 'si si-github',
			'URL'    => $GetLinkWithGoto('/auth/github')
		]);
		?>
	</div>
	<hr class="opacity-10 mt-2 mb-2" />
	<?php endif; ?>

	<?php if($HasGoogle): ?>
	<div>
		<?php
		$Surface->Area('user/login-auth-button', [
			'Action' => $Action,
			'Name'   => 'Google',
			'Icon'   => 'si si-google',
			'URL'    => $GetLinkWithGoto('/auth/google')
		]);
		?>
	</div>
	<hr class="opacity-10 mt-2 mb-2" />
	<?php endif; ?>

</div>
