<?php

/**
 * @var Nether\Surface\Engine $Surface
 */

$HasApple = Nether\User\Library::IsAppleEnabled();
$HasGitHub = Nether\User\Library::IsGitHubEnabled();
$HasTwitter = Nether\User\Library::IsTwitterEnabled();
$HasAnythingElse = ($HasApple || $HasGitHub || $HasTwitter);

?>

<div id="LoginForm">
	<div class="<?php $Printer($HasAnythingElse ? 'text-left' : 'text-center') ?> mb-4">
		<h4>Log In</h4>
	</div>

	<div class="row <?php $Printer($HasAnythingElse ? 'justify-content-between' : 'justify-content-center') ?> align-items-stretch">
		<div class="col-12 col-md-5 mb-4">
			<form method="post">
				<div class="row justify-content-center">
					<div class="col-12 mb-2">
						<input id="LoginUsername" type="text" class="form-control" name="Username" placeholder="Username..." />
					</div>
					<div class="col-12 mb-2">
						<input id="LoginPassword" type="text" class="form-control" name="Password" placeholder="Password..." />
					</div>
					<div class="col-12">
						<button id="LoginAccept" type="submit" class="btn btn-primary d-block w-100">Log In</button>
					</div>
				</div>
			</form>
		</div>
		<?php if($HasAnythingElse): ?>
		<div class="col-md-2 mb-4">
			<div class="FancyOrVH">
				<div></div>
				<label>Or</label>
				<div></div>
			</div>
		</div>
		<div class="col-12 col-md-5">

			<div class="PrettyModernBox">
				<div>
					<div class="row tight">
						<?php if($HasApple): ?>
						<div class="col-12 mb-2">
							<button class="btn btn-block btn-dark text-align-left">
								<i class="mdi mdi-fw mdi-apple mr-1"></i>
								<span>Log In via Apple</span>
							</button>
						</div>
						<?php endif; ?>
						<?php if($HasGitHub): ?>
						<div class="col-12 mb-0">
							<a href="/auth/github" class="btn btn-block btn-dark text-align-left">
								<i class="mdi mdi-fw mdi-github mr-1"></i>
								<span>Log In via GitHub</span>
							</a>
						</div>
						<?php endif; ?>
						<?php if($HasTwitter): ?>
						<div class="col-12 mb-2">
							<button class="btn btn-block btn-dark text-align-left">
								<i class="mdi mdi-fw mdi-twitter mr-1"></i>
								<span>Log In via Twitter</span>
							</button>
						</div>
						<?php endif; ?>
					</div>
				</div>
			</div>

		</div>
		<?php endif; ?>
	</div>
</div>

<script type="module">
import JsonRequest from '/share/atlantis/api/json-request.js?v=<?php $Printer($CacheBuster) ?>';

jQuery(function(){

	jQuery('#LoginForm form')
	.on('submit', function() {

		let input = jQuery(this).serializeArray();
		let data = new FormData;
		let req = new JsonRequest('POST', '/api/user/session/login', data);

		for(const item of input)
		data.set(item.name, item.value);

		(req.send())
		.then(function(result) {
			if(result.error !== 0) {
				alert(result.message);
				return;
			}

			location.href = '/';
			return;
		});

		return false;
	});

	return;
});
</script>
