<?php

use Nether\User;

/**
 * @var Nether\Surface\Engine $Surface
 * @var Nether\Avenue\Route $Route
 */

$HasThirdPartyAuth = User\Library::HasAnyThirdPartyAuth();
$TitleCSS = $HasThirdPartyAuth ? 'text-left' : 'text-center';
$ShiftyColumnCSS = $HasThirdPartyAuth ? 'justify-content-between' : 'justify-content-center';

?>

<div>
	<div class="<?php $Printer($TitleCSS) ?> mb-4">
		<h4>Log In</h4>
	</div>

	<div class="row <?php $Printer($ShiftyColumnCSS) ?> align-items-stretch">
		<div class="col-12 col-md-5 mb-4">
			<form id="LoginForm" method="post">
				<div class="row justify-content-center mb-2">
					<div class="col-12 mb-2">
						<input type="text" class="form-control" name="Username" placeholder="Email..." />
					</div>
					<div class="col-12 mb-2">
						<input type="password" class="form-control" name="Password" placeholder="Password..." />
					</div>
					<div class="col-12">
						<input type="hidden" name="Goto" value="<?php $Printer($Route->Request->Query->Goto) ?>" />
						<button type="submit" class="btn btn-primary d-block w-100">Log In</button>
					</div>
				</div>
			</form>
			<div class="text-center">
				<a href="/signup">Create Account</a> | <a href="/login/reset">Forgot Password?</a>
			</div>
			<script type="module">
			import NUI from '/share/nui/nui.js?v=<?php $Printer($CacheBuster) ?>';
			jQuery(function(){
				jQuery('#LoginForm')
				.on('submit', function() {

					let form = new NUI.Form(this);
					let req = new NUI.Request('LOGIN', '/api/user/session');

					(req.send(form.read()))
					.then(req.goto)
					.catch(req.catch);

					return false;
				});
				return;
			});
			</script>
		</div>
		<?php if($HasThirdPartyAuth): ?>
		<div class="col-md-2 mb-4">
			<?php $Surface->Area('misc/fancy-or') ?>
		</div>
		<div class="col-12 col-md-5">
			<?php $Surface->Area('user/login-auth', [ 'Action'=> 'Log In' ]) ?>
		</div>
		<?php endif; ?>
	</div>
</div>
