<?php

/**
 * @var Nether\Surface\Engine $Surface
 */

?>

<div id="LogoutConfirm" class="row justify-content-center">
	<div class="col-12 col-md-6">
		<h4>Log Out?</h4>
		<p>Are you sure you want to log out?</p>
		<div class="row justify-content-center">
			<div class="col">
				<button id="LogoutAccept" class="btn btn-primary d-block w-100">Log Out</button>
			</div>
			<div class="col-auto">
				<button id="LogoutReject" class="btn btn-secondary">Cancel</button>
			</div>
		</div>
	</div>
</div>

<script type="module">
import JsonRequest from '/share/atlantis/api/json-request.js?v=<?php $Printer($CacheBuster) ?>';

jQuery(function(){

	jQuery('#LogoutAccept')
	.on('click', function(){

		let req = new JsonRequest('POST', '/api/user/session/logout');

		(req.send())
		.then(function(result){

			location.href = '/';
			return;
		});

		return;
	});

	jQuery('#LogoutReject')
	.on('click', function(){
		location.href = '/';
		return;
	});

	return;
});
</script>
