<?php

use Nether\Atlantis;

/**
 * @var Routes\Docs $Route
 */

$Surface->Set([
	'Page.Section.Title' => 'CSS Reference',
	'Page.Title'         => 'Container Cargo Bay',
	'Page.Info'          => NULL
]);

?>

<div class="mb-6">
	<?php $Surface->Area('sensei/docs/css/__nav', [ 'Section'=> 'cargobay' ]) ?>
</div>

<div class="ta-center mb-4">
	<h3>.cargobay > .container</h3>
</div>

<div class="cargobay mb-4">
	<?php for($A = 0; $A < 5; $A++): ?>
	<div class="container">
		<div class="jumbotron">
			This is a Jumbotron in a Container in a Cargo Bay.
		</div>
	</div>
	<?php endfor; ?>
</div>

<hr class="border-0 mb-8" />

<div class="ta-center mb-4">
	<h3>.cargobay > section > .container</h3>
</div>

<div class="cargobay mb-6">
	<?php for($A = 0; $A < 5; $A++): ?>
	<section>
		<div class="container">
			<div class="jumbotron">
				This is a Jumbotron in a Container in a Section in a Cargo Bay.
			</div>
		</div>
	</section>
	<?php endfor; ?>
</div>

<hr class="border-0 mb-4" />
