<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Blog;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * @var Blog\Dashboard\BlogElement $Element
 */

?>



	<?php foreach($Element->Blogs as $Blog): /** @var Blog\BlogUser $Blog */ ?>

		<div class="jumbotron rounded">

			<!-- BLOG TITLE -->
			<div class="fw-bold text-uppercase">
				<a href="<?php $Util->Print($Blog->BlogUser->Blog->GetURL()) ?>"><?php $Util->Print($Blog->BlogUser->Blog->Title) ?></a>
			</div>
			<hr class="mt-0 mb-2" />

			<!-- BLOG STATS -->
			<div class="row mb-4">
				<div class="col-12 col-md-auto mb-2 mb-md-0">
					<div>
						<div class="font-size-most-large fw-bold"><?php $Util->Print(number_format($Blog->Hits)) ?></div>
						<div class="font-size-smallest text-uppercase text-muted">Views Last 24hr</div>
					</div>
				</div>
				<div class="col-12 col-md-auto mb-0 mb-md-0">
					<div>
						<div class="font-size-most-large fw-bold"><?php $Util->Print(number_format($Blog->Visitors)) ?></div>
						<div class="font-size-smallest text-uppercase text-muted">Unique Visitors</div>
					</div>
				</div>
			</div>

			<!-- BLOG BUTTONS -->
			<div class="mb-2">
				<a href="<?php $Util->Print($Blog->BlogUser->Blog->GetWriteURL()) ?>" class="btn btn-dark btn-block text-align-left">
					<i class="mdi mdi-plus-thick"></i>
					New Post
				</a>
			</div>
			<div class="mb-2">
				<a href="#" class="btn btn-dark btn-block text-align-left">
					<i class="mdi mdi-account-details"></i>
					Hit Stats
				</a>
			</div>
			<div class="mb-0">
				<a href="<?php $Util->Print($Blog->BlogUser->Blog->GetSettingsURL()) ?>" class="btn btn-dark btn-block text-align-left">
					<i class="mdi mdi-cog"></i>
					Settings
				</a>
			</div>

		</div>

	<?php endforeach; ?>

