<span style="font-weight: bold; color: #9eb2d7;">USAGE:</span> ssl.atl <command> <args>

<span style="font-weight: bold; color: #9eb2d7;">•</span> <span style="font-weight: bold; color: #9eb2d7;">help <command>:</span> <span>view help for specific command.</span>
<span style="font-weight: bold; color: #9eb2d7;">•</span> <span style="font-weight: bold; color: #9eb2d7;">help --verbose:</span> <span>view all help for all commands.</span>

<span style="font-weight: bold; color: #7b9bd5;">config</span>
<span style="color: #676767;">Tool to configure the SSL cert for this project.</span>

<span style="font-weight: bold; color: #7b9bd5;">renew</span>
<span style="color: #676767;">Renew the SSL cert for this project.</span>

<span style="font-weight: bold; color: #7b9bd5;">cron</span>
<span style="color: #676767;">Shows the line to be added to crontab to auto-renew SSL.</span>

<span style="font-weight: bold; color: #7b9bd5;">lookup</span> <domain>
<span style="color: #676767;">Check the status of an SSL cert for any domain on the internet.</span>

