<?php

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Routes\Docs $Route
 * ...
 */

$Route->Pathbar->Items->Push(Atlantis\Struct\Item::New(
	Title: 'ssl.atl'
));

$Files = Nether\Common\Filesystem\Indexer::DatastoreFromPath(dirname(__FILE__), $Page);

$Files
->Remap(fn(string $F)=> str_replace('.phtml', '', basename($F)))
->Filter(fn(string $F)=> str_starts_with($F, 'help'))
->Sort();

?>

<div class="cargobay">
	<section class="pt-0">
		<div class="container">

<?php foreach($Files as $File): ?>
<div class="jumbotron rounded mb-4">
	<pre><?php $Surface->Area("sensei/docs/cli/{$Page}/{$File}") ?></pre>
</div>
<?php endforeach; ?>

		</div>
	</section>
</div>


