<?php

/**
 * @var Nether\Atlantis\UI\AceEditor $Element
 */

$Surface
->AddStyleURL('/share/atlantis/lib/ace/ace.css')
->AddScriptURL('/share/atlantis/lib/ace/ace.js')
->AddScriptReadyFrag('elements/ace-editor/ready');

?>

<div class="<?php $Util->Print($Element->GetClassesForHTML('atl-code-viewer o-anim-fast o-0')) ?>" data-code-lang="php" data-code-theme="clouds_midnight">
	<section class="ace_editor"><?php $Util->Print($Element->Content) ?></section>
</div>
