(function(){

	let delayStack = 0;
	let delayBump = 100;

	let initViewer = function() {

		let that = jQuery(this);
		let lang = that.attr('data-code-lang');
		let theme = that.attr('data-code-theme');
		let viewer = null;

		////////

		if(!lang)
		lang = 'text';

		if(!theme)
		theme = 'monokai';

		////////

		viewer = ace.edit(this.querySelector(':scope > section'), {
			mode: `ace/mode/${lang}`,
			theme: `ace/theme/${theme}`,
			maxLines: 1234,
			readOnly: true,
			highlightActiveLine: false,
			printMarginColumn: false,
			cursorStyle: 'smooth'
		});

		////////

		// all of them get ready fast, but the reveals are waterfalled
		// because i think that looks neat. also the ace devs swear its
		// super not async so this is why its not an on load type of
		// thing on that. future me is going to think this is stupid
		// if they aint reminded.

		setTimeout(
			(()=> that.removeClass('o-0')),
			(delayStack += delayBump)
		);

		return;
	};

	jQuery('.atl-code-viewer')
	.each(initViewer);

	return;
})();
