<?php ##########################################################################
################################################################################

use Nether\Atlantis;
use Nether\Avenue;
use Nether\Common;
use Nether\Surface;
use Nether\User;

/**
 * @var Atlantis\Engine $App
 * @var Atlantis\Struct\TemplateHelper $Util
 * @var Avenue\Router $Router
 * @var Surface\Engine $Surface
 * @var User\EntitySession $User
 *
 * @var Atlantis\PublicWeb $Route
 * ...
 */

$Surface->Set([
	'Page.Section.Title' => 'CSS Reference',
	'Page.Title'         => 'Dyes',
	'Page.Info'          => NULL
]);

################################################################################
################################################################################

$Colours = new Common\Datastore([
	'black', 'white',
	'dark', 'light',
	'red', 'orange', 'yellow', 'green', 'blue', 'purple'
]);

?>

<div class="container">
	<div class="mb-8">
		<h2 class="tt-upper">Solid Buttons</h2>
		<hr />
		<div class="row g-4">
			<?php foreach($Colours as $C): ?>
			<div class="col-12 col-md-3">
				<button class="btn btn-block <?php $Util->Print("btn-{$C}") ?> ta-left">
					<i class="mdi mdi-circle"></i>
					<?php $Util->Print($C) ?>
				</button>
			</div>
			<?php endforeach; ?>
		</div>
	</div>

	<div class="mb-8">
		<h2 class="tt-upper">Outline Buttons</h2>
		<hr />
		<div class="row g-4">
			<?php foreach($Colours as $C): ?>
			<div class="col-12 col-md-3">
				<button class="btn btn-block <?php $Util->Print("btn-outline-{$C}") ?> ta-left">
					<i class="mdi mdi-circle"></i>
					<?php $Util->Print($C) ?>
				</button>
			</div>
			<?php endforeach; ?>
		</div>
	</div>
</div>


