<?php

/**
 * @var Nether\Email\Struct\LibraryConfigInfo $LibInfo
 */

$Surface->Area('admin/breadcrumbs', [ 'Trail' => [
	'Email Send Test' => NULL
]]);

?>

<?php if($Surface->Get('TestEmailSent')): ?>
<div class="alert alert-success mb-4">
	An attempt has been made.
	If it does not arrive check the email log file.
</div>
<?php endif; ?>

<div class="row justify-content-center mb-4">
	<div class="col-12 col-md-12 col-lg-12">
		<form method="post">
			<div class="row tight">
				<div class="col-12">
					<div class="fw-bold">Send Test To:</div>
					<input type="text" class="form-control" name="Email" value="<?php $Printer($User->Email) ?>" />
				</div>
				<div class="col-12 mb-2"></div>
				<div class="col">
					<select name="Via" class="form-select">
						<?php foreach($LibInfo->GetReadyServices() as $ServInfo): /** @var Nether\Email\Struct\ServiceConfigInfo $ServInfo */ ?>
						<option value="<?php $Printer($ServInfo->Key) ?>" <?php echo($Selected($LibInfo->IsDefaultKey($ServInfo->Key))) ?>>via <?php $Printer($ServInfo->Name) ?></option>
						<?php endforeach; unset($ServName, $ServInfo); ?>
					</select>
				</div>
				<div class="col-auto">
					<button class="btn btn-primary btn-block">
						<i class="mdi mdi-fw mdi-email mr-2"></i> Send
					</button>
				</div>
			</div>
		</form>
	</div>
</div>

